### ISSUE TITLE
padrino-gen plugin not working.

### ISSUE THREAD

**Issue by abuiles** [padrino/padrino-framework#1204]
I tried to install a plugin and was getting an error that the template was  not found, even with it was there. I create a clean app and tried it again, and didn't work, pasting the whole process.

```
terminus-2 ~/Code $ padrino-gen project test_padrino
      create  
      create  .gitignore
      create  config.ru
      create  config/apps.rb
      create  config/boot.rb
      create  public/favicon.ico
      create  public/images
      create  public/javascripts
      create  public/stylesheets
      create  tmp
      create  .components
      create  app
      create  app/app.rb
      create  app/controllers
      create  app/helpers
      create  app/views
      create  app/views/layouts
      create  Gemfile
      create  Rakefile
    skipping  orm component...
    skipping  test component...
    skipping  mock component...
    skipping  script component...
    applying  slim (renderer)...
       apply  renderers/slim
      insert  Gemfile
    skipping  stylesheet component...
   identical  .components
       force  .components

=================================================================
test_padrino is ready for development!
=================================================================
$ cd ./test_padrino
$ bundle
=================================================================

terminus-2 ~/Code $ cd test_padrino/
terminus-2 ~/Code/test_padrino $ ls
Gemfile         app     config.ru   tmp
Rakefile    config      public
terminus-2 ~/Code/test_padrino $ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.0.4) 
Using i18n (0.6.4) 
Using multi_json (1.7.2) 
Using activesupport (3.2.12) 
Using bundler (1.3.4) 
Using rack (1.5.2) 
Using url_mount (0.2.1) 
Using http_router (0.11.0) 
Using mime-types (1.21) 
Using polyglot (0.3.3) 
Using treetop (1.4.12) 
Using mail (2.5.3) 
Using rack-protection (1.5.0) 
Using tilt (1.3.6) 
Using sinatra (1.4.2) 
Using thor (0.17.0) 
Using padrino-core (0.11.0) 
Using padrino-helpers (0.11.0) 
Using padrino-admin (0.11.0) 
Using padrino-cache (0.11.0) 
Using padrino-gen (0.11.0) 
Using padrino-mailer (0.11.0) 
Using padrino (0.11.0) 
Installing temple (0.5.5) 
Installing slim (1.3.6) 
Your bundle is complete!
It was installed into /Users/adolfobuiles/.rvm/gems/ruby-1.9.3-p194
terminus-2 ~/Code/test_padrino $ padrino plugin bootstrap
Could not find task "plugin".
terminus-2 ~/Code/test_padrino $ padrino-gen plugin bootstrap
       apply  https://github.com/padrino/padrino-recipes/raw/master/plugins/bootstrap_plugin.rb
  The template at https://github.com/padrino/padrino-recipes/raw/master/plugins/bootstrap_plugin.rb could not be found!
terminus-2 ~/Code/test_padrino $ 
```

Btw, `https://github.com/padrino/padrino-recipes/raw` now redirects to
`https://raw.github.com/padrino/padrino-recipes/master/` I think the problem is somewhere around that, I tried to fix it, but just changing the path didn't work. Maybe I could have a better look later.

**Comment by konung** [comment]
Chiming it 3 years later - same issue, with a solution. 

Confirming the same issue on Windows 7 with ruby 2.2.3 & Rubygems 2.**4**.4 . Upgrading rubygems (current 2.**6**.4) and setting SSL env  - solves the underlying problem - SSL issue. The error - is just not propagated properly - so it was a bit of a mystery. 

Certificate can be obtained here: https://curl.haxx.se/ca/cacert.pem ( or search google)

Option 1 - session ENV - in the file or in a console
ENV["SSL_CERT_FILE"] = "C:\\tools\\local\\ruby\\223\\cacert.pem"
my Ruby live in c:\tools , your's might be in a different folder. 

Option2 - System ENV  via console ( make sure you use cmd and not powershell - there is a conflit with one of the powershell cmdlets)
set SSL_CERT_FILE C:\tools\local\ruby\223\cacert.pem

You can also do this in powershell: 
CMD /C “ set SSL_CERT_FILE C:\tools\local\ruby\223\cacert.pem”

Don't forget to restart your console ( completely!)
 
My Debian boxes didn't have any issues ( using rbenv), but I'm guessing it might be a similar issue.
