### ISSUE TITLE
padrino-core/application/rendering/extensions/erubis.rb causes other Sinatra erb templates to be HTML escaped

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1256]
The way in which padrino registers `Padrino::Erubis::Template` to be used when the `erb` rendering method is called, causes responses from other Sinatra applications to be entirely escaped.

```
class Middleware < Sinatra::Base

  get '/foo'
    erb :foo
  end

end

class App < Padrino::Application
  use Middleware
end

$ curl http://localhost:3000/
&lt;!DOCTYPE html&gt;
&lt;!-- saved from url=(0014)about:internet --&gt;
&lt;html&gt;
&lt;head&gt;
....
```

**Comment by bethesque** [comment]
I took my project and ripped out everything except the code to reproduce the issue. It turns out that it's the erubis gem being included in the Gemfile that causes the issue.

https://github.com/bethesque/padrino-html-erb-escape

Unfortunately, the erubis gem is a dependency of a dependency of a dependency, so I can't rip it out.

**Comment by namusyaka** [comment]
Thanks for providing that.
This can be resolved by adding `register Padrino::Rendering` or `register Padrino::Helpers`.
In addition, the following patch can also resolve your problem.

```diff
diff --git a/Gemfile b/Gemfile
index 655d25e..a052147 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,7 +1,7 @@
 source 'https://rubygems.org'

 gem 'rack'
-gem 'padrino', '~>0.12.4'
+gem 'padrino-core', '~>0.12.4'
 gem 'rack-test'
 gem 'rake', '~>10.0'
 gem 'rspec', '~>3.0'
```

```diff
diff --git a/lib/app.rb b/lib/app.rb
index 771f7c2..698165a 100644
--- a/lib/app.rb
+++ b/lib/app.rb
@@ -1,4 +1,4 @@
-require 'padrino'
+require 'padrino-core'

 Padrino::Logger::Config[:development] = { :log_level => :warn }
```
Your project bundled `padrino-helpers`, so the tilt prefering code was `require`d automatically.
https://github.com/padrino/padrino-framework/blob/master/padrino-helpers/lib/padrino/rendering/erubis_template.rb#L62

**Comment by bethesque** [comment]
Right, I see. Thanks very much for your help @namusyaka.
