### ISSUE TITLE
Add rom-rb support

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-framework#1312]
Add https://github.com/rom-rb/rom support once it is released for public use.

**Comment by skade** [comment]
rom-rb is released now by the way.

**Comment by wikimatze** [comment]
Sounds great, I think the integration is a bigger project.

**Comment by ujifgc** [comment]
Closing in favor of #1494

**Comment by postmodern** [comment]
@ujifgc what about `padrino-gen model` templates for generating the ROM models?

**Comment by ujifgc** [comment]
Of course, this should be mentioned in #1494. These tasks are close enough to be done together.
