### ISSUE TITLE
No support for dumping AR schema to sql

### ISSUE THREAD

**Issue by maca** [padrino/padrino-framework#1390]
There is no way to dump and load the schema to/from sql, ruby schema generation is hardcoded.

`ActiveRecord::Base.schema_format = :sql` is ignored.

This is important when using postgres hstore extention that cannot be represented in a ruby schema dump for AR < 4

**Comment by ujifgc** [comment]
You can use `rake ar:structure:dump` to dump your database schema into SQL file. The resulting file is at `"#{Padrino.root}/db/#{Padrino.env}_structure.sql"`
