### ISSUE TITLE
Rake task not working

### ISSUE THREAD

**Issue by blanchma** [padrino/padrino-framework#1498]
I have the following padrino 0.11.4 project with ActiveRecord as ORM.

https://github.com/blanchma/invisiblefriend

But when I do:
nvisiblefriend:% bundle exec padrino rake -T                                                                              <master>
=> Executing Rake -T ...
rake db:seed          # Load the seed data from db/seeds.rb
rake routes[query]    # Displays a listing of the named routes within a project, optionally only those matched by [query]
rake routes:app[app]  # Displays a listing of the named routes a given app [app]
rake secret           # Generate a secret key
rake test             # Run application test suite

I'm working with ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin11.4.2]

**Comment by treerunz** [comment]
Hey @blanchma  did you find a solution to this?

**Comment by blanchma** [comment]
@treerunz Too many years ago. I can't even remember if I did.
