### ISSUE TITLE
0.11 -> 0.12 change to @params breaks our code/tests

### ISSUE THREAD

**Issue by mattalbright** [padrino/padrino-framework#1699]
We have a bunch of 0.11 Padrino controllers that look like this:
```
controller :asset do
  get :read, map: '/catalogs/:catalog_id/assets/:asset_id' do
    validate_param_ids(:catalog_id, :asset_id) # Make sure they're UUIDs
    find_params = params.slice(:catalog_id, :asset_id)
    @asset = Asset.find(find_params)
    raise ResourceNotFoundError, {asset: "does not exist"} if @asset.nil?
    render ...
  end
end
```
And our RSpec tests look like this:
```
it "returns 404 when asset not found in DB" do
  @catalog_id, @asset_id = Uuid.create, Uuid.create
  Asset.should_receive(:find).with({
    catalog_id: @catalog_id, 
    asset_id: @asset_id,
  }).and_return(nil)
  get "/catalogs/#@catalog_id/assets/#@asset_id"
  last_response.status.should == 404
end
```
I'm attempting to upgrade to Padrino 0.12, and can't figure out any way to make this combination of test and code, which I think looks pretty straightforward, continue to work unchanged.  

Issue #1696 was my first stab at explaining it, but I went off on a tangent there with HashWithIndifferentAccess that doesn't actually help in my case, so I'm creating this issue fresh with all the info.

What 0.12 did was change the routing params to have string keys (instead of symbols), which breaks both the code and the tests.  Here's what I've tried:
- Make params actually be a HashWithIndifferentAccess: this fails because our tests expect symbol keys to be passed, and HWIA has string keys under the covers.
- Call symbolize_keys! on params before entering the controller (in a before block), but that makes url() break with "route mapping for url(:asset_read) could not be found!"

Is there a simple way to make my hundreds of controllers and probably thousands of tests keep working when upgrading from 0.11 to 0.12?  The pattern I'm using seems pretty simple and straightforward: there are symbols in the controller url map, so I use symbol keys to access them from the params hash, and pass those same symbol keys into the model layer.  Was there a valid reason for breaking backward compatibility in this way?

**Comment by ujifgc** [comment]
As of Padrino 0.13.0 params behavior is:

`request.params` is simple Rack String-keyed params Hash, separates Strings from Symbols and has no knowledge of route params, has only query params (GET + POST)

```
GET '/catalogs/1/assets/2?sid=3'
request.params #=> { "sid" => "3" }
```

`params` is Sinatra-flavored String-keyed params Hash, can find values by Symbol with `#[]` and `#values_at`, has route params and query params

```
GET '/catalogs/1/assets/2?sid=3'
params #=> { "catalog_id" => "1", "asset_id" => "2", "sid" => "3" }
```

`request.route_obj.significant_variable_names` is an Array of Symbols, consists of route params names

There is no longer `env['router.params']` value of `http_router`.


I assume the proposed fix for the issue would be making the params hash Symbol-keyed to be consistent with key naming in route declaration:

```
get '/catalogs/:catalog_id/assets/:asset_id' do; end
GET '/catalogs/1/assets/2?sid=3'
params #=> { :catalog_id => "1", :asset_id => "2", "sid" => "3" }
```

What do we do with query params in this case?

**Comment by ujifgc** [comment]
Closing as lacking feedback.
