### ISSUE TITLE
Event streaming never fires the close callback in Padrino apps

### ISSUE THREAD

**Issue by drbawb** [padrino/padrino-framework#1704]
Padrino version(s) tested: 0.12.1, 0.12.2

Given a brand new Padrino project: `padrino g project es-test`
With the following application:

    list = []

    get '/connect', :provides => 'text/event-stream' do
      stream(:keep_open) do |con|
        list << con
        con  << "data: connected. \n\n"

        con.callback do
          logger.warn "conn closed"
          list.delete con
        end

        con.errback do
          logger.warn "con lost"
          list.delete con
        end

      end
    end
             
    get '/broadcast' do
      list.each do |con|
        logger.warn "sending message..."
        con << "data: broadcast rx'd \n\n"
      end
    
      'done'
    end

Started with `thin` using: `bundle exec thin -e development -p 3000`
I never see `conn closed` or `con lost` logged to the console.

Instead the `list = []` keeps growing as more connections are added, and it does not appear to shrink.

This same application works on Sinatra 1.4.5 w/ thin and has no issues closing connections. (A small modification is necessary: use `provides: 'text/event-stream'` instead of `:provides => 'text/event-stream'`)

Apart from the close callbacks never being fired: events seem to work as desired.
Does anyone have insight as to why these callbacks would not be fired?

**Comment by ujifgc** [comment]
Should be fixed after 5367ba52dea849f12003a4e7676f0941fb607374
