### ISSUE TITLE
attack prevented by Rack::Protection::AuthenticityToken,help!

### ISSUE THREAD

**Issue by martin-yang** [padrino/padrino-framework#1724]
Hello,

I generated a Padrino app using the built in generate command and I'm simply attempting to make a POST request to the controller using an angularjs call.

Find some solution but all failure:

1.add set :protect_from_csrf, false in app.rb(error: 405 Method Not Allowed)

2.add authenticity_token=session[:csrf] in POST request(error: attack prevented by Rack::Protection::AuthenticityToken)

I use padrino 0.12.2.
HELP ME.
Thanks.
Martin.

**Comment by kkirsche** [comment]
I ran into a ton of issues with this token and Angular in Padrino For me it came down to having to call $http.post('url/endpoint/', $.params(payload));
