### ISSUE TITLE
set raise_errors in configure :production

### ISSUE THREAD

**Issue by pchaganti** [padrino/padrino-framework#1728]
How does one set :raise_errors to true in :production? Tried to configure it like this in app.rb

``` Ruby
configure :production do
      set :raise_errors, true
    end

```

That did not seem to set the flag. Can anyone point me in the right direction?

thanks!

**Comment by deepak07** [comment]
I am facing issue in setting configure params on different environments. 
The rubydoc says that we can set the config variables as given below. 

```
Padrino.configure :development do |config|
  config.value2 = 'only development'
end
Padrino.configure :development, :production do |config|
  config.value2 = 'both development and production'
end
```
I tried setting the same but resulted in errors.
`NoMethodError: undefined method 'config' for Padrino:Module`

I am running on **0.12.4** version. Is there something that I am doing wrong in this?

**Comment by adam12** [comment]
> I am running on 0.12.4 version. Is there something that I am doing wrong in this?

This was introduced in **0.13.0**. You'll need to upgrade.
