### ISSUE TITLE
Better community communication

### ISSUE THREAD

**Issue by Signum** [padrino/padrino-framework#1769]
You might winkle your nose about this issue because it's non-technical and perhaps not easy to solve. I've been a huge fan of Padrino for a year now and I totally enjoy using it for my web projects. Besides I've posted several articles about Padrino on my web site (workaround.org). But the way that the "community" (Padrino users) is communicating frustrates me a lot.

Many questions are just risen as Github issues (like this one). I don't think that Github is a good idea for discussions. And I have seen no other projects use the issue tracker like that.

Very few questions make it to the Google Groups mailing list. I don't use a GMail account and it has been an adventure for me to even subscribe to the list because Google makes it artificially hard to subscribe for non-Google users. I'm actually subscribed but my last two posts are just gone. Just two posts made it to the list after two days of moderation delay. That's unbearable. If someone  forces me to have a Google email address for that purpose I'd probably not even care for the project at all.

And hardly any questions ever get answered on the IRC channel on Freenode. I myself am joined to the channel and once in a while there a questions coming up but nobody answers. I have essentially given up sending questions myself because all of the 50 channel visitors there seem to be dead. It's like a digital mortuary with just a bot sending out CI messages to zombies who don't read it.

I know that marketing is a hard issue for open-source projects. And I'm hard to convince of a tool or framework but Padrino is so great in my opinion that it deserves to be endorsed and supported properly. And does not only mean frequent patches and updates but helping users get the best of it. If Padrino had been first in the Ruby ecosystem and Rails came next then nobody would seriously use Rails - that's my honest belief. Padrino surely has a smaller community. But then let's help it communicate better, invent things, propose ideas, help each other.

So please let us find a place to support newcomers, discuss ideas, post snippets etc. I'm not sure what the best way is. (I've heard good things of "Discourse".) But a broken Google group and an alienated Github issue tracker is just wrong in my opinion. And I'm starting to become pretty frustrated of these ways of non-communication.

Please don't get this wrong as a plain rant. I'm really willing to help and provide resources if necessary. I just refuse to spend more time fighting against the means of inter-human communication than spending time with the framework I love.

…Christoph

**Comment by Quintasan** [comment]
I just got this idea from #neovim IRC channel which has a dedicated bot to releat the messages between Gitter and IRC. They use [finnp/gitter-irc-bot](https://github.com/finnp/gitter-irc-bot). Perhaps it would be good idea to get something similar.

**Comment by wikimatze** [comment]
@Quintasan I did it and it's working great. At the others, is it okay to create a padrinobot account on github and gitter for it?

**Comment by nesquena** [comment]
Absolutely OK to create whatever Padrino community channels you can! Thanks.

**Comment by ujifgc** [comment]
Closing as discussed enough and non-technical issue.

**Comment by wikimatze** [comment]
That's fine, I think gitter is working fine (nearly a mailing-list replacement).
