### ISSUE TITLE
Ruby 2.2

### ISSUE THREAD

**Issue by namusyaka** [padrino/padrino-framework#1771]
The default URI parser on Ruby2.2 conforms RFC 3986, so we should check the things related to it.
* rack (ref https://github.com/rack/rack/commit/f467f1b8c21127473b9e6277608d06f9e81e101e, but it's not released yet)
* rack-test (ref https://github.com/brynary/rack-test/pull/114, not supported yet)
* Object#respond_to? problem was fixed.

**Comment by ujifgc** [comment]
Seems working. ref 1a3b2644413cdb865c8f93d26e35af135c5d562a
