### ISSUE TITLE
Is there a good solution to distinguish 'padrino start' and 'padrino console'?

### ISSUE THREAD

**Issue by tune** [padrino/padrino-framework#1780]
I'd like to change my program behavior whether server is working or not.
I couldn't find the good way to distinguish `padrino start` and `padrino console` from program.
Is there a good solution?

I've tried to detect by checking 'IRB' or 'Pry' is defined.
But it doesn't work when I use gem which use irb/pry inside like 'better_errors'.

``` ruby
def console?
  Module.const_defined? :IRB or Module.const_defined? :Pry
end
```

**Comment by mdunc** [comment]
I have a thread that polls SQS for messages that I do not want this to run in the Padrino console as incoming messages create database operations that I do not want happening while in the console.  Googling for "detect padrino console" keeps bring up this closed ticket so I figured I'd bring it up here.
