### ISSUE TITLE
tilt 2 support

### ISSUE THREAD

**Issue by dariocravero** [padrino/padrino-framework#1789]
Hi all,

`tilt 2` has been out for a while now and `sinatra` already [has support for it](https://github.com/sinatra/sinatra/commit/e8ea7709534b01b0325903421e7f1ad0d25c0d19) although it hasn't been unlocked because they didn't release `1.4.5`'s successor yet.

Overall the new version (apart from being maintained - notice there were no updates to v1 since 2013) includes code refactors and a new functionality for mappings. I've asked the author about the benefits [here](https://twitter.com/dariocravero/status/522761026119667712).

However, I think we should upgrade soon. Perhaps we should coordinate that with `sinatra`'s release? Thoughts @padrino/core-members?

Thanks,
Darío

**Comment by ujifgc** [comment]
Seems like the last thing holding tilt1 is here: https://github.com/padrino/padrino-framework/blob/b0e3d57aabc5f8b5f8a0fe2ac754c9294d32151e/padrino-helpers/padrino-helpers.gemspec#L27

I will test it soon.

**Comment by tdreyno** [comment]
I (and Middleman) would love this.

**Comment by tdreyno** [comment]
:fireworks:
