### ISSUE TITLE
Liquid engine  not working since padrino 0.12.3

### ISSUE THREAD

**Issue by hadan** [padrino/padrino-framework#1796]
I use liquid for template engine, but using padrino from ver 0.12.3,it won't render using liquid

**Comment by hadan** [comment]
Here the directory structure for my view:
-views
&nbsp;-layouts
&nbsp;&nbsp;-application.liquid
&nbsp;-main
&nbsp;&nbsp;-index.liquid
&nbsp;&nbsp;-foo.liquid

Actually  only file under main directory that is rendered, it's the layouts/application.liquid that does not render since 0.12.3.
In application.liquid there's {{ content}} as placeholder for index.liquid etc.
I wanted to paste my view here as html snippet but it's so clumsy using markdown.

**Comment by ujifgc** [comment]
Please publish your failing project on Github and give a link here.

**Comment by ultrasaurus** [comment]
The liquid engine is working, but it reports that it is not.  Also, upgrading liquid gem will fix a warning.  

Versions I'm working with:
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]

$ gem list padrino

*** LOCAL GEMS ***

padrino (0.12.5)
padrino-admin (0.12.5)
padrino-cache (0.12.5)
padrino-core (0.12.5)
padrino-gen (0.12.5)
padrino-helpers (0.12.5)
padrino-mailer (0.12.5)
padrino-support (0.12.5)
```

I generated a simple app:
```
$ padrino g project testapp -t rspec -s jquery -e liquid -c sass
$ cd testapp
$ bundle
$ padrino start
.../gems/ruby-2.2.2/gems/liquid-2.1.2/lib/liquid/htmltags.rb:44: warning: duplicated key at line 47 ignored: "index0"
WARNING: no supported rendering engine found. To use Padrino::Helpers and 
Padrino::Rendering properly you should include `gem 'erubis'`, `gem 'haml'` 
or `gem 'slim'` in your Gemfile. If you are confident about using 
Padrino::Helpers without Padrino::Rendering, please define constant 
`Padrino::IGNORE_NO_RENDERING_ENGINE = true` before `require 'padrino-helpers'`.
=> Padrino/0.12.5 has taken the stage development at http://127.0.0.1:3000
[2015-06-13 19:36:33] INFO  WEBrick 1.3.1
[2015-06-13 19:36:33] INFO  ruby 2.2.2 (2015-04-13) [x86_64-darwin13]
[2015-06-13 19:36:33] INFO  WEBrick::HTTPServer#start: pid=60312 port=3000
^C[2015-06-13 19:37:13] INFO  going to shutdown ...
[2015-06-13 19:37:13] INFO  WEBrick::HTTPServer#start done.
```

Changed the liquid line in Gemfile to:
```
gem 'liquid', '= 3.0.3'
```
then I did ```bundle update```

This gets rid of the warning from liquid, but padrino is still reporting that there's no rendering engine.  

I add this to app.rb
```
    get '/' do
        render :hello, locals: {'name' => 'Sarah'}
    end
```

and a view called hello.liquid:
```
<h1>Hello {{ name }}</h1>
```

I can go to http://127.0.0.1:3000/ and see "Hello Sarah"

so, it seems that liquid is working, but there is a spurious error.

**Comment by hadan** [comment]
After some trial and error and sinatra documentation perusing.
Turns out I have to add
```ruby
:layout => true
```
in every _render_ calling  in controller.
Now it works for padrino 0.12.5.
How to make  this to affect class-wide instead of per function?

**Comment by ujifgc** [comment]
Does liquid support layouts nowadays or do you use another layout engine?
Also, https://github.com/padrino/padrino-framework/issues/1796#issuecomment-69462965
