### ISSUE TITLE
Update the hash syntax to the new for the admin app

### ISSUE THREAD

**Issue by mrkaspa** [padrino/padrino-framework#1804]
The admin app still uses the old style hash {:key => value}

**Comment by nickcoyne** [comment]
Times have moved on a bit since this issue was originally opened. Would it be possible to switch over to the 1.9 hash syntax now?

**Comment by ujifgc** [comment]
Doubt it. As far as I know hash colon syntax is still misleading and restricted.

**Comment by nickcoyne** [comment]
@ujifgc I don't want to open a can of worms, but in what way is it misleading and restricted?

Like many others, I follow the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide), in particular https://github.com/bbatsov/ruby-style-guide#hash-literals.

**Comment by ujifgc** [comment]
I find it misleading:

```
hash = { key: value } # the colon is after the token, the token looks like a variable name or a string
hash.key # no method error, works in JavaScript
hash['key'] # => nil
hash[:key] # => value, magic of knowing to move the colon

hash = { :key => value } # the key is obviously a symbol
hash[:key] # no magic, the key is exactly the same
```

I find it restrictive because I still have to use rocket syntax when my keys are not symbols (variables or strings).

There is no reason to use two different syntaxes when one of them is obviously more powerful and straightforward than another.

Here is some unpopular ruby style guide: https://github.com/styleguide/ruby/hashes

**Comment by nickcoyne** [comment]
@ujifgc I don't agree on the inference of magic, or see the relevance of JavaScript, but thanks for the clarification.

**Comment by nickcoyne** [comment]
I like the idea you suggested of a switch to enable this, but maintaining completely separate templates sounds like a big overhead. What about a simple helper function to be used in the templates? (assuming that were practical)

**Comment by jjant** [comment]
@ujifgc How is that misleading? Any ruby beginner could understand the difference. This syntax has been used for so long that I find it really weird that you think it's misleading.

**Comment by ujifgc** [comment]
@jjant there are misleading or even mad quirks in programming and in the world that are common, familiar or customary. Learning them as a beginner does not make them inherently neat, it just litters the learning curve. In extreme cases it can create worship.
