### ISSUE TITLE
datetime fields in the form builder

### ISSUE THREAD

**Issue by CrowdHailer** [padrino/padrino-framework#1808]
Is there a datetime_input helper in the form builder? I can't find it in the documentation. I have also tried finding it in the source an think it is absent. If so I guess this is a feature request.

I am looking for something like this
```rb
<% form_for @event, '/events' do |f| %>
  <%= f.datetime_name :start_date %>
<% end %>
```

It would be helpful to have a separate date_input, time_input and datetime_input. It would also be good if providing a datetime for min and max worked. when using text_input with options `type: 'date', min: DateTime.now` the min is not correctly formatted. I am not surprised about this on a text_input but would be on a datetime_input.
This is an example of the code that I think must be common enough to warrant a helper

```rb
<%= f.text_field :start_date, required: true, min: DateTime.now.strftime('%Y-%m-%d'), type: 'date', value: (@school_course.start_datetime.strftime('%Y-%m-%d') if @school_course.start_datetime) %>
```

**Comment by jkoutavas** [comment]
I could really use this. How's the dev going, anything I can try?

**Comment by CrowdHailer** [comment]
Hey I have had to postpone working on this due to a huge influx of work. Mismanagement on my part but still have to fix it. So nothing to show on my part. What I remember thinking would be useful would be to outline more about how people expect it to work. handling Date, Time & DateTime as well as the format on the front end. lots and lots of variables.
