### ISSUE TITLE
Superclass mismatch after app reloads in development

### ISSUE THREAD

**Issue by mindware** [padrino/padrino-framework#1817]
I'm using padrino (0.12.3) on ruby-2.1.2. Everytime I do a minor change that results in an app reload, the page I receive 'TypeError' with "superclass mismatch for class" for my classes. 

The error points to line 95 in "ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/reloader.rb in require"

Any thoughts?

**Comment by ujifgc** [comment]
Closing as ignored by the OP. We can try to improve the Reloader but we need failing examples.

**Comment by mindware** [comment]
Thanks, been a bit busy with other matters. I solve the problem back then. I'll go back and check sometime, if I find the issue, I'll simply reopen with the information requested. If I dont, I'll keep it closed.
