### ISSUE TITLE
Customizing the padrino.logger format in Rake tasks

### ISSUE THREAD

**Issue by Signum** [padrino/padrino-framework#1818]
I'm totally happy with the default access log of the Padrino.logger. But in my Rake tasks I run very complex operations and find them hard to debug. There I would like to customize the output that I get from "logger.debug". The Ruby file and the line number that generated the log entry would really help (I used to do that in Python all the time).

Currently:

    logger.debug 42

Outputs:

    DEBUG -  42

What I would like to get is:

    DEBUG - [tasks/update_db.rb:158] 42

I have tried to understand how Padrino does logging but I'm a bit lost. In Rake tasks the "logger" object is just available but I can't see where it is initialized. Changing the :format_message parameter does not seem to help because by default it just is "%s - - [%s] "%s"" and I can't influence what the individual %s mean. I wouldn't even know where to alter that for Rake tasks.

Any help? Thanks.

**Comment by namusyaka** [comment]
Basically this feature is cool and useful. Btw, I've got a question.
How should be provided the feature? (Maybe optional style is good).
`:find_caller` option, or confirm the number of indicator(%s)?
