### ISSUE TITLE
New website layout 

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-framework#1826]
The discussion by @angelbotto, @dariocravero, @skade, @CrowdHailer and @rendez about the new design on [gitter](https://gitter.im/padrino/padrino-framework) as well as the ticket of #1769 finally gave me the motivation to work on this. The layout under http://padrino.incontentkingdom.com/ is fantastic. 

I said down the last couple mornings and evenings porting Padrino into jekyll with bootstrap 3.3.1 and fontawesome. The result can be found under http://padrinorb.wikimatze.de/ and the code is available under https://github.com/wikimatze/padrinorb-website. I ported most parts of the old page (disqus comments are missing as well as the guide pages) and we need now a decent design, animations graphics, clarifications on the front page to attract more people and contributors.

Any ideas and suggestions are welcome. Since we have now a "working" place, we can see the results in reality and build on the right things. Before Padrino 1.0.0 is out, the website needs to be finished.

There are tons of things to work on, but the basement is set.

Bests,

Matthias.

**Comment by angeloashmore** [comment]
Hello everyone. I'm a Padrino user, but I've never contributed to the project before. Maybe I could help with this?

What do you think of this concept? It is obviously missing quite a bit of elements and content, but it shows the clean style I am going for.

![desktop hd](https://cloud.githubusercontent.com/assets/8601064/5694296/b34e0f92-98f1-11e4-8fdd-feb5a6661251.png)

**Comment by angeloashmore** [comment]
Mobile views and some different layouts.

![screen shot 2015-01-10 at 8 57 24 pm](https://cloud.githubusercontent.com/assets/8601064/5694560/4f7a2d74-990b-11e4-9088-da369bcd20c6.png)

**Comment by Rendez** [comment]
Looks really cool @angeloashmore I am particularly fond of the colour scheme following the new logo. For a starting mockup, I am in. @wikimatze what do you think? Does this fit with every part you've created?

**Comment by wikimatze** [comment]
@angeloashmore I like the design and elements on the front page and as @Rendez mentioned, good, that you follow the new colorscheme. I've just uploaded the latest changes and deployed the changes. In my eyes, I'm pretty done with the layout.

I find the actual startpage a little bit "naked" and welcome @angeloashmore design. Maybe we can discuss the front-page [here](https://github.com/padrino/padrino-new-web/issues/14).

Bests

Matthias

**Comment by wikimatze** [comment]
I did a lot since the last twenty days:
- CSS minifying
- [RSS feed](http://padrinorb.wikimatze.de/feed.xml)
- Disqus integration:
![padrino-disqus](https://cloud.githubusercontent.com/assets/264708/5993568/c04782f8-aa55-11e4-9700-e13a6b89b5d7.png)
- better headlines for guides, features, contribute and team section: 
![padrino-blog-headline](https://cloud.githubusercontent.com/assets/264708/5993572/e6970712-aa55-11e4-886f-f4d309e51781.png) 

here is a variant of it (which I like more): 
![padrino-blog-headline-two](https://cloud.githubusercontent.com/assets/264708/5993602/88d86368-aa56-11e4-9383-ce7dc879b582.png)
- I finished the front-page: 
![padrino-front-page](https://cloud.githubusercontent.com/assets/264708/5993607/bce4130a-aa56-11e4-9812-d8b917b0278f.png)

Looking for more feedback.

**Comment by nesquena** [comment]
This is looking great! One small thing I noticed here: http://padrinorb.wikimatze.de/padrino-0-11-0-released-padrino-lives/ that the screenshots are enormous by default, I wonder if we just need to tweak the content of the blog post or what the right solution is but it looks odd when viewed.

**Comment by wikimatze** [comment]
@nesquena I limit the size already .... and yeah it's big. Which should be the default size for images in your mind.

**Comment by CrowdHailer** [comment]
No comment beyond looking great.

**Comment by nesquena** [comment]
Yeah I the issue is just the native size of those images and not really any issue with the site styles. Looks great overall! I will try to do a full audit this weekend to see what tasks are left. Thanks for everyone's hard work getting this developed!

**Comment by wikimatze** [comment]
@nesquena sounds great, create as many issues as you like.

**Comment by angeloashmore** [comment]
I have been in the process of moving homes, but everything is settled now so I'm back!

Based on the content in @wikimatze's new version and the design I came up with, I created this:
https://github.com/angeloashmore/padrino-web

It is built using Middleman. Could you guys take a look at it?
``` shell
git clone https://github.com/angeloashmore/padrino-web.git
bundle
bundle exec middleman
```

It is responsive, but the navigation/menu is not completed. The following pages were created as demos:
* /contribute
* /faq
* /changes

![screen shot 2015-02-06 at 11 00 20 am](https://cloud.githubusercontent.com/assets/8601064/6087441/7cd9e31a-adef-11e4-998f-861b96b46cbf.png)
![screen shot 2015-02-06 at 11 00 44 am](https://cloud.githubusercontent.com/assets/8601064/6087442/805d8870-adef-11e4-89dd-24f4622d30c2.png)
![screen shot 2015-02-06 at 11 00 55 am](https://cloud.githubusercontent.com/assets/8601064/6087444/835e6c60-adef-11e4-8e27-7b398ded8e41.png)
![screen shot 2015-02-06 at 11 01 05 am](https://cloud.githubusercontent.com/assets/8601064/6087446/85f66d24-adef-11e4-92fe-5e0797c26b9a.png)

**Comment by angeloashmore** [comment]
![screen shot 2015-02-10 at 3 22 13 pm](https://cloud.githubusercontent.com/assets/8601064/6140179/a96d8db8-b138-11e4-853e-8e7aec02f076.png)

**Comment by wikimatze** [comment]
@angeloashmore I like your and mine design, should I create a branch and try to integrate your layout so that we can easier decide which one we take?

**Comment by Rendez** [comment]
@angeloashmore That looks great, we originally designed the logo for a white background. ^^

**Comment by wikimatze** [comment]
Hi there, we have now two versions of the new design, what are we going to do now?

**Comment by nesquena** [comment]
@wikimatze what do you recommend? I like both of them significantly more than our current site.

**Comment by wikimatze** [comment]
@nesquena I can try to convert my things to middleman (would be something to learn about). Still waiting for feedback from other padrino collaborators.

**Comment by nesquena** [comment]
@namusyaka @ujifgc Do you two have any thoughts or feedback around the future of the site? I'd like to coordinate the launch of this with the release of 0.13.0.

**Comment by wikimatze** [comment]
Any news on that topic? I want to work on the new page and get it finally done.

**Comment by wikimatze** [comment]
Glad that it is finally out, I'll close this issue now.
