### ISSUE TITLE
Padrino-cache timeout/retry fallback

### ISSUE THREAD

**Issue by Rendez** [padrino/padrino-framework#1836]
Last night, RedisToGo suffered DDos attacks and our site with Padrino on Heroku wasn't available, because it led to errors 500. We use cache: true in most of the controller actions
How can we get Padrino and Moneta to timeout trying to fetch controller "actions" from cache?
I've realized that memcached offers for example `exception_retry_limit`. For Redis, I am unsure.

**Comment by ujifgc** [comment]
Padrino Cache passes every option to underlying Moneta library: [`Moneta.new(name, options)`](https://github.com/padrino/padrino-framework/blob/5bc24cd71653db4c581df01fe6f6c947a77333bc/padrino-cache/lib/padrino-cache.rb#L120). If Moneta has timeout option you can specify it for your apps `set :cache, Padrino::Cache.new(:MyAdapter, :my_option => 'my_value')`. Wheither moneta supports it or not, you should ask at https://github.com/minad/moneta.

Closing as not Padrino issue.
