### ISSUE TITLE
Proposal Padrino Logo

### ISSUE THREAD

**Issue by Rendez** [padrino/padrino-framework#1844]
Hi, as already discussed in [Gitter](https://gitter.im/padrino/padrino-framework), we are making the next proposal and opening the discussion for the new Padrino logo that would be tagging along with the release of Padrino 2.0 and the new website @wikimatze is preparing:

![Padrino Logo Presentation](https://proudsugar.s3.amazonaws.com/images/uploads/35e431bb5d816384af984c3f633708da.png)

What do you think?

**Comment by wikimatze** [comment]
@daniproud thanks for the images, they are now included on the page.

**Comment by daniproud** [comment]
@wikimatze :) you're welcome

**Comment by wikimatze** [comment]
Can we close this issue? I'm fine with the new logo so far.
