### ISSUE TITLE
Effect of Sinatra's show_exceptions on catch-all exception handling

### ISSUE THREAD

**Issue by emanuil-tolev** [padrino/padrino-framework#1845]
I'm trying to integrate a Padrino 0.12.4 app with raygun.io, an exception handling SaaS. I've gotten it to work in a development environment, but not production.

The setup in ```app.rb```:
```ruby
class App < Padrino::Application
  use ActiveRecord::ConnectionAdapters::ConnectionManagement
  register Padrino::Rendering
  register Padrino::Mailer
  register Padrino::Helpers
  # ... etcetera

  require 'raygun4ruby'
  Raygun.setup do |config|
    config.api_key = "api key"
    config.enable_reporting = true
  end
  use Raygun::Middleware::RackExceptionInterceptor
end
```

The exception to be raised (on hitting /):

```ruby
get :index do
  # .. snip setting some vars
  raise "lala"
  # .. snip some more code
  render :home, layout: "homepage"
end
```

And this is why I think Sinatra's show_exceptions setting is causing the problem - the exception not being passed to Raygun's Rack middleware. The only reason I'm asking here instead of Sinatra's repo is because I'm not using pure Sinatra, so I presume I will be bounced back here to start over :).

```ruby
# WORKING example in development environment, no modification of raise_errors or show_exceptions from their defaults, Padrino 0.12.4
puts settings.raise_errors  # false
puts settings.show_exceptions  # true

# WORKING example in development environment, Padrino 0.12.4
set :raise_errors, true
puts settings.raise_errors  # true
puts settings.show_exceptions  # true

# BROKEN example in development environment - exception not passed to middleware, Padrino 0.12.4
set :show_exceptions, false
puts settings.raise_errors  # false
puts settings.show_exceptions  # false

# BROKEN example in development environment - exception not passed to middleware, Padrino 0.12.4
set :raise_errors, true
set :show_exceptions, false
puts settings.raise_errors  # true
puts settings.show_exceptions  # false
```

I did also read #1666 but putting ```use Raygun::Middleware::RackExceptionInterceptor``` and the setup code first in config.ru (without wrapping it in a padrino application class) doesn't do the trick - the exception is still not passed to the raygun middelware.

Here is an example of the raygun tracking not working in ```RACK_ENV=production``` (because show_exceptions is set to false, I surmise): http://pastebin.com/q0gB0rmg

I think this really shouldn't be this difficult, the problem is probably that I had 0 experience with Rack middleware until I met with this problem. Any advice on getting exceptions handled by the middleware in production is greatly appreciated!

**Comment by ujifgc** [comment]
Closing as looks solved.
