### ISSUE TITLE
Padrino Command Exits Zero on Error

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-framework#1849]
Ran into a problem doing something like this:

```
/tmp/padrino-test >padrino stop && echo 'Success!'
=> tmp/pids/server.pid not found!
Success!
```

As you can see, `padrino s` wasn't running, yet it the command exited with 0.

This is also the case when trying to exec invalid commands:
```
/tmp/padrino-test >padrino whatwhatwhat && echo 'Success!'
Could not find command "whatwhatwhat".
Success!
```
Of course this is (to some extent) [a Thor issue](https://github.com/erikhuda/thor/issues/244). 

The second problem can be easily solved by adding the following to `Padrino::Cli::Launcher`:

```ruby
protected
def exit_on_failure?
  true
end
```

Of course this assumes you don't want to maintain any sort of dependency on the current behavior. 

Fixing the first problem seems a tad ugly and/or invasive:

1. Explicitly call `exit 1` on failure
1. Raise `Thor::Error` on failures like the above and stuff [like this](https://github.com/padrino/padrino-framework/blob/0.12.4/padrino-core/lib/padrino-core/cli/adapter.rb#L16)
1. Just let errors propagate, you'll get non-zero but with a stacktrack -which is not too user friendly

**Comment by ujifgc** [comment]
Thank you for your report! Please tell if there's more commands failing to convey their failure.
