### ISSUE TITLE
Drop outdated components

### ISSUE THREAD

**Issue by namusyaka** [padrino/padrino-framework#1851]
We're going to drop outdated components at the same time with releasing 0.13.0
Please raise the component and discuss.

**Comment by nesquena** [comment]
@padrino/collaborators were there any components we should have dropped that we missed?

**Comment by ujifgc** [comment]
Tests:

https://github.com/thumblemonks/riot
https://github.com/cavalle/steak

Javascript:

https://github.com/rightjs/rightjs-core

**Comment by wikimatze** [comment]
+1 for dropping those components.

**Comment by nesquena** [comment]
Yep agreed we should drop any "inactive" components. The ones @ujifgc mentioned definitely fit that criteria.

**Comment by wikimatze** [comment]
I could do the coding for removing those components.

**Comment by ujifgc** [comment]
Go ahead.

**Comment by wikimatze** [comment]
Okay, you have been faster.
