### ISSUE TITLE
Application Extensions

### ISSUE THREAD

**Issue by hcatlin** [padrino/padrino-framework#1853]
Someone very clever invented the Padrino::Mounter::ApplicationWrapper. It automatically wraps the class of anything mounted in Padrino, so that, theoretically, you can easily mount a non-padrino app, and it will respond in a nice way to all of the methods that Padrino expects to be there with a mounted app.

To do this, it's a SimpleDelegate. That very much solved the problem from the Padrino angle, where we assume no application author would want to spend any time getting Padrino compatibility.

The issue is, as I'm trying to fix up an easy adapter for Grape in Padrino.. and so far it's a nightmare to get everything working together. You can see this in action with all horribly ugly PadrinoEatsGrape makes your simple Grape app file! https://github.com/eivan/PadrinoEatsGrape/blob/master/api/app.rb

That's what we expect people to copy and paste into their app! EWWWWW. Why so much shit? Because, when you use ```SimpleDelegate```, the delegated application can override a single function, but cannot use any of the other predefined functions.

For instance, here's some code in Padrino's ApplicationWrapper:

````
      def dependencies
        @__dependencies ||= Dir["#{root}/**/*.rb"]
      end

      def prerequisite
        @__prerequisite ||= []
      end
````

From what I've read in the code, I have no idea what the actual difference is between prerequisites and dependencies.... But, in this case, I know the Reloader is referencing ```prerequisites``` (plural, but that was another issue), but the files I want reloaded are in dependencies. So, you'd think in my Grape app, I could just do...

````
    def prerequisites
      dependencies
    end
````

But, nope. You can't. You see, this class has no idea about who or what is wrapping it... which is just a reference to this class. I can't call the nice default dependencies method from ApplicationWrapper. To get this to work, I need to copy and paste the already written function. BOO!

Or, I wanted to add another line to the ```setup_application!``` method, but when I do that, I can't call ```super```. I have to copy and paste. 

NOoooooo!!!!

I recommend that we build an ApplicationMethods module, allow that module to get included into the ApplicationWrapper. Then, in my application, if I want to inherit and customize the methods, then I can just include the same set of methods and live my life out in happiness.

Patch following.

**Comment by namusyaka** [comment]
[This](https://github.com/namusyaka/padrino-framework/tree/wrapper-to-extension) is a first implementation for super method.
