### ISSUE TITLE
Grape Support?

### ISSUE THREAD

**Issue by hcatlin** [padrino/padrino-framework#1854]
It seems like Grape and Padrino should get along a lot better than indicated. Would this project be up for "instant" support for dropping in Grape apps. I think it should be pretty straight forward and would actually just require cleaning up some of the Padrino code for mounting apps.

PS: Is there a list anywhere of supported types of apps you can mount that interop easily? I'd happily use a better API wrapper than Grape, if I knew it were magically supported.

**Comment by nesquena** [comment]
@padrino/collaborators @hcatlin I know this a bit old but I'm curious how much work it would take to make grape plug and play with Padrino 0.13.X?

**Comment by ujifgc** [comment]
Plug out Sinatra and plug in Grape? A lot, I think.

**Comment by nesquena** [comment]
Oh I initially read this as plugging existing grape apps into a Padrino project by mounting them.

**Comment by ujifgc** [comment]
Well, look at #1900, it indicates people do that already. It doesn't play well with Reloader but it seems to work. Might as well document it.

**Comment by nesquena** [comment]
Great I was under the impression, this was already working with Padrino now (except reloading). Unless we misunderstood @hcatlin I wonder if we should close this ticket?

**Comment by ujifgc** [comment]
I put together a small guide on how to mount a Grape app onto a Padrino project: https://github.com/padrino/padrino-framework/blob/master/padrino-docs/guides/grape.md

Bear in mind that reloading still does not work with Grape apps.
