### ISSUE TITLE
padrino-console / loader does not add lib/ to $LOAD_PATH

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1861]
I recently attempted to upgrade an app from 0.12.2 to 0.12.4. I noticed that when padrino loaded code from `lib/`, that it didn't add `lib/` to `$LOAD_PATH` before hand. I generated a new app using 0.12.4 and confirmed `lib/` was not being added when running `padrino console`.

**Comment by sshaw** [comment]
This is talked about [here](https://github.com/padrino/padrino-framework/issues/1794). Not sure if [this comment](https://github.com/padrino/padrino-framework/issues/1794#issuecomment-60198613) is the official stance on the matter. Would be good to get that clarified.

**Comment by postmodern** [comment]
Closing as duplicate.

**Comment by sshaw** [comment]
Not sure this is a duplicate, I think my followup about `lib` may have been lost in the mire of the other issues.

@ujifgc does your response [here]() (*"As for `Padrino.load_paths` vs. `$LOAD_PATH`..."*) include the a project's `lib` directory, as outlined by @postmodern above?

**Comment by ujifgc** [comment]
I'm not sure what are you asking. Do you want `padrino g project` to create empty `lib` folder and add `$LOAD_PATH.unshift Padrino.root('lib')` to `config/boot.rb` for you?

**Comment by postmodern** [comment]
@ujifgc I want padrino to add `lib/` to `$LOAD_PATH` if it exists. Creating an empty `lib/` is also nice. This odd behavior is currently blocking me from updating to 0.12.4.

**Comment by postmodern** [comment]
Note that bundler only adds `lib/` to `$LOAD_PATH` if the project contains a `.gemspec` which includes `lib/` in the `gemspec.require_paths`.

**Comment by postmodern** [comment]
As a workaround, I've added the following line to `config/boot.rb`:

    $LOAD_PATH.unshift(File.join(PADRINO_ROOT,'lib'))

**Comment by ujifgc** [comment]
You're talking about adding the detection to Padrino loader, not adding it to `boot.rb` generator, right?

**Comment by postmodern** [comment]
@ujifgc correct. The loader appears to have supported `lib/` at one point?

**Comment by ujifgc** [comment]
True, at `0.12.0` the loader silently shoved random folder names into `$LOAD_PATH` like ["#{root}/lib", "#{root}/models", "#{root}/shared"](https://github.com/padrino/padrino-framework/blob/0.12.2/padrino-core/lib/padrino-core/loader.rb#L205-L211). I need to hear more opinions on this so called problem and maybe find a good practice. I really would like to not pollute `$LOAD_PATH` in an agnostic web framework.

**Comment by ujifgc** [comment]
Closing as a library should not manage $LOAD_PATH.

Padrino already loads all the files from [default_dependency_paths](https://github.com/padrino/padrino-framework/blob/e22cb0f936f34188c273ef9522d479c08c0ba9a6/padrino-core/lib/padrino-core/loader.rb#L192) and it does it without a possibility to break require order set by package manager.

If you have a project complex enough that you have to change [dependency_paths](https://github.com/padrino/padrino-framework/blob/e22cb0f936f34188c273ef9522d479c08c0ba9a6/padrino-core/lib/padrino-core/loader.rb#L182) you should know how require works and you should not expect from a framework to add magic lib folder for you.

**Comment by postmodern** [comment]
@ujifgc what if one of the files contains `require 'some/file/in/lib'`? By requiring all of the files in no particular order, it forces developers not to add `require`s.

**Comment by ujifgc** [comment]
Yes, yes... This is great idea! We should remove default dependency paths altogether.

**Comment by postmodern** [comment]
As a workaround I added:

    $LOAD_PATH.unshift(File.join(Padrino.root,'lib'))
    Padrino.load!
