### ISSUE TITLE
Router#recognize disappeared; no apparent way to provide an env to determine a route

### ISSUE THREAD

**Issue by fj** [padrino/padrino-framework#1862]
As of [this commit](https://github.com/padrino/padrino-framework/commit/2d81e28cbd2b7172294acadcafe371734c8c4ea1#diff-c13c50f5426b23eb4d895160f07b3092L69), `Router#recognize` disappeared. At this point, there doesn't seem to be a way to pass a `Rack::MockRequest.env_for` hash and get a list of matching routes, and the padrino-rspec gem is broken as a result.

This means that tests can't determine whether something is routable (or if they can, then I'm no longer sure what the right way to do it is) by providing only a request env hash. It may be possible if you supply an entire request, but that is somewhat slower and would cause performance hits in tests if there are a lot of routes to check.

Is there a new recommended way to do this? For reference, the previously working RSpec matcher was along these lines:

```ruby
    matcher :be_routable do
      match do |verb_to_path_map|
        begin
          # compile Padrino's routing information
          Padrino.application.call(Rack::MockRequest.env_for("/"))
        end
        path = verb_to_path_map.values.first
        method = verb_to_path_map.keys.first.to_s.upcase
        @routed_to = Padrino.mounted_apps.map(&:app_obj).
          map{|a| a.router.recognize(Rack::MockRequest.env_for(path, :method => method))}.first
        @routed_to.first
      end

      failure_message_for_should_not do |path|
        "expected #{path.inspect} not to be routable, but it routes to #{@routed_to.inspect}"
      end
    end
```

@dariocravero suggested doing a workaround of duck-typing an object that looks like what Padrino wants, so one can do something like this:

```ruby
  class RouterMockRequest
    attr_accessor :path_info, :request_method, :params

    def initialize(path_info: '/', request_method: :get, params: {})
      @params         = params
      @path_info      = path_info
      @request_method = request_method
    end
  end
```

and then one can do

```ruby
    @routed_to = Padrino.mounted_apps.map(&:app_obj).
      map{|a| a.router.engine.find_by_request(RouterMockRequest.new(path_info: path, request_method: method)) {}}.first
```

which will work to get tests passing again. However, this couples all of my routing tests to internal details of Padrino's implementation, which isn't preferable.

**Comment by dariocravero** [comment]
@namusyaka is there any particular reason why `#recognize` was dropped in the first place?

Following the current code in `PathRouter::Compiler`, something like [#find_by_request](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/path_router/compiler.rb#L37-L49) without `yield` should do.

Perhaps those methods can be combined somehow?
Also, `#find_by_request` hints that it only finds a route, not that it runs its code.
Perhaps it should be broken down into two and we can then have something like `#find_by_request` and `#call_by_request`?
On top of that, why are we returning routes when the verbs don't match?

I reckon something like this may do:

```
module Padrino
  module PathRouter
    #
    # High performance engine for finding all routes which are matched with pattern
    #
    class Compiler

      ##
      # Finds routes by using request.
      #
      def find_by_request(request)
        rotation do |offset|
          pattern  = request.path_info.encode(Encoding.default_external)
          if route = match?(offset, pattern)
            route if route.verb == request.request_method.downcase.to_sym
          end
        end
      end

      ##
      # Call routes by using request.
      #
      def call_by_request(request)
        find_by_request(request).each do |route|
          pattern = request.path_info.encode(Encoding.default_external)
          params  = route.params_for(pattern, request.params)
          yield(route, params)
        end
      end
    end
  end
end
```

To make slightly nicer we could then add something that hints whether we route a request or not:

```
module Padrino
  module PathRouter
    #
    # High performance engine for finding all routes which are matched with pattern
    #
    class Compiler
      ##
      # Tells whether the app routes a request or not
      #
      def routes?(request)
        !find_by_request(request).empty?
      end
    end
  end
end
```

Let me know if this suits?

Also, on testing, a mocking object like the one @fj points up there might be a good thing to include in a test helpers perhaps?

I can draft a PR if you're happy with those changes.

@padrino/core-members thoughts?

**Comment by namusyaka** [comment]
Sorry for the inconvenience, and I agree with you basically.
Btw, the mock request should be used smoothly (in fact, we could use it on http_router...), so we should add the support to path_router.
I'm going to make a patch using your suggestion. Thank you for telling me!!
