### ISSUE TITLE
Set I18n.locale=:zh_CN not working

### ISSUE THREAD

**Issue by JuoCode** [padrino/padrino-framework#1865]
I type following code reference from [Padrino localization document](http://www.padrinorb.com/guides/localization):

```
I18n.default_locale = :en

Padrino.before_load do
  I18n.locale = 'zh_cn'
end
```

When i use Chrome, The result of language setting:

> navigator.language
> "zh-CN"
> navigator.languages
> ["en", "zh", "zh-CN"]

When i restart server and refresh page, i can't see any Chinese words; I have been trying to set `I18n.enforce_available_locales` to true/false, it still doesn't work; 

[Another article on Stackoverflow](Another article) says use `padrino-contrib`, the results same of above

**Comment by JuoCode** [comment]
I don't know what reason, because we only support two language environment(en, zh)，so i hard coded in the `before filter`

```
locales = request.env['HTTP_ACCEPT_LANGUAGE'] || 'en'
if locales.start_with? 'zh'
  I18n.locale = 'zh_cn'
else
  I18n.locale = 'en'
end
```

> `request.env['HTTP_ACCEPT_LANGUAGE']` may by nil

**Comment by cookiebody** [comment]
I think you should set **I18n.default_locale** in app's before filter:
```ruby
# in [appname]/app.rb
before do
  # I18n.default_locale = 'zh_cn'
  I18n.default_locale = params[:lang]
end
```

**Comment by JuoCode** [comment]
@cookiebody Yes, it's necessary
Above problem I wrote just want to auto detect browser's or system's language setting to choose a locale between `zh` and `en`

**Comment by JuoCode** [comment]
Because I think this problem

**Comment by JuoCode** [comment]
I guess this issue may be it can't compatible with a variety of Chinese locale string

Like `zh`, `zh_CN`, `zh-CN`

**Comment by ujifgc** [comment]
`zh-CN` is the proper naming. https://tools.ietf.org/html/rfc5646

Locale file should be named like that `zh-CN.yml`.

Adding this locale to available locales should be like this: `I18n.available_locales = ['en', 'zh-CN']` or through listing locales directory and parsing the result.

I18n selecting this locale should be like this: `I18n.locale = 'zh-CN'`.

**Comment by sshaw** [comment]
FWIW under 0.12.6 putting this in boot.rb:

```ruby
Padrino.before_load do
  I18n.locale = :de
end
```

Will only set the locale for the first few requests (using WEBrick). Future requests fallback to using whatever is in `default_locale`. 

This does not seem to be a problem under 0.13.1.
