### ISSUE TITLE
Padrino Routing in regular Sinatra app does not trigger before block

### ISSUE THREAD

**Issue by JeanMertz** [padrino/padrino-framework#1870]
We have a regular Sinatra app in which we are exploring the possibilities of using specific Padrino modules in our application.

However, we are running into an issue in which `helper` are not triggered for inherited classes:

```ruby
class BaseController < Sinatra::Base
  before do
    request.extend(Our::Custom::Request)
  end
end

class MainController < BaseController
  get '/' do
  end
end
```

This works as expected, but as soon as we register `Padrino::Routing`, and convert our `get` to a Padrino-based route, the before block is no longer triggered.

Only if we move the block to our `MainController` namespace, does it trigger again, but this is not ideal for us. Any ideas?

**Comment by ujifgc** [comment]
Looks like we loose filters on class inheritance. Any chance to have published minimal failing project with a locked Gemfile?

**Comment by namusyaka** [comment]
Fixed. Thanks for the report.
Please let us know if you still have the issue.
