### ISSUE TITLE
Sequel migration requiring single model file

### ISSUE THREAD

**Issue by MatzFan** [padrino/padrino-framework#1873]
Re [#1520](https://github.com/padrino/padrino-framework/issues/1520) & [#1795](https://github.com/padrino/padrino-framework/issues/1795) comment:
>Tasks db:migrate and db:seed might not work properly without additional testing with sequel because of http://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-Using+models+in+your+migrations.

`rake sq:migrate` is requiring one of my [project](https://github.com/MatzFan/padfoot) models (agent_alias.rb). Others not required - oddly!
Impact is `rake sq:migrate` builds my User model as a table of columns with blank titles.
Workaround is to `rake sq:migrate:to[n]` sequentially - which currently works.

Can't see this model required in `/lib/**/*` or anywhere else, so maybe a bug?
Any help much appreciated. Sequel + PostgeSQL working well with your excellent framework otherwise.

**Comment by mitchellhenke** [comment]
What does the migration file look like?

**Comment by MatzFan** [comment]
The migration files are [here](https://github.com/MatzFan/padfoot/tree/master/db/migrate) Mitchell.

Bruce

**Comment by mitchellhenke** [comment]
I was able to migrate from a newly created database without any issues.  What error are you getting exactly?

**Comment by MatzFan** [comment]
The problem occurs when I `sq:migrate:down` and then `sq:migrate` at that point the model file is being loaded:
>Macintosh:padfoot me$ padrino rake sq:migrate
=> Executing Rake sq:migrate ...
  DEVEL -   LOADING (0.0109s) /Users/me/dev/padfoot/lib/sass_initializer.rb
  DEVEL -   LOADING (0.0107s) /Users/me/dev/padfoot/lib/scrapers/app_details_scraper.rb
  DEVEL -   LOADING (0.0215s) /Users/me/dev/padfoot/lib/scrapers/app_refs_scraper.rb
  DEVEL -   LOADING (0.0113s) /Users/me/dev/padfoot/app/app.rb
  DEVEL -   LOADING (0.0110s) /Users/me/dev/padfoot/app/models/agent_alias.rb
   INFO -  (0.000240s) SET standard_conforming_strings = ON
   INFO -  (0.000209s) SET client_min_messages = 'WARNING'
   INFO -  (0.000226s) SET DateStyle = 'ISO'
  ERROR -  PG::UndefinedTable: ERROR:  relation "agent_aliases" does not exist

**Comment by mitchellhenke** [comment]
I just went migrated down and then back up without issue.  I get those messages as well, but the migrations do finish running.

**Comment by MatzFan** [comment]
well that's typical; seems an intermittent problem as Users table is ok now - previously had all-blank column titles. Repeated a few times and looks ok. Would still like to know why the one model file is required - which gives the error messages. Closed as functionality not impaired - many thanks for looking at this Mitchell

**Comment by ujifgc** [comment]
I will leave it open and look into the error some time soon.

**Comment by MatzFan** [comment]
ok, thanks

**Comment by ujifgc** [comment]
Finaly got to look at the issue. The problem is this line in your Rakefile: https://github.com/MatzFan/padfoot/blob/17149c799307fdd6cb3205b30f49c249fc1a1d1c/Rakefile#L3

By calling it you load full application environment for all the rake tasks though it's recommended to not load models for your migrations. There's a patch in our code that prevents loading models for sequel migrations, but this code is run after your require hence no effect.

**Comment by MatzFan** [comment]
Aaaggh - of course. Many thanks Igor & sorry you spent time on this, will change it right away.

Cheers

Bruce
