### ISSUE TITLE
padrino-gen controller --app foo bar crashes

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1874]
padrino-gen 0.12.4 crashes with `padrino-gen controller --app foo bar` raises an exception:

<pre>
/home/hal/.gem/ruby/2.0.0/gems/padrino-gen-0.12.4/lib/padrino-gen/generators/controller.rb:66:in `prepend': can't modify frozen String (RuntimeError)
	from /home/hal/.gem/ruby/2.0.0/gems/padrino-gen-0.12.4/lib/padrino-gen/generators/controller.rb:66:in `create_controller'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/hal/.gem/ruby/2.0.0/gems/padrino-gen-0.12.4/lib/padrino-gen/generators/cli.rb:50:in `setup'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/hal/.gem/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/hal/.gem/ruby/2.0.0/gems/padrino-gen-0.12.4/bin/padrino-gen:16:in `<top (required)>'
	from /home/hal/.gem/ruby/2.0.0/bin/padrino-gen:23:in `load'
	from /home/hal/.gem/ruby/2.0.0/bin/padrino-gen:23:in `<main>'
</pre>

**Comment by namusyaka** [comment]
Sorry. It was the critical bug but was already fixed in [this commit](30ed16b61a4cb3ee3a920add63e5ccdb3fe63296).
