### ISSUE TITLE
Active Support dependency warning when using Ruby 2.2.0

### ISSUE THREAD

**Issue by quimrstorres** [padrino/padrino-framework#1876]
I just started a new project with ```padrino-0.12.4``` and ```ruby-2.2.0``` and I am receiving this warning:

```active_support/values/time_zone.rb:270: warning: circular argument reference - now```

I looked into it and the issue is identified [here](https://github.com/rails/rails/issues/18201) (since padrino-support depends on active-support 3.2.*).

Will future releases bump the active support dependency?

**Comment by ujifgc** [comment]
`padrino-support` depends on `activesupport` `>= 3.1`. This should allow you to upgrade to `4.*` without problems. There probably will be no bump in active-support requirement any time soon.

**Comment by quimrstorres** [comment]
Sorry, you're right. I had this problem because I created the app through the project generator with the Mongoid ORM, that also depends on active support. For some reason running bundler installed Mongoid 3.x, that locked active support on the version I mentioned.

**Comment by ujifgc** [comment]
We could lock the generator on the latest mongoid if it's working.

**Comment by quimrstorres** [comment]
Let me bump the mongoid version and I'll get back to you.
