### ISSUE TITLE
padrino-gen plugin for adding honeybadger to a padrino app

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1877]
[Honeybadger](https://www.honeybadger.io/) integration would be nice!

**Comment by postmodern** [comment]
If anyone is interested in adding explicit Padrino support to Honeybadger, here is how they hook into Sinatra: https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/init/sinatra.rb

**Comment by joshuap** [comment]
I maintain the honeybadger gem, and am happy to help however I can. We also detect the framework here:

https://github.com/honeybadger-io/honeybadger-ruby/blob/af4273d1e143d7bef67c7da3608cff37bb6f2005/lib/honeybadger.rb#L219

If we must hook into Padrino differently, I think we can add a check for it before checking for Sinatra (like we do for Rails); the plugin/initialization code for Padrino is what I'm less familiar with. We just need to be able to install two Rack middleware and optionally pick up configuration from Padrino when starting our agent (for example, in Sinatra you can do `set :honeybadger_api_key, 'foo'` and it will use that setting if it's found.) Open to suggestions.

**Comment by KamilMroczek** [comment]
+1

**Comment by postmodern** [comment]
So far I've been copy/pasting this:

### config/honeybadger.rb

    require 'honeybadger'
    HONEYBADGER_CONFIG = Honeybadger::Config.new(env: env)
    Honeybadger.start(HONEYBADGER_CONFIG)

### app/app.rb

    configure :production do
      use Honeybadger::Rack::ErrorNotifier, HONEYBADGER_CONFIG
    end

**Comment by nesquena** [comment]
@postmodern I'd love to see that contributed to here: https://github.com/padrino/padrino-recipes/tree/master/plugins so we can run `padrino-gen plugin honeybadger`. See https://github.com/padrino/padrino-recipes/blob/master/plugins/hoptoad_plugin.rb for a point of reference.

**Comment by postmodern** [comment]
Is there a cleaner, more padrino way, to expose the `HONEYBADGER_CONFIG` object? Setting a global constant seems awkward.

**Comment by sshaw** [comment]
I had a similar issue and setting the constant seemed to be the best option. Though in the case of Honeybadger, it looks like you can just [override `honeybadger_config`](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/init/sinatra.rb#L13-17) and [set `:notices` to `false`](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/init/sinatra.rb#L25) when not in production.

Does that work for your scenario?

**Comment by ujifgc** [comment]
A PR for https://github.com/padrino/padrino-recipes is welcome.
