### ISSUE TITLE
RSpec template for Helpers cannot find the Helper module

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1878]
I noticed that the RSpec template for Helper specs may be broken.

<pre>
require 'spec_helper'

describe "Foo::App::BarsHelper" do
  let(:helpers){ Class.new }
  before { helpers.extend Foo::App::BarsHelper }
  subject { helpers }

  describe "#baz" do
    it "should quix" do
      expect(subject.baz).to be == 'quix'
    end
  end
end
</pre>

When I try to run this spec file, I get `uninitialized constant Foo::App::BarsHelper`.

**Comment by namusyaka** [comment]
Is there [this code](https://github.com/padrino/padrino-framework/blob/master/padrino-gen/lib/padrino-gen/generators/components/tests/rspec.rb#L4) in your spec_helper.rb?

**Comment by postmodern** [comment]
Oops. It is not.
