### ISSUE TITLE
ERROR Padrino::Rendering::TemplateNotFound: Layout 'layouts/error' not found

### ISSUE THREAD

**Issue by krukgit** [padrino/padrino-framework#1880]
When accessing a non-existing url, instead of rendering error 404 page, I receive the Internal Server Error `Layout 'layouts/error' not found in '/Users/me/projects/project/app/views'`. I traced the error back to these two files:

[padrino-contrib/exception_notifier.rb:57](https://github.com/padrino/padrino-contrib/blob/11eb70338082087fc08bb99c2fa2358a8d16e895/lib/padrino-contrib/exception_notifier.rb#L57)

[padrino-helpers/lib/padrino/rendering.rb:310](https://github.com/padrino/padrino-framework/blob/333098adb6a93075337580d7014aff816bdc5e1e/padrino-helpers/lib/padrino/rendering.rb#L310)

`ExceptionNotifier` sets content_type to `text/html`. `Rendering` module doesn't treat this as `simple_content_type` and looks for file names `/errors.en.text/html` and `/errors.text/html`, ignoring existing `/errors`.

**Comment by ujifgc** [comment]
Could you please publish your failing project cut to the minimal required to reproduce the issue?

**Comment by krukgit** [comment]
Please check https://github.com/krukgit/padrino_test/tree/issue_1880

Steps to reproduce:
1. `git clone git@github.com:krukgit/padrino_test.git`
2. `cd padrino_test`
3. `git checkout issue_1880`
4. `bundle install` (note the .ruby-gemset and .ruby-version files)
5. `bundle exec padrino start`
6. Visit http://localhost:3000/test

Expected: 
```
Test 404
```

Actual: 
```
Padrino::Rendering::TemplateNotFound at /test
Layout 'layouts/error' not found
```

**Comment by jf** [comment]
Just chiming in a bit on this: I'm not familiar with the usage of the exception notifier, but I can confirm that this problem is there on the lastest padrino (0.12.5) as well (the example uses 0.12.3), and ruby 2.2.0 (don't think the ruby version is a crucial factor here).

**Comment by ujifgc** [comment]
Padrino rendering expects `content_type` to be a symbol but the documentation says it can be a string with a '/'. We should resolve this.
