### ISSUE TITLE
2 options declared as seleceted when one option's value is same as another option's caption

### ISSUE THREAD

**Issue by tjad** [padrino/padrino-framework#1882]
CODE:

= form_tag '/someurl' do
  = select_tag "My Test Tag", :options=>[["1", 2], ["2", 1]], :selected=>1, :include_blank=>"My Test"

OUTPUT:
![screenshot from 2015-02-17 15 23 00](https://cloud.githubusercontent.com/assets/140786/6228806/fe8c1906-b6b8-11e4-91d3-77da5f59d651.png)

DEPENDENCIES
padrino (0.12.4)
rack (1.6.0)
slim (3.0.2)

**Comment by ujifgc** [comment]
Yes, this behavior is expected. It can be considered bad behavior.

You can fix it locally by monkey patching this method: https://github.com/padrino/padrino-framework/blob/e3a1aafc3769d0782babf2605d6b3e79efec8729/padrino-helpers/lib/padrino-helpers/form_helpers/options.rb#L46-L50

**Comment by ujifgc** [comment]
@padrino/core-members any input please? Do we let it select by value and content and close the issue, or do we select only by value, or do we ignore content if value exists? Do we deprecate or just fix it?

**Comment by nesquena** [comment]
@ujifgc I would say the best move is to ignore content if value exists, else fallback to value. That would resolve this issue. One thing is for sure, if value exists, then only that should be checked to avoid this issue.

**Comment by ujifgc** [comment]
Yes, makes sense.

**Comment by tjad** [comment]
Sorry for my late input, yes, I agree that the caption should be ignored if the value exists. Thanks a lot for the fix.
