### ISSUE TITLE
Use Web Translate It for managing localizations?

### ISSUE THREAD

**Issue by fractious** [padrino/padrino-framework#1883]
To manage the localization process for our apps, we use a service called [Web Translate It](https://webtranslateit.com). It provides a nice web UI for translators to add and update their translations and a very handy cli tool for developers to mange their locale files. We've been using it for a few years now and have been very happy with it.

We're currently internationalizing a padrino app for localisation into Hindi, which I see [isn't yet a supported language in padrino](https://github.com/padrino/padrino-framework/tree/master/padrino-support/lib/padrino-support/locale).

WTI is [free for open source projects](https://webtranslateit.com/en/projects/public/about). Would you consider using WTI for managing localizations of the framework instead of your [current process of having users email localisations to you](http://www.padrinorb.com/guides/localization)? And if so, could I help you with this process?

**Comment by brnrds** [comment]
on this subject, are pull-requests for translation files accepted? email feels a bit weird.

**Comment by dariocravero** [comment]
Hey @fractious, thanks for your suggestion!

I guess the question is: is it a tool we can use to generate the locales and have them exported to static `yml` files as we have it right now? If it is then I guess there shouldn't be any issue in using it to generate locales on demand and add them to the code as needed.
I'd be careful about adding a third-party dependency on something that should be distributed as a simple static file.

**Comment by fractious** [comment]
> I guess the question is: is it a tool we can use to generate the locales and have them exported to static yml files as we have it right now? 

Yes, exactly that. Take a look at the [documentation for the `wti` cli tool](https://github.com/AtelierConvivialite/webtranslateit). Basically only the developer in charge of locales for Padrino need install the `wti` gem. They can then push the master (English) locale files whenever they change, up to WTI, add new languages (either via the cli tool e.g. `wti addlocale fr-CA` or via the web UI) and then once the strings have been translated via the Web UI, simply pull down the newly created locale files for that language `wti pull -l fr-CA`. No other users need to know anything about how the locale files are managed.

> If it is then I guess there shouldn't be any issue in using it to generate locales on demand and add them to the code as needed.

Yup, there's a little bit of one-off setup to configure API keys and specify which locale files to sync with WTI but after that it's a very smooth workflow.

If you want me to fork the repo and get WTI set up for you so you can try it out I'd be happy to. I'll just need your email address to invite you to the WTI project.

**Comment by ujifgc** [comment]
@brnrds yes, of course.

Closing as looks like overkill for Padrino.

Also, I updated localization guide to mention Github PRs.
