### ISSUE TITLE
NoMethodError - private method `public'

### ISSUE THREAD

**Issue by plewis-carecloud** [padrino/padrino-framework#1884]
When trying to include 'padrino-core/application/routing' in my existing Sinatra App...I get the 

```
NoMethodError - private method `public' error.
/vendor/bundle/gems/padrino-core-0.9.21/lib/padrino-core/application/routing.rb:553:in `static_file?'
```

It appears that this is happening because :public setting has now been deprecated and is now using either :public_dir or :public_folder

**Comment by ujifgc** [comment]
Are you sure you are trying the correct version of Padrino `padrino-core-0.9.21`? The stable version is `0.12.4`, you probably should upgrade. To fix your exact issue you could monkey patch this method: https://github.com/padrino/padrino-framework/blob/0.9.21/padrino-core/lib/padrino-core/application/routing.rb#L552-L560

Closing as wont fix.
