### ISSUE TITLE
Consider replacing Access Control with warden, cancan and devise

### ISSUE THREAD

**Issue by FeeJai** [padrino/padrino-framework#1888]
The current Padrino Access Control plugin lacks some important features. It especially does not work across multiple Padrino Apps and misses things like registration. If you are interested in replacing this with some common gems, I'd provide a PR.

**Comment by FeeJai** [comment]
Just noticed that this is somehow similar to #468

**Comment by ujifgc** [comment]
Cancan looks abandoned, devise is for Rails, warden has padrino-warden adapter.

We could use some help with `padrino-admin` though. It would be very nice to be able to choose authentication and authorization solutions on `padrino g admin` phase.

**Comment by ujifgc** [comment]
Closing as considered.
