### ISSUE TITLE
[padrino-gen] generate namespaced models

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1890]
Currently, it doesn't appear to be possible to generate namespaced models (ex: `Foo::Bar` `models/foo/bar.rb`). Would this be possible?

**Comment by akemrir** [comment]
Yes, for me too. But change is not so complicated.

Create main library in models folder for module:
model/foo.rb
``` ruby
module Foo
end
```

Change model to use different table name, namespaced one for example foo_bars.
Update migration and place it in proper place.

for example in sequel you can use this
``` ruby
class Foo::Bar < Sequel::Model(:foo_bars)
end
```

Foo is this module created in main models directory.

In activerecord you can use something like this:
lib/foo_table_prefix.rb
``` ruby
module FooTablePrefix
  extend ActiveSupport::Concern

  included do
    def self.table_name_prefix
      'foo_'
    end
  end
end
```

and then

``` ruby
class Foo::Bar < ActiveRecord::Base
  include FooTablePrefix
end
```

**Comment by ujifgc** [comment]
Closing as too ORM-dependent.
