### ISSUE TITLE
"error 404 do" in app/app.rb doesn't do anything

### ISSUE THREAD

**Issue by jf** [padrino/padrino-framework#1897]
To reproduce:
1. `padrino g project app`
2. Insert the following into `app/app.rb`: `error 404 { render 'doesnt/matter/wont/get/rendered' }`
3. Now trigger a 404 by simply going to localhost:3000. You'll still get the standard Sinatra 404 page

**Comment by ujifgc** [comment]
It's Sinatra's default behavior: https://github.com/sinatra/sinatra/issues/578#issuecomment-14094026
To catch this not_found you could use `not_found { 'error' }` block;

**Comment by jf** [comment]
ok wow, thanks, @ujifgc ! Reading that sinatra thread, it would seem that `set :show_exceptions, :after_handler` would do it as well, but I guess this is where Padrino differs. Thanks for the info. Any thoughts on this issue?

**Comment by ujifgc** [comment]
My thought is that it's confusing.

**Comment by jf** [comment]
Thanks, @ujifgc for your thoughts! Do u see Padrino going away from Sinatra in this aspect? It seems based on https://github.com/sinatra/sinatra/issues/578 that it's not going to change anytime soon in Sinatra...

**Comment by ujifgc** [comment]
No, I don't see Padrino going away from Sinatra documentation too much. However if you see something that works with Sinatra and fails on Padrino you should create an issue.
