### ISSUE TITLE
Reloading not working when Grape API mounted as sub project

### ISSUE THREAD

**Issue by roychoo** [padrino/padrino-framework#1900]
Hi, 
i had tried to mount a grape api project successfully, however i am unable to get the reload working when i change a file in the grape api project.

i tried to find some documentation on this but to no avail.
is this expected or i missed out something?

**Comment by dariocravero** [comment]
How and from where (i.e,. where are the files) are you mounting your grape
api?

**Comment by roychoo** [comment]
you can take a look at https://github.com/dblock/grape-on-padrino my project is very similar

**Comment by ujifgc** [comment]
Confirmed no reloading on two levels: reloader middleware is not called and grape app does not provide reloading routines. I don't think it could be easily fixed from Padrino side.

You could look at this solution https://github.com/AlexYankee/grape-reload, it's based on Padrino Reloader code and as far as I can see, adds reloading routines to grape apps.
