### ISSUE TITLE
How to use #mat outside of Admin?

### ISSUE THREAD

**Issue by leemour** [padrino/padrino-framework#1905]
In my app I'm doing

```ruby
register Padrino::Admin::Helpers::ViewHelpers
```
but it doesn't help. When using `mat` in a view I get:
```undefined method `mat' for #<Lenstroy::App:0x007f09f76a4fc0>```

**Comment by ujifgc** [comment]
You can not `register Padrino::Admin::Helpers::ViewHelpers`, it's just a module, not a Padrino extension. To include module methods to your app you can use `helpers Padrino::Admin::Helpers::ViewHelpers`.
