### ISSUE TITLE
HTML Multi-Select only submits one value

### ISSUE THREAD

**Issue by catswithbenefits** [padrino/padrino-framework#1910]
HTML Multi-Select boxes do not seem to work with `0.12.5`. Only one selected value is readable at the server. Use the following code snippets to reproduce:

*Controller function to show the form*
```
	get :test do
		@dummy = DummyModel.new # irrelevant, needed for form_for to work
		render 'test'
	end
```

*test.haml - the actual form's HTML*
```
%h1
	Test

= form_for @dummy, '/backend/content/test' do |form|

	%select{:class => 'form-control', :name => 'multi', :multiple => 1}
		%optgroup{:label => 'Maingroup'}
			%option{:value => 1}
				Number 1
			%option{:value => 2}
				Number 2
			%option{:value => 3}
				Number 3
	%input{:type => 'submit'}
```

*Controller Post-Handler*
```
	post :test do
		raise params.inspect
	end
```

Now, when selecting multiple values I expect them all to be readable in my post-handler. However only the first value is returned as is obvious with the following output:

```
{"authenticity_token"=>"XXX", "multi"=>"3"}
```

**Comment by ujifgc** [comment]
You should set 'multi[]' as multi-select name for Rack to be able to parse POST query parameter as an Array. Adding '[]' to parameter name for arrays is Rails and Rack convention. An example of explanation can be found here http://codefol.io/posts/How-Does-Rack-Parse-Query-Params-With-parse-nested-query or Googled.

**Comment by catswithbenefits** [comment]
My bad, thanks for clarifying.
