### ISSUE TITLE
Root :index route incorrectly matches single-character URLs

### ISSUE THREAD

**Issue by Freaky** [padrino/padrino-framework#1915]
Create a minimal project with padrino-gen, add a "get :index { }" block to it.

Request /a, and be surprised when it actually matches the route and blows up trying to extract params from it:

    NoMethodError - undefined method `names' for nil:NilClass:
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/matcher.rb:58:in `params_for'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/route.rb:112:in `params_for'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:54:in `block in call_by_request'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:86:in `block in rotation'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:85:in `loop'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:85:in `with_object'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:85:in `rotation'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router/compiler.rb:51:in `call_by_request'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/path_router.rb:43:in `call'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/application/routing.rb:943:in `route!'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/application/routing.rb:926:in `block in dispatch!'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/application/routing.rb:924:in `dispatch!'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
        lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
        lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:225:in `context'
        lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:220:in `call'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/router.rb:84:in `block in call'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/router.rb:75:in `each'
        lib/ruby/gems/2.2.0/gems/padrino-core-0.13.0.beta2/lib/padrino-core/router.rb:75:in `call'
        lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
        lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by Freaky** [comment]
Test case: https://github.com/Freaky/padrino-test-app

**Comment by namusyaka** [comment]
@Freaky Thank you for the thorough explanation. Fixed. 
Please let me know if you still have the issue.

**Comment by Freaky** [comment]
Looks good, thank you :)
