### ISSUE TITLE
SubApps not finding routes

### ISSUE THREAD

**Issue by ianseyer** [padrino/padrino-framework#1917]
I have a three apps loaded under one main app, in a project called SnapStories: `Reports`, `Organization`, and `Auth`. They were created & mounted via the padrino generators.

However, `rake routes` yields nothing: no errors or routes. The only routes that actually get served are those in app/app.rb. Nothing from my controllers in my subapps.

Code here: https://github.com/ianseyer/snapstories-public

**Comment by namusyaka** [comment]
Thanks for the clear explanation. 
I'd like to tell you two points:

1. `rake routes` outputs only named routes, so you must define the named route.
```ruby
# before
get "/" do
end

get "/foo" do
end

# after
get :index do
end

get :foo do
end
```
2.  The order of sub application defined in your apps.rb is incorrect. The main application should be placed in the end.
```ruby
Padrino.mount('SnapStories::Auth', :app_file => Padrino.root('auth/app.rb')).to('/auth')
Padrino.mount('SnapStories::App', :app_file => Padrino.root('app/app.rb')).to('/')
```
See: [Upgrading Padrino from 0.11.X to 0.12.0 Guide](http://www.padrinorb.com/blog/upgrading-padrino-from-0-11-x-to-0-12-0-guide)'s Reorder Mounter Apps section.

**Comment by ianseyer** [comment]
Thank you!
