### ISSUE TITLE
Add Anchor links to sections in the docs

### ISSUE THREAD

**Issue by bryanbraun** [padrino/padrino-framework#1924]
Adding anchor links to the headings in the docs would make it easier to reference specific sections. I think this would be most useful in the guides, but it could possibly be done in the yard-generate API docs also.

I happen to maintain [a tool](http://bryanbraun.github.io/anchorjs/) that helps with that and would be happy to help set it up.

It looks like padrinorb.com may be in transition... which repo would I make the PR to in order for it to be most helpful? https://github.com/padrino/padrino-web? https://github.com/padrino/padrino-new-web?

**Comment by wikimatze** [comment]
Hi @bryanbraun thanks for your idea, this sounds like a good idea. Beside what you've mentioned, there is even a third version https://github.com/angeloashmore/padrino-web. You can find the whole discussion under https://github.com/padrino/padrino-framework/issues/1826. All we need is to find a final solution which page we want to take and then you can include your anchor links

Bests

Matthias

**Comment by ujifgc** [comment]
Closing in favor of https://github.com/padrino/padrino-web/issues/31

**Comment by wikimatze** [comment]
Hi @bryanbraun finally implemented your idea in <https://github.com/padrino/padrino-web/commit/c1204088a53493f90386c0729fb1af07733eea3c> - thanks for the great tool.
