### ISSUE TITLE
Common directory for all plugin init code?

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1926]
I've noticed that `padrino-gen` adds `_init.rb` files for some plugins or libraries (ex: resque, SCSS). I think it would be best if these were grouped in a common directory (ex: `lib/init/`, `lib/plugins/` or `config/init/`).

**Comment by nesquena** [comment]
I agree with this. I tend to put them into a `lib/init` folder in my own projects but there's no reason we can't standardize that.

**Comment by ujifgc** [comment]
Closing in favor of #2032
