### ISSUE TITLE
padrino reports no rendering engine for liquid (but it works)

### ISSUE THREAD

**Issue by ultrasaurus** [padrino/padrino-framework#1928]
I was planning to use liquid on a new project -- it seems to work, but padrino reports no rendering engine found:
```
WARNING: no supported rendering engine found. To use Padrino::Helpers and 
Padrino::Rendering properly you should include `gem 'erubis'`, `gem 'haml'` 
or `gem 'slim'` in your Gemfile. If you are confident about using 
Padrino::Helpers without Padrino::Rendering, please define constant 
`Padrino::IGNORE_NO_RENDERING_ENGINE = true` before `require 'padrino-helpers'`.
```

I updated https://github.com/padrino/padrino-framework/issues/1796, but then figured perhaps I should write a separate issue for the spurious warning

**Comment by ultrasaurus** [comment]
hmm.  I'm using the 0.12.5 version of the gem, and I can see why there's an error.  There is no built-in template for liquid:  https://github.com/padrino/padrino-framework/tree/0.12.5/padrino-helpers/lib/padrino/rendering

will have to look more to understand why .liquid files render and what exactly these templates do if they aren't required for a rendering engine to work

**Comment by nesquena** [comment]
Padrino uses Tilt for rendering so that supports any number of different engines including liquid. The whole rendering engine warning stuff has to do with supporting "safe html" and "view capture" within templates. Liquid should work fine without a rendering engine defined for simple use cases making the warning a bit unnecessary potentially. Thoughts @ujifgc @namusyaka ?

**Comment by namusyaka** [comment]
@nesquena Right. I'm going to dig into the problem in this week.

**Comment by namusyaka** [comment]
@ultrasaurus At first, the problem doesn't occur with 0.13.x.
Do you have reasons not to use that version?
@padrino/core-members Should we backported some commits (including this problem solver) to 0.12 branch?

**Comment by ujifgc** [comment]
I don't see the problem. If the warning message annoys OP she can always define the proper constant. I'm confident that the message is not spurious or useless. As far as I know Liquid is not an adequate rendering engine, as it has no support for yielding from layouts.

**Comment by ultrasaurus** [comment]
confused why liquid is listed as a supported component when it's not an adequate rendering engine.  

![image](https://cloud.githubusercontent.com/assets/41906/8444688/ad1c98b8-1f48-11e5-9b55-ee09e8718dce.png)

Did I miss some part of the doc?

**Comment by ultrasaurus** [comment]
@namusyaka I just did ```gem install padrino``` which provides the latest release version, which appears to be 0.12.5

Open to using 0.13.x, if you all are feeling like it is pretty stable even though it is still beta.  I'm also open to a different rendering engine.  I just picked liquid since my team is using it on another part of the project (different web app) and I thought it would be nice.

**Comment by nesquena** [comment]
This is definitely an issue with the docs being out of date and ambiguous. Thankfully, you should be able to run liquid with 0.12.5 without any issue but ignoring the warning. I'm hoping to release 0.13.0 within next few weeks and with that version warning I think has been fixed entirely. Sorry for any confusion.

**Comment by ujifgc** [comment]
> I'm also open to a different rendering engine

You can use liquid for content and ERB for layout. In 0.12.5 it's Erubis, in 0.13 it can be stdlib ERB. Layout is useful if you have a common header and footer, and distinct content.

**Comment by ujifgc** [comment]
Closing as Padrino no longer reports no rendering engine.
