### ISSUE TITLE
Admin app template needs ConnectionPoolManagement?

### ISSUE THREAD

**Issue by mushishi78** [padrino/padrino-framework#1932]
I'm new to Padrino. I had trouble with a fresh install using the admin template. Following the advise of this thread, [1767](https://github.com/padrino/padrino-framework/issues/1767), I added `use ConnectionPoolManagement` to the top of the admin/app.rb and it sorted it out. Just thought you might want to add it to the template if this is the right thing to do.

**Comment by namusyaka** [comment]
@mushishi78 Thanks for pointing out!
