### ISSUE TITLE
What Happened to field_human_name?

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-framework#1934]
I see that this has been removed between 0.11 and 0.12; no warning, no CHANGES entry, no mention of this [in the upgrade guide](http://www.padrinorb.com/blog/upgrading-padrino-from-0-11-x-to-0-12-0-guide).
 
Is `I18n.t "#{model_name}.attributes.#{field}"` the replacement?

I gotta say, migrating from 0.10 to 0.12 feels like going from a 1.0 to 3.0

**Comment by namusyaka** [comment]
Sorry for the inconvenience. The method was removed at [this commit](https://github.com/padrino/padrino-framework/commit/2e35adaeb28a5c9813b48ddf3cbb776b85a9b6c5), but I guess it shouldn't be removed. I'd like to restore it. 
@padrino/core-members Thoughts?

**Comment by ujifgc** [comment]
Agreed. The removal was not thoughtful as I had confused private and protected APIs.

**Comment by namusyaka** [comment]
@sshaw @ujifgc Thanks for pointing out and confirming!
