### ISSUE TITLE
Logger documentation is incorrect

### ISSUE THREAD

**Issue by gvt** [padrino/padrino-framework#1938]
https://www.padrinorb.com/api/Padrino/Logger.html

The documentation at the URL above shows the incorrect log levels. The code in padrino-core version 0.12.5 has this instead:

```
    Levels = {
      :fatal =>  4,
      :error =>  3,
      :warn  =>  2,
      :info  =>  1,
      :debug =>  0,
      :devel => -1,
    } unless defined?(Levels)
```

**Comment by ujifgc** [comment]
@nesquena who can regenerate https://www.padrinorb.com/api/Padrino/Logger.html ?

**Comment by nesquena** [comment]
@DAddYE can you help regenerating http://www.padrinorb.com/api/index.html. Pretty please :)

**Comment by DAddYE** [comment]
It should be good now! Give it some refresh ;)

**Comment by nesquena** [comment]
@DAddYE sweet! Thanks for taking the time to regenerate the docs!
