### ISSUE TITLE
Padrino return 404 when "provides" is set and 'Accept' header has only '*/*'.

### ISSUE THREAD

**Issue by tunepolo** [padrino/padrino-framework#1943]
I find strange behaviour in padrino.
It seems router bugs.

#### Windows

```bat
% ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]
```

#### Linux

```bash
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
```

### Source Code

```ruby
get :text, provides: :text do
  content_type 'text/plain'
  'hello world'
end

get :image, provides: :jpg do
  content_type :jpg
  filepath =  File.join(Padrino.root, 'files/padrino.jpg')
  File.binread(filepath)
end
```

Whole source code is accesible from [tunepolo/padrino_router_bugs](https://github.com/tunepolo/padrino_router_bugs).

```bash
$ git clone https://github.com/tunepolo/padrino_router_bugs
$ bundle install
$ ruby bin/image_server -h 0.0.0.0
```

### Symptom

Note that '172.23.105.165' is my PC's IP.
The response difference is caused by browser's 'Accept' header.

* Google Chrome : ```text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8```
* Internet Explorer(localhost) : ```text/html, application/xhtml+xml, */*```
* Internet Explorer(IP address) : ```*/*```

[Google Chrome]

| URL | Success |
|-----|---------|
| http://localhost:3000/text | ○ |
| http://localhost:3000/image | ○ |
| http://172.23.105.165:3000/text | ○ |
| http://172.23.105.165:3000/image | ○ |

[Internet Explorer]

| URL | Success |
|-----|---------|
| http://localhost:3000/text | ○ |
| http://localhost:3000/image | ○ |
| http://172.23.105.165:3000/text | × |
| http://172.23.105.165:3000/image | × |

**Comment by ujifgc** [comment]
Confirmed but not with IE 11.0.9600.17905
Had to install Modified Headers Ext to Firefox and send Accept: */* to get 404.

**Comment by tunepolo** [comment]
@ujifgc  Yes, you're right.
The problem happens when the Accept headers has only '*/*'.
So problem always happen when curl is used.

I've updated the issue title to describe the symptom more correctly.
