### ISSUE TITLE
How to use Sidekiq Web with Padrino

### ISSUE THREAD

**Issue by hbrysiewicz** [padrino/padrino-framework#1944]
I've scrounged through old issues and even spoken to the friends over in the Sidekiq gitter chat room (specifically [jc00ke](https://github.com/jc00ke)). I attempted to follow the steps [in this gist](https://gist.github.com/passcod/3754086) which allowed me to get Sidekiq running from within Padrino but I am still unable to get the Web Interface running. I tried mounting within the `apps.rb` and I also tried mapping in the `config.ru` as outlined by the afore mentioned gist. In either case I see the following error:
![image](https://cloud.githubusercontent.com/assets/2779962/8886348/7bf1c8de-321d-11e5-9895-66eb7478e2e6.png)

Any help would be appreciated.

**Comment by cookiebody** [comment]
Mount Sidekiq admin app in `config.ru`:
```ruby
require File.expand_path("../config/boot.rb", __FILE__)
require 'sidekiq/web'

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ["username", "password"]
end
run Rack::URLMap.new(
  "/sidekiq" => Sidekiq::Web,
  "/" => Padrino.application)
```

**Comment by nesquena** [comment]
@hbrysiewicz let us know if that works!

**Comment by basex** [comment]
I created a padrino app and put sidekiq web inside:

```ruby
require 'sidekiq/web'

module App
  class Sidekiq < Sidekiq::Web
    use(Rack::Auth::Basic) do |user, password|
      [user, password] == %w(yourusername yourpassword)
    end

    class << self
      def app_name
        ''
      end

      def dependencies
        []
      end

      def setup_application!; end

      def reload!; end
    end
  end
end
```

then in config/apps.rb you mount the App
```ruby
Padrino.mount('App::Sidekiq').to('/sidekiq')
```

**Comment by pchaganti** [comment]
@cookiebody The recommended way per sidekiq is to mount sidekiq web in your rack app like below. But this gives the same exception. There is an issue posted for this in sidekiq repo too - https://github.com/mperham/sidekiq/issues/2459


```Ruby
require File.expand_path("../config/boot.rb", __FILE__)

require 'sidekiq/web'

Sidekiq::Web.use Rack::Session::Cookie, :secret => ENV['RACK_SESSION_COOKIE']

run Rack::URLMap.new("/" => Padrino.application, "/sidekiq" => Sidekiq::Web)
```

**Comment by ujifgc** [comment]
The recommended way to mount Sidekiq to Padrino application is (`config/apps.rb`)

```
Padrino.mount('Sidekiq', :app_class => 'Sidekiq::Web', :app_root => Sidekiq::Web.root).to('/sidekiq')
```

It worked on `gem 'sidekiq', '3.4.1'`, it fails now on `gem 'sidekiq', '3.4.2'`.

This is definitely a bug in Sidekiq introduced in https://github.com/mperham/sidekiq/commit/cf3c43b2410c4573e05ac119494e41115f4140ad by using Rack Protection before configuration of sessions:

```diff
class Web < Sinatra::Base
     include Sidekiq::Paginator
 
+    use Rack::Protection, :use => :authenticity_token unless ENV['RACK_ENV'] == 'test'
```

A workaround for now could be this code:

```ruby
require 'sidekiq/web'
Sidekiq::Web.use Rack::Session::Cookie, :secret => 'secret'
Sidekiq::Web.instance_eval { @middleware.reverse! } # make session the first middleware to run
Padrino.mount('Sidekiq', :app_class => 'Sidekiq::Web', :app_root => Sidekiq::Web.root).to('/sidekiq')
```

Please be aware that this is not Padrino issue. You should convey this information to Sidekiq team to fix it properly.

**Comment by hbrysiewicz** [comment]
Thanks all for your help. @cookiebody your solution did not work. Using the recommended `Padrino.mount` way described by @ujifgc - my original approach - did work once I moved the order of mounting around. I'm not sure why this is. I also had to specify version of sidekiq to 3.4.1. Here is what my apps.rb looks like working: 
```
require 'sidekiq/web'

Padrino.configure_apps do
  ... set stuff ...
end

class Sidekiq::Web < ::Sinatra::Base
  class << self
    def dependencies; []; end
    def setup_application!; end
    def reload!; end
  end
end

Padrino.mount('Sidekiq', :app_class => 'Sidekiq::Web', :app_root => Sidekiq::Web.root).to('/sidekiq')
Padrino.mount('Something::App', :app_file => Padrino.root('app/app.rb')).to('/')

```

**Comment by hbrysiewicz** [comment]
Everyone, thanks for your help. I've opened up an issue with the Sidekiq team - https://github.com/mperham/sidekiq/issues/2461 who seem to think it isn't an issue within Sidekiq. Do you think someone from the Padrino team could coordinate with the Sidekiq team to solve this? I personally am not familiar enough with the internals of either of the projects or I would be the intermediary.
