### ISSUE TITLE
Order shouldn't matter in terms of mounting sub-apps in Padrino

### ISSUE THREAD

**Issue by treble37** [padrino/padrino-framework#1949]
In [config/apps.rb](https://github.com/treble37/padrino_superhero_todo/blob/master/config/apps.rb), I have this code:

````
# Mounts the core application for this project
Padrino.mount('Api', :app_file => Padrino.root('api/api.rb')).to('/api')
Padrino.mount('PadrinoSuperheroTodo::App', :app_file => Padrino.root('app/app.rb')).to('/')
````
If I swap the order of the lines and put the 'Api' on the bottom, the Api sub-app doesn't seem to load....

**Comment by ujifgc** [comment]
Please look at #796 and #1471 and tell if it solves the problem. Specifically, I asked the same question here https://github.com/padrino/padrino-framework/issues/796#issuecomment-26522900 and there was no arguing. Closing as it's not an issue but feel free to discuss here.
