### ISSUE TITLE
charset is not used when content_type is :json

### ISSUE THREAD

**Issue by tunepolo** [padrino/padrino-framework#1950]
I've found following difference between sinatra and padrino.
Is this a specification?

[Sinatra]

```ruby
require 'sinatra'
 
get '/' do
  content_type :json, charset: 'utf-8'
end
```

→ "Content-type: application/json; charset=utf-8"

[Padrino]

Case1 : Use symbol for charset

```ruby
get '/' do
  content_type :json, charset: 'utf-8'
end
```

→ "Content-type: application/json"

Case2 : Use String for charset

```ruby
get '/' do
  content_type :json, "charset" => 'utf-8'
end
```

→ "Content-type: application/json; charset=utf-8"

**Comment by ujifgc** [comment]
Should be fixed in #1952
