### ISSUE TITLE
Problem with controllers

### ISSUE THREAD

**Issue by basex** [padrino/padrino-framework#1951]
O padrino edge, if I run:

```ruby
get :edit, with: :id do
   p params
end
```

and try to get this controller with ?id=1234&test=1234

Only the key :id is on the params, on the previous padrino versions the :test key would also be part.

**Comment by ujifgc** [comment]
Failed to confirm.

**Comment by basex** [comment]
I send a test/example. Just give me 1 or 2 hours.

**Comment by basex** [comment]
It's related with #1942 

```ruby
    get '/update', with: :id do
      p params[:id]
      p params[:test]
      params.inspect
    end
```

HTTP GET: /update/1234?test=message
Result:
p params[:id] => 1234
p params[:test] => nil
params.inspect => {"test"=>"message", "id"=>"1234"}

**Comment by ujifgc** [comment]
Can't reproduce. Please provide a failing project with Gemfile.lock

```
    get '/edit', with: :id do
      puts params[:id]
      puts params[:test]
      puts params.inspect
    end
```

```
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
rack (1.6.4)
sinatra (1.4.6)
padrino (edge) 

DEBUG -       GET (0.0013s) /edit/1234?test=message - 200 OK
1234
message
{"test"=>"message", "id"=>"1234"}
```

**Comment by basex** [comment]
Re-tested and it's working. Hadn't updated to last edge code.

Sorry ujifgc for making you loose the time :/
