### ISSUE TITLE
When the padrino task mongoid support mongoid 4 ~ 5 version ?

### ISSUE THREAD

**Issue by abbish** [padrino/padrino-framework#1962]
I try to use mongoid 5 in padrino framework, but the rake task raise error
I have checked the padrino task mongoid source code seems like only supported version 2 or 3 for mongoid

When the padrino task mongoid support mongoid 4 ~ 5 version ?

**Comment by abbish** [comment]
The following is error when execute mi:drop
```
~/.rvm/gems/ruby-2.1.3/gems/padrino-gen-0.12.5/lib/padrino-gen/padrino-tasks/mongoid.rb:34:in `mongoid_collections': undefined method `collections' for #<Mongo::Client:0x70131948317420 cluster=127.0.0.1:27017> (NoMethodError)
```

**Comment by ujifgc** [comment]
Someone familiar with new Mongoid API could add it here: https://github.com/padrino/padrino-framework/blob/592fd760619ba86af1c4de5fa0b3f5170c418ab1/padrino-gen/lib/padrino-gen/padrino-tasks/mongoid.rb#L6-L60

Pull requests are appreciated.

**Comment by namusyaka** [comment]
[This patch](https://github.com/mongodb/mongo-ruby-driver/pull/691) might be able to close this issue.

**Comment by namusyaka** [comment]
The [2.1.1](https://github.com/mongodb/mongo-ruby-driver/releases/tag/v2.1.1) has been released.
Closed.
