### ISSUE TITLE
No method `messages' for nil:NilClass

### ISSUE THREAD

**Issue by Seikitsu** [padrino/padrino-framework#1965]
Hello, I have no actual problem except that when you make a typo in your mailer configuration (like extra "{" or something, it apparently doesn't load and you get this "No method `messages' for nil:NilClass" message, which really doesn't tell much. Wouldn't be possible to catch that and make some better error message?

**Comment by ujifgc** [comment]
Please provide your source code and the error stack trace.

**Comment by Seikitsu** [comment]
lets say:
Balikservis::App.mailer :notifications do
  defaults :content_type => 'text/html'
  
  # Klient - potvrzeni o objednani
  email :ordered do |order|
    to      order.address_from.email
    bcc order.address_from.email_bcc if order.address_from.email_bcc
    subject "Zásilka ##{ order.order_number } - objednána"
    provides :plain, :html
    render  'notifications/ordered', :layout => "mail.html", :locals => {:order => order, :subject => "Zásilka ##{ order.order_number } - objednána" }
  end
end

(it has much more emails, but they are pretty much the same, all you need to do to replicate is make a ruby typo, something like ||order|)

NoMethodError: undefined method `messages' for nil:NilClass
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/padrino-mailer-0.11.4/lib/padrino-mailer/helpers.rb:109:in `deliver'
	from (irb):1
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/padrino-core-0.11.4/lib/padrino-core/cli/base.rb:68:in `console'
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
	from /home/beholder/.rvm/gems/ruby-2.2.2/gems/padrino-core-0.11.4/bin/padrino:9:in `<top (required)>'
	from /home/beholder/.rvm/gems/ruby-2.2.2/bin/padrino:23:in `load'
	from /home/beholder/.rvm/gems/ruby-2.2.2/bin/padrino:23:in `<main>'
	from /home/beholder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/beholder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
