### ISSUE TITLE
Please update padrino-mailer's dependency on mail gem

### ISSUE THREAD

**Issue by karloku** [padrino/padrino-framework#1972]
padrino-mailer depends on "mail", "~> 2.5.x" which was released two years ago. This outdated version of "mail" gem makes padrino only supports "mime-type" gem with version "~> 1.16". 
It could be a pain when I tried to use some other gems that requires mime-type with a higher version than 2.0.
Hope padrino team could fix this.

**Comment by ujifgc** [comment]
Fixed in 78e1b4ce. Will be available with Padrino 0.13.1
