### ISSUE TITLE
Routing problems

### ISSUE THREAD

**Issue by akemrir** [padrino/padrino-framework#1982]
I have upgraded my new project to 0.13 and I have routing problems.

It is possible now to pass multiple optional parameters with proper nesting?
In padrino 0.12.5 I could write:

``` ruby
q = { per_page: 2, page: 4 }
url_for(:notes, :index, query: q, beta: 50)
```

which build route to:
``` url
/notes?query[per_page]=2&query[page]=4&beta=50
```

In 0.13 this is not possible anymore, it doesn't build properly:
``` url
/notes?query={:per_page=%3E%222%22,%20:page=%3E%224%22}&beta=50 
```

In new version query parameter is string in controller and it seems to not transform passed hash.
This is a bug? Is there workaround?

**Comment by namusyaka** [comment]
Thanks for the report.
I'm going to fix the problem in a few days.

**Comment by namusyaka** [comment]
This is a mustermann's problem. I'd like to fix. Maybe the patch can be provided in this week.

**Comment by namusyaka** [comment]
Fixed. Please let us know if you still have a problem. Thank you!

**Comment by akemrir** [comment]
@namusyaka This change is in 0.13.1.beta1?
