### ISSUE TITLE
Internal Race/Threading condition and Mounted Apps.

### ISSUE THREAD

**Issue by curtislinden** [padrino/padrino-framework#1984]
I'm noticing behaviour on ruby 2.2.2 and ruby 2.2.3 that leads me to believe there is an issue with mounted apps. I'm the only one on my team that has this issue - I'm new to the team - The only difference we have is that my machine CPU is unique : 3.7 GHz Quad-Core Intel Xeon E5. (MacPro)

Fresh GEMS, fresh Ruby installs from scratch.

The first symptom is that there is a file 'filename.rb' that is required in both 'boot.rb' and in 
'database.rb'. (It's in database.rb so that rake tasks that don't run boot.rb will work)

Only on my machine :
boot.rb => require_relative 'filename'  => true
boot.rb => Padrino.load! => database.rb => require_relative 'filename' => true

Require_relative shouldn't be returning true - that is very strange.

When the app boots - there are none of the mouted app routes.

I switched to Rubinious 2.5.8 which is built with a LLVM 3.5 instead of the stock mac LLVM.

With Rubinious i don't see the require_relative issue - and all my mounted apps are working.

Any thoughts?

**Comment by ujifgc** [comment]
What happens if you do not use `require_relative`?

**Comment by curtislinden** [comment]
if i switch  ```require_relative``` to

```require './config/filename'```

It stops double parsing the file - and the routes still do not work.

I've noticed that the boot process for Sequel is significantly slower on
rubinious, so is starting the server - and then it works..

Are there any deferred or threaded operations in Padrino.mount?



On Tue, Oct 27, 2015 at 2:42 PM, Igor Bochkariov <notifications@github.com>
wrote:

> What happens if you do not use require_relative?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/padrino/padrino-framework/issues/1984#issuecomment-151654122>
> .
>



-- 
Curtis J Schofield | Senior Systems Analyst | U2U
Skype robotarmymade | Second Life Curtis Linden | C 415.632.6001

Linden Lab | Makers of Shared Creative Spaces

**Comment by curtislinden** [comment]
The issue appears in 2.2.0 and 2.2.2 and 2.2.3 and 2.3.0-dev.

The issue doesn't appear in 2.1.5.

**Comment by ujifgc** [comment]
Great. Can you provide a minimal failing project with `Gemfile.lock` so I could test it on my machine?

**Comment by curtislinden** [comment]
I'll see what I can do.


On Wed, Oct 28, 2015 at 2:40 PM, Igor Bochkariov <notifications@github.com>
wrote:

> Great. Can you provide a minimal failing project with Gemfile.lock so I
> could test it on my machine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/padrino/padrino-framework/issues/1984#issuecomment-152002389>
> .
>



-- 
Curtis J Schofield | Senior Systems Analyst | U2U
Skype robotarmymade | Second Life Curtis Linden | C 415.632.6001

Linden Lab | Makers of Shared Creative Spaces

**Comment by ujifgc** [comment]
Closing as missing feedback.
