### ISSUE TITLE
Generator doesn't properly handle "api/posts'

### ISSUE THREAD

**Issue by halfdan** [padrino/padrino-framework#1987]
When running the controller generator: `padrino g controller api/posts` it properly creates files in `app/controllers/api/` and `app/helpers/api/` but the code is invalid.

```
MyApp::App.controllers :api/exercises do

end
```

I'm essentially trying to create a sub-namespace and I'm sure there's another way to do this, but the generator shouldn't really create invalid code.

**Comment by ujifgc** [comment]
Would you like to provide a minimal working human-generated project for us to refer? I'm not sure what are you trying to achieve by namespacing the controller. As I understand Padrino, Api should be an app inside your project.

**Comment by halfdan** [comment]
Hi @ujifgc,
I think I went about this the wrong way. There are two solutions to my problem:

* Have the API in an app mounted as `/api` and then simply add the controllers there
* Have an `ApiExercisesController` that has a simple `map: '/api/exercises`

I'm not sure what the generator should do here as the intention isn't clear - I suppose it could straight out reject to generate anything with a `/` in it.

**Comment by halfdan** [comment]
@ujifgc Nice! Thanks

**Comment by ujifgc** [comment]
You are welcome, thank you for your report.
