### ISSUE TITLE
padrino-gen admin with custom user model produces broken code

### ISSUE THREAD

**Issue by halfdan** [padrino/padrino-framework#1991]
I created an admin app with `-m User`. This resulted in a broken admin interface (in layouts/application.haml):

`%li.navbar-edit-account=link_to tag_icon(:user), url(:users, :edit, :id => current_account.id), :title => pat(:profile), :class => 'navbar-nav-link'`

It also does not change `current_account` to `current_user` as I would expect. It really should be `current_#{account_model}`

**Comment by ujifgc** [comment]
Probably won't be fixed any time soon by core team. Feel free to make a PR.

**Comment by ujifgc** [comment]
Closing as won't fix.
