### ISSUE TITLE
Optional parameters broken in 13.0

### ISSUE THREAD

**Issue by CyberFerret** [padrino/padrino-framework#1992]
I just upgraded one of my projects to 13.0, and it seems that optional parameters on routes are now broken?

For consistency sake, I was using this syntax for optional params:

    get :myroute, :with => '(:optparam)' do
      ... some stuff
    end

But now it appears that calling /myroute results in a 404 error whereas it used to work before.

I tried the 'old' way as below, but that doesn't seem to work in 13.0 either?

    get '/myroute/(:optparam)' do
      ... some stuff
    end

**Comment by CyberFerret** [comment]
Managed to effect a workaround solution by checking for both route possibilities, like so:

    ['myroute', 'myroute/:optparam'].each do |path|
      get path do
        ...stuff
      end
    end

It means I cannot use symbols for the routes any longer, which is disappointing because it breaks the consistency of my code, but at least it works!

**Comment by ujifgc** [comment]
Have you tried the new syntax? With the '?'.

```
get "/foo(/:optional)?" do
end
```

**Comment by CyberFerret** [comment]
I will give that a shot later tonight - thanks!

Any chance there is a way to make it work with the 

    get :foo, :with => ... 

syntax? Purely from a consistency point of view with my code base (which is over 8000 lines of Ruby)

**Comment by ujifgc** [comment]
Yes. It works with `with`:

```ruby
get :myroute, :with => '(:optparam)?' do
  params.inspect
end
```

Closing as resolved.
