### ISSUE TITLE
Problem with Padrino Generator

### ISSUE THREAD

**Issue by basex** [padrino/padrino-framework#1996]
When creating a simple project: `padrino g project padrino_test`

I get:

```
/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- padrino-gen/command (LoadError)
/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/.rvm/gems/ruby-2.2.3/gems/padrino-core-0.13.1.beta1/lib/padrino-core/cli/base.rb:51:in `generate'
```

I'm running ruby 2.2.3 with RVM on OSX with padrino 0.13.1.beta1

This is the same problem as #1993.

**Comment by fighterleslie** [comment]
I ran into the same problem (`cannot load such file -- padrino-gen/command (LoadError)`) today. It seems the `padrino generator` doesn't work when I want to create a new project. 

System info:
 * ruby (2.2.3), installed via rbenv + ruby-build
 * RubyGems (2.5.0) 
 * Padrino (0.13.0)
 * OS: Linux Ubuntu 14.04 LTS (64-bit)

**Comment by ujifgc** [comment]
Do you happen to skip installing `padrino-gen` gem?

If I install only `padrino-core` and try to run `padrino g project test`, I get the same error.

`padrino gen` command requires `padrino-gen` gem to be installed.

**Comment by basex** [comment]
I have padrino-gen gem and all the other padrino gens installed on the same version as padrino and If I do ```padrino --version``` I get ```Padrino v. 0.13.1.beta1```. Everything works without a problem except the generator.

**Comment by fighterleslie** [comment]
@ujifgc I install padrino via RubyGems: `gem install padrino`. After installation, it seems `padrino-gen` is also installed as a part of the `padrino` gem. When I run command `gem list padrino`, the result is below: 

 * padrino (0.13.0) 
 * padrino-admin (0.13.0) 
 * padrino-cache (0.13.0) 
 * padrino-core (0.13.0) 
 * padrino-gen (0.13.0)  
 * padrino-helpers (0.13.0)  
 * padrino-mailer (0.13.0)  
 * padrino-support (0.13.0)

**Comment by basex** [comment]
Looking at #1993, the problem might be related with Ruby 2.2.3 and the way to require files. I tried downgrading padrino to previous versions and got the same problem with the generator.

**Comment by basex** [comment]
I managed today to generate a project ```padrino gen``` doesn't work on my installation, but ```padrino-gen``` command works without any problem.

**Comment by booty** [comment]
I was also successfully able to generate a project by substituting `padrino-gen` for `padrino g`:

    padrino-gen project sample_blog -t shoulda -e haml -c sass -s jquery -d activerecord -b

...but that workaround failed for generating the admin control panel as suggested by the blog tutorial. `padrino g admin` returned the "kernel_require.rb:128:in `require': cannot load such file -- padrino-gen/command (LoadError)" error, while `padrino-gen admin` returned the following: 

     Please specify generator to use (project, app, mailer, controller, helper, model, migration, plugin, component, task)

**Comment by wikimatze** [comment]
My System Linux  3.19.0-39-generic i686 Ubuntu 14.04.3 LTS, so 

```sh
$ padrino-gen project sample_blog -t shoulda -e haml -c sass -s jquery -d activerecord -b
```

is working as well as

```sh
$ padrino g project sample_blog -t shoulda -e haml -c sass -s jquery -d activerecord -b
```

on Padrino 0.13.1 and ruby 2.2.1p85 (rvm 1.26.11).

Bests Matthias

**Comment by ujifgc** [comment]
Confirmed on rubygems 2.5.0. Fixed by running `gem update --system`.
