### ISSUE TITLE
NewRelic agent is broken in 0.13

### ISSUE THREAD

**Issue by kuadrosx** [padrino/padrino-framework#2002]
Hi,
Looks like this support depends on monkey patching ::Padrino::Routing but it is not defined

https://github.com/newrelic/rpm/blob/03ab1989954f0e9d19d81de3ac3b930ed1d4d7be/lib/new_relic/agent/instrumentation/padrino.rb#L12

I will try to fix this, but I am not sure how :(

**Comment by ujifgc** [comment]
Can you show us a Padrino application with not `defined?(::Padrino) && defined?(::Padrino::Routing::InstanceMethods)`?

**Comment by kuadrosx** [comment]
Hi again,
Looks like something in my code makes that the first time 'defined?(::Padrino::Routing::InstanceMethods)' returns nil, I'm re-running NewRelic::Agent.manual_start on Padrino.after_load and this part is fine now.

but the real problem is that new relic is not getting the routes names, it was working perfectly on padrino 0.12.x

On my debugging I found that this code never get executed
https://github.com/newrelic/rpm/blob/14cfb6b60f900f85cfab2dc53e46562bf509e225/lib/new_relic/agent/instrumentation/sinatra/transaction_namer.rb#L14
that is why i thought it was because it wasn't monkey patching 'dispatch!' method, I created a new project to test if the name transactions works there but it doesn't, so any help is appreciated

Thanks for your time

**Comment by skade** [comment]
On the constant thing: where is npm mentioned in you Gemfile? It needs to be below padrino.

**Comment by CyberFerret** [comment]
Having the same issues.  Got Padrino apps in 0.11 and 0.12 working fine with New Relic reporting, but my 0.13 app is not reporting the transaction names (route names) in the New Relic dashboard.

Upgraded my 'newrelic_rpm' to the latest version as per advice from the NR support team, and also moved `gem 'newrelic_rpm'` to below `gem 'padrino'` in my Gemfile, but no change.

Is the new router within 0.13 not compatible with the NR gem?

**Comment by fnordfish** [comment]
I'm investigating that issue as well.

I've boiled it down to this: newrelic_rpm hooks into sinatra's `process_route` and `route_eval` methods to determinate the matched route. It looks like none of both is getting called when using padrino 0.13 with default mustermann router.

My current way of going further would be to additionally hook into padrino's `invoke_route` method.  I'm not quite sure if this is really the way to go, but at least it get's the `route_obj`.

(discussion in the New Relic forum: https://discuss.newrelic.com/t/missing-route-details-in-transaction-log/34989)

**Comment by fnordfish** [comment]
This seems to work for me (with a quite simple app):
https://github.com/fnordfish/rpm/commit/6fbbf2e4fdebcc3c4b6532a3212abb9dcbdcd2dc

**Comment by fnordfish** [comment]
fixed in newrelic_rpm 3.15.2
