### ISSUE TITLE
image_tag not rendering alt

### ISSUE THREAD

**Issue by JoostSaanen** [padrino/padrino-framework#2004]
When I use the image_tag there is no alt text rendered by default (like it is for the image_tag from rails). Is there a way to generate alt-text with this helper?

**Comment by namusyaka** [comment]
Fixed. Also, you can set alt attribute by passing `:alt` option.
Please let us know if you still have a issue.
Thanks!

**Comment by JoostSaanen** [comment]
Awesome. Thanks!
