### ISSUE TITLE
Default fallback routing and mapping

### ISSUE THREAD

**Issue by tayler1** [padrino/padrino-framework#2007]
I don't get your new router.
Also I don't know is it https://github.com/namusyaka/mustermann19 or https://github.com/rkh/mustermann issue, I post it here.

1) Consider this example
```
Sample::App.controllers :products do
  get :index do
    # url(:products, :index) => '/products'
  end

  get :index, :with => :id do
    # url(:products, :index, :id => 5) => '/products?id=5'
    # url broken, but accessing this route '/products/5' from browser works
  end
end
```
I got workaround for handling default routing without params, so...

2) Next example (just rename route to get it work)
```
Sample::App.controllers :products do
  get :index do
    # url(:products, :index) => '/products'
  end

  get :item, :with => :id do
    # url(:products, :item, :id => 5) => '/products/item/5'
  end
end
```
It wasn't exactly what I wanted so...
```
Sample::App.controllers :products do
  get :index do
    # url(:products, :index) => '/products'
  end

  get :item, :map => "/products/:id" do
    # url(:products, :item, :id => 5) => '/products/5'
  end
  # or
  get :item, :parent => :products, :map => ":id" do
    # url(:products, :item, :id => 5) => '/products/5'
  end
end
```
Totally same as your example [enhanced-routing](https://github.com/padrino/padrino-docs/blob/master/guides/05_controllers/02_enhanced-routing.html.md#namespaced-route-aliases)
Why I need explicitly map route to "/products" or to parent? It's already in `:products` controller  

```
get :index, :map => ":id" do
  # url(:products, :index, :id => 5) => '/5'
end
get :index, :map => "/:id" do
  # url(:products, :index, :id => 5) => '/5'
end
```

Isn't mapping `:id` and `/:id` should be different? First relative and second mapped to root.

**Comment by namusyaka** [comment]
@tayler1 Thanks for the report!
This is not mustermann but padrino's issue.

Reported behavior seems working well in padrino-0.12.5, so I decided that the current behavior is a bug, and then I fixed the behavior.
Could you confirm the change on your project?

**Comment by tayler1** [comment]
Yes. It is now as expected. Thank you.
