### ISSUE TITLE
Logout button looks kinda strange

### ISSUE THREAD

**Issue by blindpenguin** [padrino/padrino-framework#2008]
Hi there,

the logout button of the admin page looks a little bit strange. According to the source code, there is an additional "button" element, which is empty. I noticed it while restyling some of the CSS stuff. To make sure if it's my fail or not, i created another project without any changes, and there is the same problem. Looks like there's something wrong.

[Screenshot](http://i.imgur.com/h994ssj.png)

And here the automagically generated code:

`li class='navbar-logout' = button_to(pat(:logout), url(:sessions, :destroy), :method => :delete, :class => 'navbar-nav-form') do
              = content_tag :button, tag_icon(:'power-off'), :type => :submit, :title => pat(:logout), :class => 'navbar-nav-form-link'`

Oh, and btw.: I'm using Google Chrome 48.0.2564.116

**Comment by namusyaka** [comment]
@blindpenguin Thanks for the report! That is a bug, we didn't consider [this change](https://github.com/padrino/padrino-framework/issues/1772).
Now, the problem has been fixed. Please let us know if you still have a problem.

**Comment by blindpenguin** [comment]
Thank you very much. I copied the change into my template. Works just nice. :)
