### ISSUE TITLE
Receiving "Unresolved specs during Gem::Specification.reset" after upgrading to 0.13.1

### ISSUE THREAD

**Issue by CyberFerret** [padrino/padrino-framework#2013]
I've just upgraded a couple of projects to 0.13.1, and overall they seem to work OK, except when I try and launch `padrino s` or `padrino c`, I am getting the following message:

    WARN: Unresolved specs during Gem::Specification.reset:
          json (>= 1.7.7, ~> 1.7)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.

I have tried `gem cleanup json` as well as a full `bundle clean --force` then `bundle install` again, but to no avail.  I've also tried manually removing the `json` gem and reinstalling, but no success.  I have `json 1.8.1` and `json 1.8.3` installed.

Doing a `gem dependency json` shows me this:

    Gem json-1.8.1

    Gem json-1.8.3
      permutation (>= 0, development)
      sdoc (~> 0.3.16, development)

    Gem json_pure-1.8.1
      permutation (>= 0, development)
      rake (~> 0.9.2, development)
      sdoc (~> 0.3.16, development)

    Gem json_pure-1.8.3
      permutation (>= 0, development)
      rake (>= 0, development)

I can't see that there is any conflict?!?  I am getting this same message now on 3 different Padrino projects that I have upgraded.

I checked the `Gemfile.lock` file, and the only line with a hard reference to this version number seems to be ActiveSupport:

    GEM
      remote: https://rubygems.org/
      specs:
        activesupport (4.2.6)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        addressable (2.3.8)
        aws-sdk (2.1.1)
          aws-sdk-resources (= 2.1.1)
    <snip>

NOTE: Starting using `bundle exec padrino c` works fine with no errors.  It only happens when I leave the `bundle exec` part out.

**Comment by wikimatze** [comment]
Hi @CyberFerret I'm getting the same warning when creating sub-apps:

```sh
$ padrino g project my_project
$ cd my_project
$ padrino g app gallery

  WARN: Unresolved specs during Gem::Specification.reset:
        activesupport (>= 3.1)
        sinatra (~> 1.4.6)
        mustermann19 (>= 0)
        thor (~> 0.18)
        rack (>= 0)
  WARN: Clearing out unresolved specs.
  Please report a bug if this causes problems.
        create  gallery
        create  gallery/app.rb
        create  gallery/controllers
        create  gallery/helpers
        create  gallery/views
        create  gallery/views/layouts
        create  public/gallery
        insert  config/apps.rb
```

**Comment by CyberFerret** [comment]
Thanks for the confirmation @wikimatze ! I believe my list of unresolved specs was longer at first, similar to yours, then I ran `bundle clean` and  `gem cleanup` which reduced it down to just the one.

(Caution: Running the cleanup routines above taught me about the hazards of having non version specific gem entries in my `Gemfile`) :)

And likewise, I get the message whenever I run `padrino g` for models, controllers etc.  But it all seems to work OK, so I am assuming it is just a warning message that is OK to ignore for now. :)

**Comment by wikimatze** [comment]
Yeah, I came across `bundle clean` and `gem cleanup` just yesterday. It solved other issues, but I only get the messages when creating a new sub-app.

Anyway, enjoy Padrino!

**Comment by sshaw** [comment]
As for the fix, why is this necessary? To me this seems like it may have just been a conflict between what's in the global gem environment vs what's the Gemfile requires. 

@CyberFerret says:

> OTE: Starting using bundle exec padrino c works fine with no errors. It only happens when I leave the bundle exec part out.

If there's an alternate version of `json` installed globally then this is expected an not a problem. 

`gem cleanup json` leaves the latest version `json` or does nothing if said gem is referenced in multiple `$GEM_PATH` dirs, so `bundle exec` may still be necessary.

**Comment by ujifgc** [comment]
ref: http://bundler.io/man/bundle-exec.1.html#BUNDLE-INSTALL-BINSTUBS

**Comment by sshaw** [comment]
Well, let me ask a different way: what's the benefit of having `$GEM_HOME/bin/padrino` as an "alias" for any binstub?
