### ISSUE TITLE
Inconsistency between #image_tag and #link_to in escaping URIs

### ISSUE THREAD

**Issue by ujifgc** [padrino/padrino-framework#2016]
```irb
/padrino-framework$ bundle console
2.1.0 :001 > include Padrino::Helpers::TagHelpers
2.1.0 :002 > include Padrino::Helpers::AssetTagHelpers
2.1.0 :003 > include Padrino::Helpers::OutputHelpers
2.1.0 :004 > puts(image_tag 'image name.jpeg')
<img src="/images/image%20name.jpeg?1459513767" />
2.1.0 :005 > puts(link_to 'image title', 'image name.jpeg')
<a href="image name.jpeg">image title</a>
```

As you can see, `#image_tag` escapes the space char in image URI while `#link_to` does not.

Per [rfc3986](http://www.ietf.org/rfc/rfc3986.txt) space cannot be a part of proper URI.

Fixing this for `#link_to` will break applications that manually encode URIs to conform with the RFC and W3C standards.

Breaking this for `#image_tag` will not break applications but will introduce non-valid image URIs.

**Comment by ujifgc** [comment]
Hey, @padrino/core-members do you have an opinion on this? I would like to fix it one way or another in 0.14 and have a warning on the behavior change in the next 0.13.

**Comment by nesquena** [comment]
@ujifgc My 2 cents: I think fixing this for link_to is the best option for 0.14 as you said with warnings about this on next release.

**Comment by ujifgc** [comment]
Do you think we can use `SafeBuffer#html_safe` flag to allow crafty users to sneak in manually escaped URIs if they want to? I feel like there's gonna be some apps that fixed this manually.

**Comment by ujifgc** [comment]
I implemented a proper link escaper for modern internet document links based on https://github.com/ruby-rdf/rdf gem: https://github.com/padrino/padrino-framework/blob/link-escaper/padrino-support/lib/padrino-support/utils/link_escaper.rb

The thing is, there is virtually no difference between this and just doing `String#gsub(' ', '%20')` since modern Unicode IRIs are so liberal and cases when you are trying to escape a binary string in a document link are very fringe.

The test examples are here: https://github.com/padrino/padrino-framework/blob/link-escaper/padrino-support/test/test_link_escaper.rb

I'm tending to just scrap this escaper and use simple gsub. It covers 99.9% of common IRI syntax violations (space) and does not invade pre-encoded links.

**Comment by nesquena** [comment]
I tend to agree, better to keep it simpler. @namusyaka any thoughts?

**Comment by namusyaka** [comment]
Great, I would see the feature in Padrino
