### ISSUE TITLE
How to send file as attachment in email

### ISSUE THREAD

**Issue by ssuummit** [padrino/padrino-framework#2017]
Hi,

I was using padrino mailer feature to send email and want to send a result file as attachment in email.

I saw in documentation and used add_file function. But this is sending content of result file in message body instead of sending result file as attachment.

Can anyone please help me how can i send file as attachment?

Thanks!!
Sumit

**Comment by ujifgc** [comment]
Do you happen to use `text_part`? If you do, try to avoid it and use `body` or `html_part`. Ruby mail gem gets confused by it's own methods and creates an email with `multipart/alternative` that marks added content of `text_part` and `add_file` as alternative content.

Ref: #575, https://github.com/mikel/mail/issues/522, https://github.com/mikel/mail/issues/118

**Comment by ssuummit** [comment]
Hi,
Thanks a lot for helping me. With your attached reference thread I got what wrong I was doing. Now its working fine.

Thanks once again!!
Sumit
