### ISSUE TITLE
Official recommendation on how to deal with assets

### ISSUE THREAD

**Issue by plunntic** [padrino/padrino-framework#2020]
Just started playing with Padrino. Everything is cool but it looks like there's really no general concept on how to deal with assets in Padrino (especially those external: bootstrap, font-awesome, etc).

+ there is no official guide for that
+ it looks like there is no actively maintained gem for that
+ there are some discussions on the topic, but most of them recommend gems having last activity few years ago
+ keeping vendor code in own repository is very bad in every way (maybe it's a way to go for small website, but not for a web application really)

I could use some old gem, but none of them worked in Padrino `0.13.1` out of the box. I could use some public cdn, but public cdn's were a good idea few years ago, and not working offline is a big problem for me.

And lastly, i could setup some gulp/grunt pipeline, but i'm developing a SOA application - and Padrino looks like a perfect fit for such micro services, but the thing is that most of services needs some sort of web application, not only an api. For example identity service needs an registration / account management application. Notification service need some administration panel to manage available providers, message channels, templates and so on.

So it's not really possible (or at least practical in any way) to maintain all those gulp/grunt configurations in every repository for every service.

Any way i've decided to create an issue because if you could share your considerations and ideas on the topic it can be useful for others too.

**Comment by skade** [comment]
Hot topic :).

There is previous discussion here:

https://github.com/padrino/padrino-framework/issues/1028

Nowadays, I am erring towards "roll your own", with some self-created sharing of common assets. If you'd like to stick to Ruby, Sprockets is a good option.

The field is just too diverse and there's no good general interfaces to these tools to come up with a framework solution.

(Note that I used to work on Padrino, so this is just an ex-maintainer opinion)

**Comment by plunntic** [comment]
Yes, i've read #1028 and some others too, but having hope that maybe some new ideas arrived in those two years.

So basically self-integrating sprockets, like [that one](http://nesteryuk.info/2015/04/16/sprockets-integration-into-padrino-app.html), is still the best solution (if i want to stay with ruby assets management)?

I'd say that assets management is something that a web framework should take care of. This could be a deal breaker for many people. I think there should be at least some officially maintained gem for integration with sprockets if nothing "better" is possible at the moment.

I'm not sure if i'm already that much into ruby magic to do such a gem by myself but i could at least check it out. Maybe it would be easier to update any existing gem to work with Padrino again.

**Comment by plunntic** [comment]
# Not that bad :)

It turned out to be easy and trouble-less enough to self integrate sprockets pipeline. I used this [guide](http://nesteryuk.info/2015/04/16/sprockets-integration-into-padrino-app.html) to do it, but made some modifications:

+ I've created an assets sub-application and removed all it's content (except of `app.rb` file), this way i have just a top-level `assets` directory - the only difference is that it contains a `app.rb` file, the rest is how you would expect it to be. It will contain directories: images, styles, scripts.

+ Then in the assets application file (`assets/app.rb`), instead of:
```ruby
@sprockets = Sprockets::Environment.new
@sprockets.append_path 'app/assets/javascripts'
@sprockets.append_path 'app/assets/stylesheets'
@sprockets.append_path 'app/assets/fonts'
```

I've put:
```ruby
@sprockets = Sprockets::Environment.new
@sprockets.append_path 'assets/images'
@sprockets.append_path 'assets/styles'
@sprockets.append_path 'assets/scripts'
```

+ **Also just below the `sprockets.append_path`'s section i've put**:

```ruby
if defined?(RailsAssets)
  RailsAssets.load_paths.each do |path|
    @sprockets.append_path path
  end
end
```

This way the integration is compatible with rails-assets.org, and basically you can require bower packages in Gemfile (if you're not familiar with rails assets there is a getting started on their site). Thanks to that i don't have to keep any vendor code in my repository (even if there is no dedicated gem).

+ I've created those directories, vide: `assets/images`, `assets/styles` and `assets/scripts` and also deleted entie `/public` directory - it won't be needed as it should be auto-generated in deployment process.

+ **And in the end i don't use `AssetTagsHelper`'s from the guide**, as they don't work, at least for me, in Padrino `0.13.1`. However default Padrino asset helpers works perfect in that case, at least in local development.

# Rest is exactly the same as in the guide.

Anyway. I have no idea - yet - how it will behave in production / while deploying to production server.

# Summary

This way i have a flat directory structure for assets (just like the original Padrino's public directory):
```
- api /
- > api controllers and other stuff...

- app /
- > application controllers and other stuff...

- assets /
- > app.rb
- > images /
- > styles /
- > scripts /
```

It looks like regular directory, behaves like assets-delivery-sub-application, is easy to maintain and does not depends on whether someone created a dedicated gem or not. I think i'm happy with that.

I'll probably be back with some updates once i figure out how to deploy that thing on a server.

**Comment by viniciusgati** [comment]
Nice!
