### ISSUE TITLE
Date and time field blocks in AbstractFormBuilder

### ISSUE THREAD

**Issue by plunntic** [padrino/padrino-framework#2022]
As of #1898 there are helper methods for date and time fields but it's impossible to use them in block fassion:

```ruby
<% form_for @model, '/path', :method => 'post' do |f| %>
  <%= f.datetime_field_block :created_at %>
<% end %>
```

To me it looks like it would be enough to add appropriate field types in [this array](https://github.com/padrino/padrino-framework/blob/31eb5f5890f74e9487f9204915707f20e3055a5d/padrino-helpers/lib/padrino-helpers/form_builder/abstract_form_builder.rb#L174) and probably some test cases.

I'm interested in getting some more deep knowledge about Padrino, so yeah having fun copy-pasting some stuff could be a good point to start.

Please let me know what do you think.

**Comment by ujifgc** [comment]
Thank you.
