### ISSUE TITLE
set :default_builder inside Padrino.configure_apps doesn't work

### ISSUE THREAD

**Issue by plunntic** [padrino/padrino-framework#2023]
Basically, below code does not work as expected.

```ruby
Padrino.configure_apps do

  # [...]

  set :default_builder, Utils::FormBuilder

end
```

Application is still using default `StandardFormBuilder`. Of course it works when in `app.rb` directly, but all of my apps will be using custom form builder so puting it in `config/apps.rb` seems quite natural.

**Comment by ujifgc** [comment]
Thank you for your report.
