### ISSUE TITLE
Ruby 2.3 frozen string literals in controllers result in a RuntimeError

### ISSUE THREAD

**Issue by fnordfish** [padrino/padrino-framework#2036]
Activating frozen string literals in ruby 2.3 and using String routes result in a RuntimeError.

Sample Code:

```ruby
# frozen_string_literal: true
MyApp.controllers :stuff do
  get "/test" do
  end
end
```

Result:

```
RuntimeError - can't modify frozen String:
/home/vagrant/.gem/ruby/2.3.0/gems/padrino-core-0.13.2/lib/padrino-core/application/routing.rb:627:in `gsub!': can't modify frozen String (RuntimeError)
```

Possible workarounds:

- disable frozen string literals: `# frozen_string_literal: false` (not sure if that is a future-proof solution)
- explicitly "unfreeze" the route string: `get "/test".dup do; end` (looks a bit bulky)

**Comment by ujifgc** [comment]
Thank you for your report.
