### ISSUE TITLE
Mongoid datetime field type wrong

### ISSUE THREAD

**Issue by blindpenguin** [padrino/padrino-framework#2037]
The generator creates the datetime field wrong:

field :thetime, :type => Datetime

It should be DateTime.

**Comment by blindpenguin** [comment]
My browser is weird today.. can't edit the ticket. -.-

Forgot to mention: My installed version is 0.13.2 on Windows.

**Comment by ujifgc** [comment]
`DateTime` constant name corresponds with `date_time` underscored string, not `datetime` string.
