### ISSUE TITLE
When ActiveSupport Tries to Load Missing Constants in Padrino::Application, .parent Conflicts With ActiveSupport's Module.parent 

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-framework#2038]
When a missing constant is encountered inside the `Padrino::Application`, ActiveSupport tries to load it by calling [`Module.parent`](http://api.rubyonrails.org/classes/Module.html#method-i-parent) (amongst other things). This conflicts with [`Padrino::Application.parent`](https://github.com/padrino/padrino-framework/blob/579944b6304917bf8213bcb00d5f228704b6a672/padrino-core/lib/padrino-core/application/routing.rb#L252-L258) and results in [an `ArgumentError`](https://travis-ci.org/sshaw/itunes_store_transporter_web/jobs/130315437#L275): `ArgumentError: wrong number of arguments (given 0, expected 1..2)`.

**Comment by ujifgc** [comment]
Fixed by 0caff744ab8a545bd25615bc354135d39f0d1a88

Ref: #1814

**Comment by sshaw** [comment]
Yeah, that's on the `0.12` branch, but [does not exist in 0.12.6](https://github.com/padrino/padrino-framework/compare/0.12.6...0.13.2#diff-c2f51b1c75eae89ededcaca57ff6e0d2L244).

**Comment by sshaw** [comment]
> Yeah, that's on the 0.12 branch, but does not exist in 0.12.6.

Or in [any 0.12 release](https://github.com/padrino/padrino-framework/compare/0.12...master#diff-c2f51b1c75eae89ededcaca57ff6e0d2L244)

**Comment by ujifgc** [comment]
Pushed 0.12.7 to rubygems.
