### ISSUE TITLE
Document how to mock out helper methods with rack-test

### ISSUE THREAD

**Issue by cburgmer** [padrino/padrino-framework#2048]
I've been trying, searching, and then guessing, on how to mock out helper methods so I can test a controller. To no avail.

I have a helper
```
My::App.helpers do
  def current_user
    session[:uid]
  end
end
```

and a controller

```
My::App.controllers :api do
  get '/authenticate' do
    authenticate unless current_user
  end
end
```

and a test
```
describe 'AuthController' do
  it 'should not authenticate if already authenticated' do
    allow_any_instance_of(My::App).to receive(:current_user).and_return('123xyz')

   get '/api/authenticate'
  end
end
```

Naively I assumed that the `allow_any_instance_of` part via RSpec would be enough. However this code is not triggered.

Alternatively I tried
```
before do
  app(My::App) do
    set :current_user, '123xyz'
  end
end
```
No effect.

What is the preferred way in Padrino to support such behaviour?

**Comment by wikimatze** [comment]
Hi @cburgmer, great that you want to test your helpers. I've written about it under http://wikimatze.de/testing-helpers-in-padrino - please let me know if this helps you.

**Comment by cburgmer** [comment]
Thanks for the link, but in my case I don't want to test the helper, but rather mock the helper so I can test the controller.

In my case I've worked around the particular problem by treating the test case as an end-to-end test, and mocking out the session via rack. 
RackTest is a nice thing, however it is not the right answer to when I want to test my controller via a unit test.

**Comment by wikimatze** [comment]
I did it with a mocking-class, which includes the helper and then mock the helper calls for this helper in the spec. E.g.:


```ruby
describe SessionsHelper do
  before do
    class SessionsHelperKlass
      include SessionsHelper
    end

    @session_helper = SessionsHelperKlass.new
  end

  ...
  describe "#current_user?" do
    it "returns true if current user is logged in" do
      user = User.new
      expect(@session_helper).to receive(:current_user).and_return(user)
      expect(@session_helper.current_user?(user)).to be_truthy
    end

    it "returns false if user is not logged in" do
      user = User.new
      expect(@session_helper).to receive(:current_user).and_return(false)
      expect(@session_helper.current_user?(user)).to be_falsey
    end
  end
  ...
end
```


You then need to find a way to inject this helper in your controller test.

**Comment by ujifgc** [comment]
Closing as https://github.com/padrino/padrino-docs is the better place for documentation requests.
