### ISSUE TITLE
view not updated

### ISSUE THREAD

**Issue by u007** [padrino/padrino-framework#2049]
via padrino 0.13.2,
my view isnt reloaded when i refresh the browser..

what may have caused it?
did i missed anything in configuration?
when i change my controller code, it is working...

**Comment by wikimatze** [comment]
Can you provide more details and a example (look into the issue #2051)

**Comment by u007** [comment]
hi Wikimatze, here are part of my project,
could it be due to slim layout?
https://gist.github.com/u007/60c01a4712296c1e0697967189b670e1

**Comment by u007** [comment]
changed to erb layout, same issue,

**Comment by ujifgc** [comment]
Please try to do `enable :reload` in your app.rb. It does not get enabled because your environment is different from 'development'.

**Comment by u007** [comment]
hi ujifgc, yes i do have it.
controller is refreshing, but view isnt.
my app/app.rb has added the enable :reload , but just curious, i added one more 
but still didnt work

**Comment by u007** [comment]
yes, you guys are right,
my RACK_ENV is not development, therefore:
enable :reload (works with controller)
enable :reload_templates (now it works with template)

can someone add this in the doc? thank you :)

**Comment by wikimatze** [comment]
Hi @u007 feel free to make a pull-requests for the docs under https://github.com/padrino/padrino-docs. If you need help with it, just ping me.

**Comment by u007** [comment]
hi @wikimatze 

how about model?
i did a rename on a has_many :name due to typo for :name,
but it does not seems to reload.
controller changes and views now works with reload...
only model have this issue...

**Comment by u007** [comment]
okay nvm, i think i got it mixed up , it works :)

**Comment by wikimatze** [comment]
Glad, that it worked out for you.
