### ISSUE TITLE
spring?

### ISSUE THREAD

**Issue by u007** [padrino/padrino-framework#2051]
Hi,

will we have spring for padrino?
ive activerecord in my project and it grew quite big,
took 12s to boot on my mac air and 5s on my imac

thank you :)

**Comment by wikimatze** [comment]
You mean the application preloader https://github.com/rails/spring?

**Comment by u007** [comment]
hi wikimatze, yes :)

**Comment by wikimatze** [comment]
Can't say what other @padrino/core-members are thinking about this feature.

**Comment by ujifgc** [comment]
There are currently no plans of creating an application preloader for Padrino. Feel free to write one.
