### ISSUE TITLE
active_record has many inheritance

### ISSUE THREAD

**Issue by u007** [padrino/padrino-framework#2055]
I have a class
```
class User
  has_many :role

end

class Buyer < Buyer

end
```
when i tried to access User.first.role works!
but when i tried to access Buyer.first.role # ActiveRecord::AssociationNotFoundError: Association named 'role' was not found on Buyer

Buyer.first does return a record.

Sorry i do not know if this is specifically my setup issue or padrino
please advice.

thank you :)

**Comment by ujifgc** [comment]
Closing as not a Padrino issue.

**Comment by u007** [comment]
i found the issue,
i need to add in require_relative 'user' inside buyer.rb

@ujifgc is there a automatic way to resolve this type of model inheritance issue in padrino due to the order of models being loaded?
