### ISSUE TITLE
Controllers not properly loaded when using Sidekiq and Padrino::Mailer?

### ISSUE THREAD

**Issue by NickTitle** [padrino/padrino-framework#2059]
We have a sidekiq worker which crunches some data, then builds an email. For some reason, a sidekiq worker inside the mailer cannot resolve routes in my application. If I run the underlying code for the sidekiq worker in console, it works just fine.  
If someone could point me to a missing initialization step or cause, I'd greatly appreciate it. Here goes:

We use a custom url_for which lets me pre-pend the root to the generated url

``` ruby
# at the top of my mailer
def url_for(*names)
  ::JavelinIo::ROOT_URL+::JavelinIo::App.url(*names)
end
```

Our sidekiq initializer just loads `config/boot.rb`, which in turn loads the workers for use in the app in the 'after_load' hook (see below).  

``` ruby
# inside 'config/workers.rb'
require File.expand_path('../boot.rb', __FILE__)
```

Originally sidekiq wouldn't recognize my mailer even with boot loaded, so we explicitly required mailers in the `after_load` hook alongside the workers, like so:  

``` ruby
Padrino.after_load do
  DataMapper.finalize
  DataMapper.logger.level = 3
  Padrino.require_dependencies("#{Padrino.root}/app/mailers/*.rb")

  Dir["app/workers/*"].each do |file|
    puts "found file: #{file}"
    require "./"+file
  end

end
```

Now sidekiq recognizes the mailer but it crashes when trying to generate urls with the following error:

``` ruby
Padrino::Routing::UnrecognizedException: Route mapping for url(:"organization details_for_rule_set") could not be found
```
- i noticed the routes are symbolized into one arg, but I'm not setting that anywhere
- if i hardcode this url, it fails further down on another url in a different controller

Thanks in advance for your help!

**Comment by oranges13** [comment]
I was (and am) having the same issue. I've had to forgo using url() or url_for() in any of my background mailers for this reason.

**Comment by adam12** [comment]
> I was (and am) having the same issue.

Would you be willing to put together a small example app with Padrino+Sidekiq+a simple Mailer configured so we could take a look?

**Comment by sshaw** [comment]
As a workaround, have you tried requiring the mailer from the job class?

**Comment by ujifgc** [comment]
Closing as lacking feedback.
