### ISSUE TITLE
activerecord namespace and concern

### ISSUE THREAD

**Issue by u007** [padrino/padrino-framework#2061]
hi,

how do i ensure models/concern is loaded in padrino?
and models/mynamespace/*.rb is loaded?
how do i specify the loading criteria in padrino configuration?
and how do i configure it to work with rake ar:migrate?

i have this in my rakefile, but my concern is, if i require all ar file, my other non active record tasks will also load all models into the rake task, causing overhead...
is there any better way to do it?
thank you :)

---

```
require 'bundler/setup'
require 'padrino-core/cli/rake'

RACK_ENV = ENV['RACK_ENV']
# puts "out: #{RACK_ENV.inspect}"
PadrinoTasks.use(:database)
PadrinoTasks.use(:activerecord)
PadrinoTasks.init
```

**Comment by namusyaka** [comment]
>how do i ensure models/concern is loaded in padrino?
and models/mynamespace/*.rb is loaded?

Your concerns will be loaded. See [this code](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/loader.rb#L197).

>how do i specify the loading criteria in padrino configuration?
and how do i configure it to work with rake ar:migrate?

Maybe you can use `$LOAD_PATH`  or `Padrino::Application.prerequisites`

>i have this in my rakefile, but my concern is, if i require all ar file, my other non active record tasks will also load all models into the rake task, causing overhead...
is there any better way to do it?
thank you :)

That is a default settings for Padrino project. You can avoid one by removing the line and specifing database task name on your original task.
