### ISSUE TITLE
minor error in documentation for the blog tutorial

### ISSUE THREAD

**Issue by mketiku** [padrino/padrino-framework#2063]
In the blog tutorial [admin-dashboard-setup](http://padrinorb.com/guides/getting-started/blog-tutorial/#admin-dashboard-setup) portion, there is a minor punctuation error.

Currently it looks like this 
```
$ bundle exec rake db:migrate'
$ bundle exec rake db:seed'
```

which does not work and should be the following instead:

``` 
$ bundle exec rake db:migrate
```
and then 
```
$ bundle exec rake db:seed
````

Please note the removed apostrophe and that the commands are separated for readability

**Comment by ujifgc** [comment]
Fixed in https://github.com/padrino/padrino-docs/commit/1c325c547b304302c17e02fb15362930ec03fcb9
