### ISSUE TITLE
Adding pry_byebug to default Gemfile

### ISSUE THREAD

**Issue by Quintasan** [padrino/padrino-framework#2064]
Since padrino/padrino-framework@2a2600a7f9f594aeb3ae8bec3da04ab80d64bbf0 Padrino uses Pry if available. Debugging is a common issue and I think that Pry paired with pry_byebug is the best solution. The only downside that I can see is that it would introduce an external dependency which might be not what we want.

**Comment by ujifgc** [comment]
Probably not gonna happen. Padrino tries to stay lean and as far as I understand the use of pry_byebug is pretty fringe and limited by MRI version. You can always add it to your Gemfile by hand.
