### ISSUE TITLE
auto load models and concerns and module within models/

### ISSUE THREAD

**Issue by u007** [padrino/padrino-framework#2065]
hi,
when i run padrino rake ar:migrate,
if my model include a concern, it fail to find the class.

is there a way to ask padrino to autoload on migration models/concerns and modules inside model/ ?

thank you

**Comment by namusyaka** [comment]
Padrino loads the `concerns` directory directory automatically. See [these lines](https://github.com/padrino/padrino-framework/blob/60e2aaec27ea38cfa120b857734aab0494ed6902/padrino-core/lib/padrino-core/loader.rb#L194-L200)
However, the loading order of dependency files isn't considered.

**Comment by u007** [comment]
i ended with this in my rakefile
```
require 'bundler/setup'
require 'padrino-core/cli/rake'

RACK_ENV = ENV['RACK_ENV']
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
PadrinoTasks.use(:database)
PadrinoTasks.use(:activerecord)

PadrinoTasks.init

if Rake.application.top_level_tasks[0].start_with?('ar:')
  # solve missing concern issue, models already added by padrino
  ActiveSupport::Dependencies.autoload_paths << File.expand_path(File.join(File.dirname(__FILE__), '/models/concerns'))
end
