### ISSUE TITLE
padrino session doesn't return any value on post

### ISSUE THREAD

**Issue by faustoct** [padrino/padrino-framework#2067]
I'm running padrino + phongap. I'm doing a post where I try to retrieve a session value. Session is attached in redis cache

config.ru
```
require 'rack/session/moneta'
uri = URI.parse(ENV["REDISTOGO_URL"])
use Rack::Session::Moneta, key: 'rack.session', store: Moneta.new(:Redis, host: uri.host, port: uri.port, password: uri.password, expires: false)
```

controller.rb
```
get :app do
session[:x]="user"
end
```
```
post :app do
puts session[:x] #returns nothing on phonegap but returns on browser, why? 
end
```

It works with browser but doesn't with phonegap. Any idea?

**Comment by namusyaka** [comment]
Could you provide minimal failing project with Gemfile.lock?

**Comment by ujifgc** [comment]
It does not look like Padrino issue.

**Comment by faustoct** [comment]
Sorry, I lost this thread it looks not happened again. If I get the this issue again I doc it here. btw thanks for the framework worked super well.
