### ISSUE TITLE
Unable to activate calabash-android-0.8.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::LoadError)

### ISSUE THREAD

**Issue by Sheraz83** [padrino/padrino-framework#2070]
Hi I am having above error, please answer me if somebody has best solution, thank you

**Comment by Sheraz83** [comment]
Hi I am having above error, please answer me if somebody has best solution, thank you

**Comment by ujifgc** [comment]
Can not reproduce. Please provide your Gemfile.

**Comment by ujifgc** [comment]
Closing as missing feedback.
