### ISSUE TITLE
Padrino cache

### ISSUE THREAD

**Issue by davinciRor** [padrino/padrino-framework#2075]
BUG

**Current behavior**
If we use cache we lose charset in content-type.

**How reproduce**
1.
```
module Test
  class App < Padrino::Application
    register Padrino::Mailer
    register Padrino::Helpers
    enable :sessions

    register Padrino::Cache
    enable :caching

    get '/api', cache: true do
      content_type :json, charset: 'utf-8'

      expires 15

      "{cache: 'remove_charset'}"
    end
  end
end
```
2. Sent first time

<img width="601" alt="2016-09-08 15 06 57" src="https://cloud.githubusercontent.com/assets/9443548/18348799/328e08f8-75d6-11e6-8d97-9574c95eb7b8.png">

3. Sent second time

<img width="574" alt="2016-09-08 15 07 10" src="https://cloud.githubusercontent.com/assets/9443548/18348812/4970d8c0-75d6-11e6-84ca-0d8f0f46e8cb.png">

** Expected behavior**

When we use cache, doesn`t remove charset from header content type
 
** Versions of Ruby, Padrino, Sinatra, Rack, OS **
ruby (2.3.1)
padrino (0.13.3.2)
sinatra (>= 1.4.6)
rack (1.6.4)
OS X yosemite

**Comment by ujifgc** [comment]
Thank you for your report.
