### ISSUE TITLE
Feature Request/Question: Security measures

### ISSUE THREAD

**Issue by Immortalin** [padrino/padrino-framework#2079]
Frameworks such as hanami now include up to date security practices such as CSP and X frame headers etc. by default, are there any plans to do so too for padrino?

**Comment by pchaganti** [comment]
👍

**Comment by ujifgc** [comment]
Do we need a special treatment from Padrino to set HTTP headers?

**Comment by skade** [comment]
Padrino, being based on Sinatra, automatically includes rack-protection, which provides CSP and X-Frame headers by default.

https://github.com/sinatra/sinatra/tree/master/rack-protection
