### ISSUE TITLE
rake db:create or sq:create fails with mysql driver

### ISSUE THREAD

**Issue by CyberFerret** [padrino/padrino-framework#2084]
Just upgraded to Padrino 0.13.3.2 and am creating a new project using Sequel ORM linked to a local MySQL 5.6 database.  However am having trouble creating the initial data set with `rake db:create` or `rake sq:create`.  Output is as follows:

`bundle exec rake db:create`

```
WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add
'./lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly
if you depend on this behavior.
=> Creating database 'myproject_development'
rake aborted!
Errno::ENOENT: No such file or directory - mysql
/Users/devan/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3.2/lib/padrino-gen/padrino-tasks/sql-helpers.rb:30:in `spawn'
/Users/devan/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3.2/lib/padrino-gen/padrino-tasks/sql-helpers.rb:30:in `create_db'
/Users/devan/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.13.3.2/lib/padrino-gen/padrino-tasks/sequel.rb:52:in `block (2 levels) in <top (required)>'
/Users/devan/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/devan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/devan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create => sq:create
(See full trace by running task with --trace)
```

Strangely enough, `rake db:migrate` works fine and creates the tables as needed.  Just the create scripts that throw this error.

FYI - empty database has already been created on the MySQL server, and credentials check out ok (see above - *sq:migrate* works fine).

**Comment by CyberFerret** [comment]
Just for reference, here is the output for *db:migrate*:

`bundle exec rake db:migrate`

```
WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add
'./lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly
if you depend on this behavior.
   INFO -  (0.000084s) SET @@wait_timeout = 2147483
   INFO -  (0.000080s) SET SQL_AUTO_IS_NULL=0
   INFO -  (0.017849s) CREATE TABLE IF NOT EXISTS `schema_info` (`version` integer NOT NULL DEFAULT 0)
   INFO -  (0.000315s) SELECT * FROM `schema_info` LIMIT 1
   INFO -  (0.000078s) SELECT 1 AS `one` FROM `schema_info` LIMIT 1
   INFO -  (0.000295s) INSERT INTO `schema_info` (`version`) VALUES (0)
   INFO -  (0.000142s) SELECT count(*) AS `count` FROM `schema_info` LIMIT 1
   INFO -  (0.000097s) SELECT `version` FROM `schema_info` LIMIT 1
   INFO -  Begin applying migration version 1, direction: up
   INFO -  (0.012431s) CREATE TABLE `accounts` (`id` integer PRIMARY KEY AUTO_INCREMENT, `name` varchar(255), `surname` varchar(255), `email` varchar(255), `crypted_password` varchar(255), `role` varchar(255))
   INFO -  (0.000237s) UPDATE `schema_info` SET `version` = 1
   INFO -  Finished applying migration version 1, direction: up, took 0.013130 seconds
<= sq:migrate:up executed
```

**Comment by ujifgc** [comment]
The error message states clearly enough that `mysql` executable is unavailable in your app environment. Sequel toolkit does not support creating databases, hence Padrino has to do it with external executable `mysql` for MySQL and `createdb` for Postgres.

@padrino/core-members should be running `db:create` with an already existing database considered error or success? If this task is a part of another task, should the sequential tasks be run or aborted?

**Comment by CyberFerret** [comment]
Thanks for the clarification - I didn't realise that Padrino made a call to the mysql executable for those tasks.  I had several issues compiling the mysql and mysql2 gems on my new iMac, and was wondering if it was perhaps a gem problem, but looks like it is a simple path issue.

Am I correct in assuming then that the only different between **db:create** and **db:migrate** is that db:create creates the actual database, then chains to db:migrate to create the tables according to the migration scripts?

**Comment by ujifgc** [comment]
`db:create` just creates the database. It does not chain to anywhere. https://github.com/padrino/padrino-framework/blob/40a8a6ca3a909c18cc8e121581a816b6b96005b1/padrino-gen/lib/padrino-gen/padrino-tasks/sequel.rb#L39-L55
