### ISSUE TITLE
admin generator --them flag error

### ISSUE THREAD

**Issue by senei** [padrino/padrino-framework#2087]
Padrino v.edge _admin generator_ 
not recognise  **--them flag** 
result of this generator is the same as without this flag 

I em using them like this : 
`padrino g project test -e haml -d mongomapper -t rspec`
`padrino g admin --theme orange`

**Comment by ujifgc** [comment]
wat?

**Comment by adam12** [comment]
Looks like theme support was removed a long time ago.

I've opened a PR here to remove it from the website docs: https://github.com/padrino/padrino-docs/pull/118
