### ISSUE TITLE
session got blank between requests

### ISSUE THREAD

**Issue by faustoct** [padrino/padrino-framework#2091]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
It happens only in iPhone6 (maybe 7). 

controller

      get :xxx do
       puts session
        puts session.id # =====> ALWAYS BLANK
        puts session[:a] # =====> ALWAYS BLANK
        puts "xxx"
        session[:a]=1
        puts session[:a]
        redirect '/'
      end

config.ru

    require 'rack/session/moneta'
    uri = ...
    use Rack::Session::Moneta,
      key:            'rack.session',
      domain:         '4linked.com',
      path:           '/',
      expire_after:   false, # one week
      secret:         'my-secret',
      store:          Moneta.new(:Redis, {
        url:            url,
        expires:        false,
        threadsafe:     true
      })

It works in any mobile and desktop.

#### What is the expected behavior?
be able to retrieve stored data from the session on iphone6 and higher.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
Padrino v. 0.13.3
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
rack (1.6.4)

**Comment by adam12** [comment]
You need to comment out the call to `enable :sessions` inside your `app.rb` file if you want to use another session store.

I'm surprised you saw it working on mobile/desktop outside of iPhone, since what I was able to reproduce was the two session stores conflicted, providing different session ids each time.

See the session reference for more information: http://padrinorb.com/guides/controllers/sessions/

**Comment by faustoct** [comment]
I had tried it before `enable :sessions`

it looks like create a new session every request
request 1:

    #<Rack::Session::Abstract::SessionHash:0x007f9ac8b37850>
    63c91d1c938a377f49595efc3f74b26068e59e8c64acf916a4791b8703dd925d

    xxx
    1

request2

    #<Rack::Session::Abstract::SessionHash:0x007f9ac8b4e578>
    411f22b7df127204d02023f64eaa281d7c89e00246fe5755340a26eb890c00b3

    xxx
    1

**Comment by adam12** [comment]
I put a copy of my test up on Github here: https://github.com/adam12/padrino_2091

See if you can reproduce. Here's how.

With `enable :sessions` (run with `SESSIONS=true padrino s`)
```
session: #<Rack::Session::Abstract::SessionHash:0x007f86648c8560>
session.id: c2d02420590309b7b1dc983d2aadeebc0a31ae4d243739f3d1b24b703410953d
session[:a]:
  DEBUG -       GET (0.0136s) / - 200 OK
session: #<Rack::Session::Abstract::SessionHash:0x007f866656ff60>
session.id: 67f5dc43590dec60303d7966e5e79ec2863800fbf95fc6fbf4093b6777b5aef0
session[:a]:
  DEBUG -       GET (0.0022s) / - 200 OK
```

Without `enable :sessions` (run with `padrino s`)
```
session: #<Rack::Session::Abstract::SessionHash:0x007fd82bdb8d90>
session.id: 535ce4897960cd02ac58416d51ff0e67a7ee26c6d85689b2e9d01a9366e6591a
session[:a]:
  DEBUG -       GET (0.0122s) / - 200 OK
session: #<Rack::Session::Abstract::SessionHash:0x007fd82bcd8100>
session.id: 535ce4897960cd02ac58416d51ff0e67a7ee26c6d85689b2e9d01a9366e6591a
session[:a]: 1
  DEBUG -       GET (0.0030s) / - 200 OK
```

**Comment by faustoct** [comment]
do you mean SESSIONS=true as environment variable?

**Comment by adam12** [comment]
> do you mean SESSIONS=true as environment variable?

I wrapped my example with an environment variable check just to demonstrate. It wouldn't be required in your app.

https://github.com/adam12/padrino_2091/blob/master/app/app.rb#L6-L9

**Comment by faustoct** [comment]
Ok. It is happening in production. I will run the the code locally and Heroku. I tell you soon.

**Comment by faustoct** [comment]
I test only locally because I got a different behavior of yours.

        SESSIONS=true padrino s
        INFO -  Enabling sessions
        => Padrino/0.13.3.3 has taken the stage development at http://127.0.0.1:3000
        [2016-11-19 16:18:46] INFO  WEBrick 1.3.1
        [2016-11-19 16:18:46] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin16]
        [2016-11-19 16:18:46] INFO  WEBrick::HTTPServer#start: pid=79509 port=3000
        session: #<Rack::Session::Abstract::SessionHash:0x007fdce517a8d0>
        session.id: b0fb289ec703c363554145fb36ead3ce3d91a147effbebbb9b63eb1c46957241
        session[:a]: 
          DEBUG -       GET (0.0128s) / - 200 OK
        session: #<Rack::Session::Abstract::SessionHash:0x007fdce52534f0>
        session.id: c931d6262eb74fcb20e2bbc37caa9c88866808fff510019da4cc7b402a0ba170
        session[:a]: 
          DEBUG -       GET (0.0016s) / - 200 OK


----


      padrino s
      => Padrino/0.13.3.3 has taken the stage development at http://127.0.0.1:3000
      [2016-11-19 16:21:00] INFO  WEBrick 1.3.1
      [2016-11-19 16:21:00] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin16]
      [2016-11-19 16:21:00] INFO  WEBrick::HTTPServer#start: pid=79528 port=3000
        `protect_from_csrf` is activated, but `sessions` seem to be off. To enable csrf
        protection, use:

            enable :sessions

        or deactivate protect_from_csrf:

            disable :protect_from_csrf

        If you use a different session store, ignore this warning using:

            # in boot.rb:
            Padrino::IGNORE_CSRF_SETUP_WARNING = true

      	from /Users/fausto/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
      session: #<Rack::Session::Abstract::SessionHash:0x007fa2d4c7ed08>
      session.id: 91bbc3c3417da07c53997fe14b77d8866363419d8837c4cc4eef96c368aaccbc
      session[:a]:
        DEBUG -       GET (0.6711s) / - 200 OK
      session: #<Rack::Session::Abstract::SessionHash:0x007fa2d4e14f78>
      session.id: 91bbc3c3417da07c53997fe14b77d8866363419d8837c4cc4eef96c368aaccbc
      session[:a]: 1
        DEBUG -       GET (0.2596s) / - 200 OK

**Comment by faustoct** [comment]
Any ideia? do you need any additional info?

**Comment by adam12** [comment]
> Any ideia? do you need any additional info?

Can you make a small re-producable test case?

I was able to reproduce your issue by leaving `enable :sessions` inside my `apps/app.rb` file. Removing it solved what I thought was your issue.

**Comment by faustoct** [comment]
I try some out here. By the way do you have any idea to session be blank on iphone 6? Any test I can try? I can provide an url on production where you can inspect the request, gems, setups, etc.

**Comment by faustoct** [comment]
@adam12 . My app does not have `enable :sessions` inside `apps/app.rb`.
The point here is on specific scenario on iphone6. It also happens on safari, session gets empty after certain time.

**Comment by adam12** [comment]
I really don't have any other suggestions - I don't think this is a Padrino bug.

That said, I visited the site in your opening post and noticed that you set a `session` cookie. Maybe try putting a far-expiry on it - like 30 days (`2592000`)?

Perhaps Safari is broken when it comes to session cookies - it wouldn't be the first time.

**Comment by faustoct** [comment]
Hi man. thanks for sharing the _session cookies bronken on Safari_ . It's been hard to handle different behaviors on safari chrome, desktop and mobile.

Good hear from you the session/cookie implementation look ok.

**Comment by faustoct** [comment]
Getting any solution out here I'll share to help others in this community.

**Comment by faustoct** [comment]
I came up with a workaround. Set expire time 100 years from now. It seems to work on safari. My solution on `app.rb` :

    before 
      env['rack.session.options'][:expire_after] = 100.year.from_now
    end
