### ISSUE TITLE
Route containing :lang symbol is not resolved correctly

### ISSUE THREAD

**Issue by happycze** [padrino/padrino-framework#2093]
Possible bug in router named parameters when using :lang as named parameter.

```
get "/action/:lang/:id" do
  # Doesn't work.
end
```

```
get "/action/:lng/:id" do
  # Works as expected.
end
```

Ruby 2.0
Padrino 0.12.3

**Comment by adam12** [comment]
Are you saying you can never reach the first route?

If so, the last route is likely overriding the first one, as once they are compiled they are near identical.

**Comment by happycze** [comment]
Sorry, i wasn't more specific. These routes are alternatives. When i use :lang as named parameter in a route, it won't be matched.

**Comment by adam12** [comment]
Can you make a small app that demonstrates this?

Using this style of routing requires a string parameter to the `controllers` method - but it would likely be easier to see what you're working with.

**Comment by happycze** [comment]
Okay, got it, Padrino-contrib autolocale is causing problems, see this gist [https://gist.github.com/happycze/f36637b9e435b626b88f71cb9d023eeb](https://gist.github.com/happycze/f36637b9e435b626b88f71cb9d023eeb).

If i disable padrino-contrib autolocale, everything works as expected.

**Comment by adam12** [comment]
You're likely stuck because it's assumed that `lang` will be unique in the route.

I made a patch to padrino-contrib that let's you set a custom locale param. Give it a go if you wish.

```ruby
# Gemfile
gem "padrino-contrib", git: "https://github.com/adam12/padrino-contrib.git", branch: "custom-locale-param"

# In your app config
set :locale_param, :locale
```

If you use it and it works for you, let me know so I can submit it upstream.

**Comment by happycze** [comment]
@adam12 Hi, i really appreciate your effort, but unfortunately your patch doesn't work for me :(

**Comment by adam12** [comment]
@happycze Any idea why? I tested it on your example and it worked.

https://gist.github.com/adam12/d398bddf54fe58a297bd8f0a395f5081

**Comment by happycze** [comment]
@adam12 It doesn't work for this url "http://localhost:3000/en/article/edit/en/tags", where article is app controller
