### ISSUE TITLE
support riot tag generator

### ISSUE THREAD

**Issue by grasp** [padrino/padrino-framework#2094]
#### Do you want to request a *feature* or report a *bug*?
Feature
#### What is the current behavior?
code generator is a killer function for newbie, and a way to improve code efficiency.
current padrino generator focus on server rendered html without JS MVVM framework.

#### What is the expected behavior?
we expected introduce JS mvvm into padrino web front , like vuejs, riot ,react etc.
personally I prefer riot which is most simple.

http://riotjs.com/

thus padrino can move to a modular based web front architecture.

**Comment by adam12** [comment]
Have you had any thoughts on how this might work?

I'm inclined to believe this would be out of the scope of the Padrino core project - but maybe more suited for an external extension.

RiotJS is very agnostic about how apps are structured, and even the format of the Riot tags themselves. As Padrino doesn't ship with an asset pipeline or any opinion on Javascript, Riot tags can be implemented in many different ways, and whatever way the Padrino core team chose would likely not appease a good portion of RiotJS users.

My 2c.

**Comment by grasp** [comment]
OK, this request is really challenge for traditional MVC framework, we can close this request.

I believe MVVM frame like riotjs is a more heavy framework as it introduced force split by backend and front end.

MVVM  have advantage  for Single Page Application scenario , may not use for MVC framework.
 
we could also think of turbolinks solution  in MVC, which is a page navigation solution on rails, it can speed the page load  by using client cache, and support Android and IOS integration.

https://github.com/turbolinks/turbolinks
