### ISSUE TITLE
default mongoid gem version upgrade in generator

### ISSUE THREAD

**Issue by grasp** [padrino/padrino-framework#2095]
#### Do you want to request a *feature* or report a *bug*?
feature
#### What is the current behavior?
current generator generate 
gem 'mongoid', '>= 3.0.0'

#### What is the expected behavior?

we expected default Gemfile to
gem 'mongoid', '>= 6.0.0'

**Comment by adam12** [comment]
Thank you for reporting this.

I'm inclined to think this is a non-issue - as the dependency matcher`>=` will allow for the latest mongoid version to be used.

In my test app, this was `6.0.2` by running `padrino generate project project_name -d mongoid`

**Comment by ujifgc** [comment]
Closing as not an issue. Please report if Padrino generates invalid models or migrations.
