### ISSUE TITLE
Anyone meet segment fault 11 on mac when run padrino command

### ISSUE THREAD

**Issue by grasp** [padrino/padrino-framework#2097]
#### Do you want to request a *feature* or report a *bug*?
Bug
#### What is the current behavior?

Run any of padrino command , it will be segment fault 11.
Segmentation fault: 11

I have raised a issue to ruby.
https://bugs.ruby-lang.org/issues/12982

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

ruby 2.2, 2.3
padrino 0.13.3

**Comment by grasp** [comment]
1.using padrino 0.12.8 , same error .

2. I using RVM to install ruby 2.3.3,and it was same error .

3.for rbenv , I tried several ruby version , still same issue.

seems no workaround on mac....

**Comment by adam12** [comment]
Can you generate a basic Padrino project? or does the Padrino gem segault on something like `padrino g project basic_project`?

**Comment by grasp** [comment]
Yes, Padrino can create a basic Padrino Project, after I  reinstall 2.3.3 based on rbenv.

so It could be caused my specific project, Padrino works  inside a  new  project.

maybe the problem is  package a padrino project as a gem, I will try build again from scratch to see what happened.

**Comment by ujifgc** [comment]
Do Padrino 0.12.7 or 0.13.2 segfault?

**Comment by grasp** [comment]
it has same issue on above two build.


after  I comments line in Gemfile
#Distribute your app as a gem
#gemspec

and

lib/new_talk.rb
require 'padrino-core'

module NewTalk
  extend Padrino::Module
  #gem! "new_talk"  #  comments out here
end

it seems related with package as a Gem.

**Comment by skade** [comment]
Can you put one of your failing projects on github somewhere?

**Comment by grasp** [comment]
@skade 
https://github.com/grasp/new_talk2

**Comment by adam12** [comment]
@grasp 

I'm able to temporarily fix the segfaults by changing the last line of your `bin/padrino` command to be:

```ruby
load Gem.bin_path("padrino-core", "padrino")
```

What I believe is happening is that Bundler looks at the `gemspec` for your project, specifically the `executables` line, which is the list of files in `bin/`. It then writes out binstubs for each of those files, clobbering the proper binstubs with it's own broken version.

When Bundler generates a binstub with the line above, it normally puts the name of the Gem as it's first argument (`padrino-core`, `haml`, etc). In this instance it's mistakenly changing it to `new_talk` for all your binstubs.

When you run your `padrino` command, it loads the binstub, which incorrectly loads itself repeatedly.

You can solve this permanently by changing `new_talk.gemspec`'s executable line to the following:

```ruby
gem.executables   = ["new_talk"]
```

And re-running `bundle --binstubs`.

That said, your `bin/new_talk` binstub is still broken. It should look something like this:

```ruby
#!/usr/bin/env ruby

Dir.chdir(File.dirname(__FILE__)+'/..')

# Start the app with Padrino::Server
require 'bundler/setup'
require 'padrino-core/cli/launcher'

ARGV.unshift('start') if ARGV.first.nil? || ARGV.first.start_with?('-')
Padrino::Cli::Launcher.start ARGV

# Start the app with Rack::Server
#require "rack"
#Rack::Server.start
```

Seems like some of the ideal advise is to move Gem specific bin's to the `exe` folder (https://github.com/bundler/bundler-features/issues/105 and https://github.com/bundler/bundler/commit/0ae330ede86905a17bb940b686d45e19b79f7e41).

Thoughts?

**Comment by adam12** [comment]
> Seems like some of the ideal advise is to move Gem specific bin's to the exe folder (bundler/bundler-features#105 and bundler/bundler@0ae330e).
> 
> Thoughts?

I went ahead and opened a PR to make this change. Seems to be more benefits than downsides.

**Comment by grasp** [comment]
Yes, I verified the solution . it works.

Thanks for the fix.

@adam12 

Many Thanks!
