### ISSUE TITLE
`padrino rake routes` fails with NoMethodError

### ISSUE THREAD

**Issue by oranges13** [padrino/padrino-framework#2098]
When attempting to run `padrino rake routes` I am suddenly getting the error

`padrino-core-0.13.2/lib/padrino-core/mounter.rb:133:in 'block in named_routes': undefined method 'name' for #<Array:0x000000021aab88> (NoMethodError)`

In an attempt to figure out which (if any) of my routes was causing the issue I systematically commented out all of my controllers one file at a time. Even with all of my controller code commented out, the error persists.

**Comment by adam12** [comment]
Are you able to attach the rest of the stack trace?

**Comment by oranges13** [comment]
[Here you go](https://gist.github.com/oranges13/e4fe7d7a5cef230fff92d81e7b75cb85)

I have somewhat narrowed it down to the order in which I include Sidekiq::Web

For instance (in apps.rb):

```
# Mounts the core application for this project
Padrino.mount('Portal::App', :app_file => Padrino.root('app/app.rb')).to('/')
Padrino.mount('Sidekiq', :app_class => 'Sidekiq::Web', :app_root => Sidekiq::Web.root).to('/sidekiq')
```

Seems like this may actually be an issue in Sidekiq -- if I put it 2nd I do get my own app's routes before the error. If I put it first, I just get the error.

**Comment by adam12** [comment]
Likely not Sidekiq related (which is a Sinatra app under the hood).

I don't believe Sinatra applications have a routes method, which is what Padrino expects when mounting apps and displaying routes.

I created #2100 with a possible fix.
