### ISSUE TITLE
How to set Cache-control  in framework

### ISSUE THREAD

**Issue by yongwoon** [padrino/padrino-framework#2102]
#### Do you want to request a *feature* or report a *bug*?
feature

#### What is the current behavior?

I set the static_cache_controle in app.rb
```
set :static_cache_control, ['no-transform', {:max_age => 0}]
```

and check header 
```
Server: Apache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger
Set-Cookie: 98651
path=/; expires=Sat, 07 Jan 2017 10:24:56 -0000; HttpOnly
Content-Length: 217731
Status: 200 OK
X-Content-Type-Options: nosniff
Connection: close
Content-Type: text/html;charset=utf-8
```

#### What is the expected behavior?
I expect cache-control setting inserted in http header response as following:
Cache-Control: no-transform, max-age=0

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby       2.1.5
Sinatra   1.4.3
Padrino   0.11.2
OS           centOs

**Comment by ujifgc** [comment]
This settings only sets the header on files served statically by Sinatra/Padrino. It does not set any headers for the regular requests or requests served statically by proxying web server.

Ref: http://www.sinatrarb.com/intro.html#Static%20Files

As you are using Apache with Phusion Passenger you probably should configure locations of the static files to set this header.

**Comment by yongwoon** [comment]
Thanks you comment.
