### ISSUE TITLE
Time/Datetime Select Field

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-framework#2103]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What is the expected behavior?

Form helpers for time and datetime select fields. 

I was thinking specifically about ActiveRecord, as it's supported easily via the`field_name(1i)`, `field_name(2i)`, etc... syntax. Of course Padrino is DB agnostic, so maybe this could go in Padrino Contrib (or just elsewhere). Or, maybe a generic solution can be provided.  

Thoughts?

**Comment by adam12** [comment]
Are many people using this multi-input type of date / date time select anymore?

You could support Sequel by passing a hash of `year`, `month`, `day`, so perhaps if you were to go ahead with this, you could have a form helper that could be configured for the database adapter. Output numerically ordered selects for AR, and a hash for Sequel. No idea for the rest of the ORMS tho :\ 

Another option is just a helper that does the selects (year, month, day named), and people can cast to their own format in their model.

**Comment by ujifgc** [comment]
Closing as probably won't make it to Padrino-helpers as it's very entangled with ORM implementation.

Feel free to implement it as a plugin.
