### ISSUE TITLE
2016, ++(++(++(2013))) and Issue #1251 still needs a workaround

### ISSUE THREAD

**Issue by lonniev** [padrino/padrino-framework#2110]
WARN - attack prevented by Rack::Protection::AuthenticityToken #1251

From 2013. Now in 2016, one still has to alter the out of the box padrino gen admin app to avoid this POST 403 error.

The fix still remains as:

```ruby
# config/apps.rb
#
Padrino.configure_apps do
  # enable :sessions
  set :session_secret, '183b03c435cc2e157054d1245dac164f661800a31db796e0f7e76bab7ecdf0ae'
  set :protection, :except => :path_traversal
  set :protect_from_csrf, true
  set :allow_disabled_csrf, true # this is the crucial addition
end
```

and then in the admin/controllers/sessions.rb file:

```ruby
# admin/controllers/sessions.rb
#
  post :create, :csrf_protection => false do
    if account = Account.authenticate(params[:email], params[:password])
```

Ideally, the out of the box admin app would be altered to work with CSRF enabled and with the sessions/new handler passing a suitable session authority token. For a newbie to pandrino/sinatra like me, that's too hard a fix for now.

**Comment by ujifgc** [comment]
What are the steps to generate a faulty app?

**Comment by lonniev** [comment]
- cloud9
- gem install padrino
- padrino g project myproject -d mongoid -s jquery -e haml -t rspec -b
- cd myproject
- padrino g admin
- padrino rake db:seed
- padrino s -h $IP -p $PORT
- browse to .../admin
- login
- get 403 Forbidden

There may have been some bundle exec calls midway but, basically, just out of the box package install and try a minimal smoke test.

**Comment by ujifgc** [comment]
Can not reproduce, it works without any problems. Can you publish a minimal faulty app with `Gemfile.lock`?

**Comment by ujifgc** [comment]
Closing for the lack of feedback.

**Comment by HorizonShadow** [comment]
I'm seconding this error. 

```
padrino g project blog-tutorial -t rspec -e haml -scss -s jquery -d sequel -b
padrino g admin 
padrino rake db:create
padrino rake db:migrate
padrino rake db:seed
Attempt to login to admin
Get 403 forbidden
```

https://github.com/HorizonShadow/padrino-admin-error

**Comment by ujifgc** [comment]
Failed to reproduce with Padrino 0.14.1.1 and the provided commands
Failed to reproduce with https://github.com/HorizonShadow/padrino-admin-error Gemfile.lock

Please, check your application log, there might be some messages from Rack::Protection
