### ISSUE TITLE
WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add './lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly

### ISSUE THREAD

**Issue by bigtunacan** [padrino/padrino-framework#2117]
In the latest version of Padrino I am receiving this WARNING

`WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add
'./lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly`

Is there a way I can easily add this back in?  Was this change security related?

**Comment by ujifgc** [comment]
You can add `$LOAD_PATH.unshift Padrino.root('lib')` or `$LOAD_PATH.push Padrino.root('lib')` to your `config/boot.rb`.

The change is not security-related. It was mostly done to raise user awareness of Ruby feature requiring mechanics and to lower the magicness of the framework.

**Comment by neohunter** [comment]
I added it to boot.rb but warning still appearing

**Comment by kennwilson** [comment]
Confirming that adding /lib to $LOAD_PATH does not suppress this message when rake tasks are run. Any other suggestions?
