### ISSUE TITLE
how to handle subdomains per controllers

### ISSUE THREAD

**Issue by faustoct** [padrino/padrino-framework#2124]
How to handling subdomains in certain controllers:
sub1.domain.com -> Controller::Sub1
sub2.domain.com -> Controller::Sub2
others -> Controller::Basic

how to do it?

**Comment by faustoct** [comment]
anyone?

**Comment by basex** [comment]
@faustoct sub1.domain.com and sub2.domain.com if they don't share controllers, you should put them in different apps
http://padrinorb.com/guides/features/mounting-applications/#advanced-mounting-support

You can then have a main padrino app for all the other subdomains.

**Comment by faustoct** [comment]
@basex Got it. I read this doc. I have this in my apps.rb

Padrino.mount('MyApp::App', :app_file => Padrino.root('app/app.rb')).to('/')

my app.rb
...
    register LessInitializer
    register Padrino::Rendering
    register Padrino::Helpers
    register Padrino::Cookies
    register Padrino::Cache
    register OmniauthInitializer

    use Rack::Deflater
    enable :caching
...

would create new have trouble with session, cache, etc?

**Comment by basex** [comment]
You can use the generator, to generate the skeleton of different apps inside.
http://padrinorb.com/guides/generators/sub-applications/

By default I'm not wrong they share the same database, session secret etc, but you change that.

I normally don't use the generator.

**Comment by faustoct** [comment]
@basex do I have any problem redefining and reinstantiating connections like cache, database, etc ?  or that's ok?

**Comment by faustoct** [comment]
@basex how can I contact u?

**Comment by faustoct** [comment]
How can I contact u filipe? u have email?


Fausto
