### ISSUE TITLE
catching `LoadError` when loading `database.rb` leads to confusing errors

### ISSUE THREAD

**Issue by fnordfish** [padrino/padrino-framework#2125]
I've run into an interesting to track down error using padrino 0.13.3.3 and sequel 4.44.0 (also see jeremyevans/sequel#1317)

When a `LoadError` is raised inside `database.rb` it is going to get "swallowed" which leads to errors way later in the application.

In my particular case a `LoadError` was raised before the database connection could be established. Since the loader just carried on, it finally crashed when loading a model (which do some introspection on their database)

While this behaviour is certainly useful for dealing with a common applications `/lib` directories, it hides very useful errors in important setup/init files.
Is there any way to exclude the `database.rb` from this (otherwise useful) loading behaviour?

**Comment by jorgefuertes** [comment]
I'm using this approach at `database.rb`:
```ruby
loop do
  begin
    MongoMapper.connection = Mongo::Connection.new('localhost', nil, logger: logger, pool_size: 16, pool_timeout: 30)
    logger.info 'MongoDB connection OK'
    break
  rescue StandardError => e
    logger.fatal 'MongoDB connection error! Please ensure Mongo is running!'
    logger.error e.message
    sleep 5
    logger.fatal 'Retrying...'
  end
end

case Padrino.env
when :development then MongoMapper.database = 'dbname_development'
when :production  then MongoMapper.database = 'dbname_production'
when :test        then MongoMapper.database = 'dbname_test'
end
````

**Comment by fnordfish** [comment]
Right. I could wrap my entire `database.rb` into a

```ruby
begin
  # ...
rescue LoadError => e
  raise ScriptError.new(e) # or any other than which is not NameError or LoadError
end
```

But somehow, adding that stuff to avoid a framework specific behaviour feels weird (not very [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment))

**Comment by ujifgc** [comment]
Can not reproduce. Please publish a minimal failing (or in your case, not failing properly) project to Github.

**Comment by fnordfish** [comment]
@ujifgc: https://github.com/fnordfish/padrino_sequel_2125
