### ISSUE TITLE
Layout is enabled when using partial

### ISSUE THREAD

**Issue by krororo** [padrino/padrino-framework#2128]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
following example: 

layouts/application.haml
```haml
!!!
%html
  #header
    application
  = yield
```

index.haml
```haml
index
%br
= partial 'foo'
```

_foo.haml
```haml
foo
```

renderd html is

```html
<!DOCTYPE html>
<html>
  <div id='header'>
    application
  </div>
  index
  <br>
  <!DOCTYPE html>
  <html>
    <div id='header'>
      application
    </div>
    foo
  </html>
</html>
```
#### What is the expected behavior?

rendered

```html
<!DOCTYPE html>
<html>
  <div id='header'>
    application
  </div>
  index
  <br>
  foo
</html>
```

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Padrino 0.14.0

It works at padrino 0.13.3.3

**Comment by ujifgc** [comment]
Thank you for your report!

**Comment by krororo** [comment]
Thank you!
