### ISSUE TITLE
Push updated version w/ fix for syntax error in activerecord padrino-gen tasks

### ISSUE THREAD

**Issue by pdlug** [padrino/padrino-framework#2135]
There's a syntax error in the padrino-gen activerecord tasks which was resolved with commit [4a80dca](https://github.com/padrino/padrino-framework/commit/4a80dca4ec0c52a9c7daa2e28d17c1d8cb024e4b). Can someone push an updated gem to resolve this? Thanks.

**Comment by ujifgc** [comment]
Done, pushed 0.14.1
