### ISSUE TITLE
Rakefile fails

### ISSUE THREAD

**Issue by faustoct** [padrino/padrino-framework#2138]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
it fails when run: `bundle exec rake -P`

*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
0.14.2

Simple Rakefile can't finish execution (fails)

    require 'bundler/setup'
    require 'padrino-core/cli/rake'
    PadrinoTasks.use(:mongoid)
    PadrinoTasks.init

Error message
```
$ bundle exec rake -P
rake aborted!
SyntaxError: /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:146: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      desc "Runs the "up" for a given MIGRATION_VERSION."
                        ^
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:149: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      desc "Runs the "down" for a given MIGRATION_VERSION."
                          ^
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.14.0.2/lib/padrino-core/cli/rake.rb:15:in `init'
/Users/fausto/Projects/coding/4linked/Rakefile:15:in `<top (required)>'
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by faustoct** [comment]
looks to be the same problem found here
https://github.com/padrino/padrino-framework/issues/2134

**Comment by adam12** [comment]
Fixed in 0.14.1.

**Comment by wikimatze** [comment]
@faustoct can you close this issue?

**Comment by faustoct** [comment]
It's happening again in 0.14.2

**Comment by adam12** [comment]
> It's happening again in 0.14.2 @adam12 @wikimatze

Can you post an updated stacktrace?

**Comment by faustoct** [comment]
@adam12 executed it right now. how you can see it's padrino 0.14.2 in stacktrace
```
$ bundle exec rake -P
rake aborted!
SyntaxError: /Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:146: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      desc "Runs the "up" for a given MIGRATION_VERSION."
                        ^
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-gen-0.14.0.2/lib/padrino-gen/padrino-tasks/activerecord.rb:149: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      desc "Runs the "down" for a given MIGRATION_VERSION."
                          ^
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.14.0.2/lib/padrino-core/cli/rake.rb:15:in `init'
/private/tmp/cool/Rakefile:9:in `<top (required)>'
/Users/fausto/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/fausto/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by adam12** [comment]
@faustoct That's a version behind 0.14.1 (and 0.14.1.1 which is latest).

https://rubygems.org/gems/padrino-gen/versions

**Comment by faustoct** [comment]
@adam12 to clarify . in padrino home page says the stable version is 0.14.0.2 is that right?

**Comment by wikimatze** [comment]
@faustoct the latest version of Padrino is 0.14.1.1 is, I've worked with it recently for the benchmarking project. You can find the mongoid app here: https://github.com/wikimatze/padrino-benchmarks/tree/master/orms/mongoid-app - everything worked there so far.

**Comment by wikimatze** [comment]
@faustoct I haven't written the blog-post about the latest release for the homepage (will do this in the following week).

**Comment by adam12** [comment]
> @adam12 to clarify . in padrino home page says the stable version is 0.14.0.2 is that right?

It's not :( It's a documentation error. 0.14.1.1 is definitely latest.

**Comment by wikimatze** [comment]
@adam12 yeah, it grabs the latest version from the blog post to update the version on the front-page (it's just build that way :smile:)!

**Comment by faustoct** [comment]
@adam12 @wikimatze  thanks guys. I'm gonna run a new test and let you guys know soon.

**Comment by wikimatze** [comment]
And @faustoct let's discuss those "try-this-and-that" discussions better on gitter: https://gitter.im/padrino/padrino-framework

**Comment by faustoct** [comment]
@adam12 @wikimatze **everything is working fine**. btw thanks  for inviting to join the community.

**Comment by wikimatze** [comment]
We are welcoming everyone to our small group. Oh, is it fixed by now?

**Comment by faustoct** [comment]
yeah! just close the issue.
