### ISSUE TITLE
IRC channel maintenance

### ISSUE THREAD

**Issue by adam12** [padrino/padrino-framework#2140]
Some of us (@wikimatze and me @adam12) have been idling in the channel and helping users, but some things have been difficult without operator status (like updating channel title).

@skade implemented a temporary fix a while ago, but it would be great to have a more permanent fix.

I opened discussions with Freenode staff, and it was suggested that the project be registered with them through a short email.

The format of that email to follow this: https://gist.github.com/AbstractBeliefs/f82487dc7d7db54d7c94740c25c08084

To be submitted here:
projects@freenode.net

By someone from this list: 
https://github.com/orgs/padrino/people

And then we can update the list of operators.

Is this something we can get taken care of?

cc @achiu (channel founder)

**Comment by wikimatze** [comment]
Or maybe we can ask directly on freenode about our issues. Think @achiu should give ops right to all @padrino/core-members then we should have at least one person who can handle the channel.

**Comment by wikimatze** [comment]
The following mail has been sent:

```
Hi,

we've talked to kline on #padrino and we're following his advice mentioned on https://freenode.net/groupreg

----------------------------------------------------------------------------------------------------------

# About your project
Your project name: Padrino
Your project blurb: Padrino is a Ruby web framework built upon the Sinatra web library

Links to places we can find out more about your project:
- http://padrinorb.com/
- https://github.com/padrino

# About you and your staff
Your nick: wikimatze
Your relationship to the project: I'm one of the project maintainers
Nicks of alternate GCs:
- achiu
- skade
- adam12
- wakatara

# About freenode
Channels you'd like to claim (typically #projectname): #padrino
Channel namespaces you'd like to claim (typically #projectname-*): #padrino-*
Cloak namespaces you'd like to claim (typically projectname/*): padrino/*

Notes you may wish to read:
* Group registration: https://freenode.net/groupreg
* Information on freenode policies: https://freenode.net/policies


----------------------------------------------------------------------------------------------------------


Cheers

Matthias
```

Now let's wait and see.

**Comment by wikimatze** [comment]
Think we can close those issue now.

**Comment by adam12** [comment]
> Think we can close those issue now.

Agreed.
