### ISSUE TITLE
Encoding problem under lastest padrino 

### ISSUE THREAD

**Issue by jiyaping** [padrino/padrino-framework#2144]
Hi  @ujifgc  , As issue #2143  mentioned ,I have a project using padrino version 0.13.3.2 and upgrade to lastest version 0.14.1.1, Some encoding problem occured , as following:

```
E:\aocproject>padrino g admin -e erb
d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `scan': invalid byte sequence in GBK (ArgumentError)
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `fetch_app_name'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/admin_app.rb:57:in `create_admin'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'

```

Is there any solutions?  Thanks.

**Comment by sshaw** [comment]
I do not have this problem with 0.14.1.1 on Windows using 2.2.6.

`actions.rb:75` (or [somewhere close to there](https://github.com/padrino/padrino-framework/blob/0.14.1.1/padrino-admin/lib/padrino-admin/generators/actions.rb#L75)) tries to read your `app.rb` file. It's likely this file's encoding does not match Ruby's default external encoding (`Encoding.default_external`) (Mine is IBM437 --I'm in the USA). 

In the short-term, I'd try to figure out what that file's encoding is and set it via:

```batch
set rubyopt="-E Windows-1252"
```

Then try running `padrino g admin -e erb` again. 

Note that the argument to `-E` must match what Ruby supports. For this list see the results of `Encoding.list`.

**Comment by ujifgc** [comment]
Since 6609b907579ec1b560c978a462ff2ed350a2ea35 0.14.0 Padrino does not manage your project encoding.

If you use in your files encoding other than your system encoding you could set this in your `config/boot.rb`:

```
Encoding.default_external = Encoding::UTF_8 # or whatever encoding you use in your files
```

**Comment by jiyaping** [comment]
Hi @sshaw , Thanks for your help, I try those instructions and get error message like this:

```
E:\aocproject>set rubyopt="-E'Windows-1252'"
E:\aocproject>padrino g admin -e erb
d:\RailsInstaller\Ruby2.2.0\bin\ruby.exe: invalid option -"  (-h will show valid options) (RuntimeError)
```

use this style will work fine.

```
set rubyopt=-E Windows-1252
```
