### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by stoplion** [padrino/padrino-framework#2148]
ruby '2.4.1'
'padrino', '0.14.1.1'

`bundle exec rake db:migrate`
using sqlite
OSX 10.12.5

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateAccounts < ActiveRecord::Migration[4.2]

```

I changed `class CreateAccounts < ActiveRecord::Migration`
to `class CreateAccounts < ActiveRecord::Migration[5.0]`
and it worked..

**Comment by adam12** [comment]
Thanks for the report.
