### ISSUE TITLE
Project generator silently ignores invalid -a option

### ISSUE THREAD

**Issue by white-monkey** [padrino/padrino-framework#2150]
With current version 0.14.1.1:

```
$ padrino g project test -d sequel -a access97
```

successfully generates the project, even though the RDBMS value is obviously invalid, and uses sqlite as default. I would expect an error message instead.

**Comment by wikimatze** [comment]
Hi @white-monkey thanks for the feedback. Do you mean a text-message like:

```The provided database adapter 'access97' is not valid. Valid adapters are 'sqlite', 'mysql', 'mysql2', 'mysql-gem', 'postgres'
```

What do other @padrino/core-members think about this change?

**Comment by ujifgc** [comment]
Of course it's a bug.

**Comment by wikimatze** [comment]
@ujifgc is the message I've provided okay? If yes, I would like to implement this change.

**Comment by ujifgc** [comment]
Sure.
