### ISSUE TITLE
Generated project with sequel/sqlite fails to start

### ISSUE THREAD

**Issue by skatkov** [padrino/padrino-framework#2154]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
1. `padrino g project project_name -d sequel -a sqlite -t minitest -e haml -c sass`
2. start `padrino start`

receive error:
```
/Users/sk/.rvm/gems/ruby-2.4.1/gems/sequel-5.0.0/lib/sequel/model/base.rb:931:in `require': cannot load such file -- sequel/plugins/schema (LoadError)
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/sequel-5.0.0/lib/sequel/model/base.rb:931:in `plugin_module'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/sequel-5.0.0/lib/sequel/model/base.rb:550:in `plugin'
	from /Users/sk/code/soihok/config/database.rb:1:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/reloader.rb:91:in `require'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/reloader.rb:91:in `safe_load'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/loader.rb:154:in `block in require_dependencies'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/loader.rb:152:in `each'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/loader.rb:152:in `require_dependencies'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/loader.rb:57:in `load!'
	from /Users/sk/code/soihok/config/boot.rb:60:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/cli/launcher.rb:25:in `require'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/padrino-core-0.14.1.1/lib/padrino-core/cli/launcher.rb:25:in `start'
	from /Users/sk/.rvm/gems/ruby-2.4.1/gems/thor-
```

#### What is the expected behavior?
Generated application should start

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
OSX
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
Padrino v. 0.14.1.1
https://gist.github.com/skatkov/8fcbbb9a0a8f685e88d349dfd7f1c15c

**Comment by adam12** [comment]
Thanks for the report.

Fixed in 1906c27e5e73. Just need a release cut now that Sequel 5 is out.

**Comment by skatkov** [comment]
Thank you for a prompt response. Will use edge version ;-)

**Comment by skatkov** [comment]
Uh.. updating to edge version didn't resolve the issue. Any workarounds for this i'm missing?

**Comment by adam12** [comment]
My bad. Actually solved in c166e6efed142bda6dcd1ad3667c0ed5b58e948c, but won't apply to already generated projects.

Inside your `config/database.rb`, remove the first line which should be `Sequel::Model.plugin(:schema)`.

**Comment by pennyU2** [comment]
@adam12 Oh my gosh! I love you! I was having the same problem and that worked like a charm. Thank you so much.

**Comment by wikimatze** [comment]
@skatkov can you close this issue now.

**Comment by skatkov** [comment]
Resolved. Closing.
