### ISSUE TITLE
humanize NoMethodError on padrino-0.14.1.1

### ISSUE THREAD

**Issue by constdrop** [padrino/padrino-framework#2157]
I used padrino-0.14.1.1 and activesupport-5.1.1 in combination. ruby version is 2.3.0, sinatra is 2.0.0.
I generate padrino admin app. When I display the login page (/admin/sessions/new) the following error occurred and become 500 error page.

    DEBUG -  TEMPLATE (0.0007s) /sessions/new
    2017-11-07 20:23:01 - NoMethodError - undefined method `humanize' for "login.title":String:
	    /Path/to/app/'vendor/bundle' /ruby/2.3.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/helpers/view_helpers.rb:43:in `padrino_admin_translate'
    ...

I add the following require to the beginning of view_helpers.rb provisionaly.

    require 'active_support'
    require 'active_support/core_ext/string'

I think it may not be a bug. But if it is a bug, could you fix it?
If it is not a bug, I think it is not good to edit Padrino's files because of my application problem. Please let me know if you have any other good countermeasures.

I have posted to stackoverflow same issue.
https://stackoverflow.com/questions/47168434/humanize-nomethoderror-on-padrino-0-14-1-1

**Comment by adam12** [comment]
It's a bug due to the ongoing effort to remove the ActiveSupport dependency from Padrino.

You don't need to update `view_helpers.rb` - creating a file in `config/initializers` should be sufficient.

```ruby
# config/initializers/extra_requires.rb
require "active_support"
require "active_support/core_ext/string"
```

**Comment by constdrop** [comment]
Thanks. I tried your suggestion, and it work well.
I'm waiting for the version fixed this bug.

**Comment by ujifgc** [comment]
Can not reproduce. When generated `admin/app.rb` has

```
require 'active_support/core_ext/object/blank'
require 'active_support/core_ext/string/inflections'
```

that have the features you require.
