### ISSUE TITLE
padrino gen task bad argument parsing

### ISSUE THREAD

**Issue by jorgefuertes** [padrino/padrino-framework#2163]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

```shell
$> padrino gen task -n main -d "Just a test task" test
create  tasks/main_a.rake
```

Generated file has wrong name and description:

```ruby
namespace :main do
  desc "Just"
  task :a => :environment do
    # This is a custom task.
  end
end
```

#### What is the expected behavior?

```shell
create tasks/main_test.rake
```

Having this file the following content:

```ruby
namespace :main do
  desc "Just a test task"
  task :test => :environment do
    # This is a custom task.
  end
end
```

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

- Ruby 2.4.4
- Padrino v. 0.14.1.1

But never worked.

**Comment by ujifgc** [comment]
Thanks for the report.
