### ISSUE TITLE
padrino gen task doesn't fit latest ruby conventions

### ISSUE THREAD

**Issue by jorgefuertes** [padrino/padrino-framework#2164]
#### Do you want to request a *feature* or report a *bug*?

feature

#### What is the current behavior?

```padrino gen task```generate this file:

```ruby
namespace :main do
  desc "Just a test task"
  task :test => :environment do
    # This is a custom task.
  end
end
```

#### What is the expected behavior?

In a better form it should be:

```ruby
namespace :main do
  desc 'Just a test task'
  task test: :environment do
    # This is a custom task.
  end
end
```

**Comment by namusyaka** [comment]
Related to #2121 
We're going to switch to new syntax when releasing v1.0.0.

**Comment by jorgefuertes** [comment]
Ok, thanks!
