### ISSUE TITLE
haml did not translate:  %transition

### ISSUE THREAD

**Issue by grasp** [padrino/padrino-framework#2171]
#### Do you want to request a *feature* or report a *bug*?
a bug
#### What is the current behavior?

haml did not translate:
 %transition

*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*

when we have %transition in haml, padrino will ignore it.
while haml command line can convert it.

#### What is the expected behavior?

%transiton should be converted as a html element

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

ruby 2.4.3
padrino: 0.13.3
sinatra: 1.4.8
Rack: 1.6.8
OS : Mac and Ubuntu

**Comment by wikimatze** [comment]
You have to update Padrino to get an updated version of haml, which solve that issue. I've added an example app under <https://github.com/wikimatze/padrino_content_for_bug> where transition is working. I've seen that you already posted that bug under <https://github.com/haml/haml/issues/973> and in the provided example app there is is `haml (5.0.1)`. Hope that fixes your issue.
