### ISSUE TITLE
Padrino admin using Mongoid grabs wrong Regexp class when authenticating

### ISSUE THREAD

**Issue by LarryFransson** [padrino/padrino-framework#2181]
#### Do you want to request a *feature* or report a *bug*?
Bug report

#### What is the current behavior?

The Padrino admin, using Mongoid, produces ```NoMethodError - undefined method `escape' for Mongoid::Matchable::Regexp:Class``` in the account class in the line

    account = where(:email => /#{Regexp.escape(email)}/i).first if email.present?

due to a collision with Mongoid::Matchable::Regexp:Class

The solution is to prefix ```Regexp``` with ```Object::``` so that the line looks like

    account = where(:email => /#{Object::Regexp.escape(email)}/i).first if email.present?

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby 2.5.0, Padrino 0.14.3, Sinatra 2.0.1, Mongoid 7.0.0

**Comment by wikimatze** [comment]
Thanks for the error report. Have you maybe tried to fix that issue in our codebase?

**Comment by LarryFransson** [comment]
I'll try to figure out the process for doing that.

**Comment by LarryFransson** [comment]
OK - you have a pull request.

**Comment by wikimatze** [comment]
@LarryFransson thanks for the fix.

**Comment by LarryFransson** [comment]
Happy I could help!
