### ISSUE TITLE
Number to Human function

### ISSUE THREAD

**Issue by setiawand** [padrino/padrino-framework#2190]
dear

i'm not a ruby speaker, i found the number_to_human_size function, but it doesnt have number_to_human function as rails did. Is it going to be implemented?

best regards

**Comment by basex** [comment]
You can import actionview and use it outside rails.

```ruby
2.5.1 :001 > require 'action_view'
 => true 
2.5.1 :002 > include ActionView::Helpers::NumberHelper
 => Object 
2.5.1 :003 > number_to_human(1234) 
 => "1.23 Thousand" 
```

**Comment by setiawand** [comment]
hi @basex do i need to add gem into my Gemfile ? thanks man!
