### ISSUE TITLE
padrino-gen bundler ~> 1.0 dependency

### ISSUE THREAD

**Issue by Esity** [padrino/padrino-framework#2205]
Current padrino-gen has bundler ~> 1.0 as a requirement in the gemspec.

I think we should change this to support bundler 2.0 unless there is a specific reason not too

**Comment by sshaw** [comment]
Bundler 2  has Ruby requirements that I think are too restrictive at this point. And Ruby what Ruby versions are or are not officially supported should not matter.

**Comment by Esity** [comment]
The issue is that it forces anyone who wants to use Padrino to use Bundler < 2. 

Is there a reason why padrino-gen requires 1.0 but other things do not have a bundler requirement?

**Comment by wikimatze** [comment]
@Esity thanks for your PR. As you can see it on travis (https://travis-ci.org/padrino/padrino-framework/jobs/483547657) breaks support for ruby 2.2.0 and we don't want that actually right now.

**Comment by adam12** [comment]
I think this PR should likely get merged, but with some modification. Instead of open-ending the `bundler` dependency, we'd probably be better off with something akin to:

```ruby
s.add_dependency("bundler", ">= 1.0", "< 3")
```

It doesn't appear that the `Gemfile` spec has changed much, at least as far as `padrino-gen` is concerned when templating, but `bundler` has a new Ruby requirement. This means that at least at this point, Bundler 1.x and 2.x are compatible with `padrino-gen` and should be accepted.

With that said, Travis failures will likely be constant now without some changes to `.travis.yml`, with #2206 actually bringing this to light. All the Travis Ruby versions ship with `bundler` installed (you can see their version in each build log, under the Ruby Version section), but it's [forcefully re-installed every time](https://github.com/padrino/padrino-framework/blob/cb4b6032af91dd14172df8d8658cf7e9fa316a37/.travis.yml#L5), without any concern to the version requested. Because `bundler` is now in the 2.x series, that installation command will default to the latest, which means that any PR / commit going forward will show as broken on the 2.2.x Travis build matrix.

The two possible solutions to this:

1. Update the `before_install` option to force the latest `bundler` version to support Ruby 2.2: `gem install bundler -v 1.17.3`

2. Remove the `before_install` option entirely, using the vendored bundler provided by Travis (and in later version of Ruby, the bundled Ruby version).

I don't have a preference to this, other than the second option seems the most sane to me.

**Comment by wikimatze** [comment]
@adam12 thanks for your thought about how to solve this issue. I would go for option two. @Esity can you try this in your PR?

**Comment by AlfredoRamos** [comment]
Any news on this?

**Comment by namusyaka** [comment]
Just fixed the failure on travis by #2210. 
IMHO I would like to use latest bundler which meant 2.0.0 or later. But as @sshaw mentioned, we should realize overall and its pros/cons on the change before adopting that.

**Comment by Miguelcldn** [comment]
Me and my team found out this restriction that affects our deployment and development. We'll use @Esity's branch for now while we look forward for this branch to be merged soon.

**Comment by nemasket** [comment]
My workaround to this was based on information found in bundler documentation.  (https://bundler.io/v2.0/guides/bundler_2_upgrade.html)

By adding a Gemfile.lock file containing BUNDLED WITH 1.17.1 to a freshly generated Padrino project, I was able to successfully run bundle --binstubs in the new project.  

Here's the terminal output for this, illustrating the error, creation of the file, and successful execution after the Gemfile.lock with appropriate content:  

jurgen@gomez:~/projects/local/padrino/exp/bba$ bundle -v
Bundler version 2.0.1
jurgen@gomez:~/projects/local/padrino/exp/bba$ bundle --binstubs
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    padrino (= 0.14.4) was resolved to 0.14.4, which depends on
      padrino-gen (= 0.14.4) was resolved to 0.14.4, which depends on
        bundler (~> 1.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.0)', which is required by gem 'padrino-gen (= 0.14.4)', in any of the sources.
jurgen@gomez:~/projects/local/padrino/exp/bba$ vi Gemfile.lock
jurgen@gomez:~/projects/local/padrino/exp/bba$ bundle --binstubs
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using activemodel 5.2.3
Using bson 4.5.0
Using bundler 1.17.2
Using diff-lcs 1.3
Using erubi 1.8.0
Using mini_mime 1.0.1
Using mail 2.7.1
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using moneta 1.0.0
Using mongo 2.8.0
Using mongoid 7.0.3
Using mustermann 1.0.3
Using padrino-support 0.14.4
Using rack 2.0.7
Using rack-protection 2.0.5
Using tilt 2.0.9
Using sinatra 2.0.5
Using thor 0.20.3
Using padrino-core 0.14.4
Using padrino-helpers 0.14.4
Using padrino-admin 0.14.4
Using padrino-cache 0.14.4
Using padrino-gen 0.14.4
Using padrino-mailer 0.14.4
Using padrino 0.14.4
Using rack-test 1.1.0
Using rspec-support 3.8.0
Using rspec-core 3.8.0
Using rspec-expectations 3.8.3
Using rspec-mocks 3.8.0
Using rspec 3.8.0
Bundle complete! 6 Gemfile dependencies, 39 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
jurgen@gomez:~/projects/local/padrino/exp/bba$ bundle -v
Bundler version 1.17.2

This was on a freshly built system with recent binaries, ruby 2.6, bundler 2.0, etc., where I just wanted to run bundler.  The auto switch capability of bundler takes care of things.   Maybe this approach will work elsewhere, too.

**Comment by yb66** [comment]
Evening.

Any word on this? I think you can get away with 6 months for this kind of decision but let it go for 7 and it'll seem excessive ;-)

Regards,
iain

**Comment by elianfish** [comment]
Can this problem be solved?
error: specification.rb:2298:in `raise_if_conflicts': Unable to activate padrino-gen-0.14.4, because bundler-2.0.2 conflicts with bundler (~> 1.0) (Gem::ConflictError)

**Comment by renich** [comment]
I'm interested in this getting fixed as well. Total blocker.

**Comment by renich** [comment]
OK, here's a quick workaround, but this sucks: 

```
gem install bundler -v 1.17.3
padrino gen project my-project
cd my-project
bundler _1.17.3_ install --path=vendor/bundle
```

... did I mention this sucks? ... well, it sucks :S

**Comment by cyclotron3k** [comment]
Is supporting Ruby 2.2 (EOL 20 Jun 2018) more important than supporting Ruby 2.6 & 2.7?

Because a default install of 2.6 & 2.7 will choke on Padrino.

**Comment by phobetron** [comment]
Personally, I've considered Padrino a dead project over this kind of thing, and moved on.

**Comment by Kenney-G** [comment]
Yeah I was excited to try this out...

**Comment by sriedel** [comment]
Running bundle install with bundler 1.17.3 on ruby 2.7.0 with gem version 3.1.2 is bringing up a deprecation warning: 

/opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated

So I'm not sure things will work with ruby 2.8/3.0 any more. would it be possible to get a padrino release before christmas that allows a bundler 2.x to be used?

**Comment by cblackburn-ajla** [comment]
> Personally, I've considered Padrino a dead project over this kind of thing, and moved on.

It has been several years since I used Padrino. Today I had an ideal project in mind but after running into this nonsense I've decided it just isn't worth it. I don't want to have to deal with switching bundler versions for different projects.

What a shame. ☹️

**Comment by nesquena** [comment]
@cblackburn-ajla Perfectly reasonable frustrations. It's clear I think to everyone at this point that we could use new contributors to help address some of these issues. If anyone is interested in taking the baton and helping to revive development and get Padrino back into a place where things like this low hanging fruit is addressed, ping me anytime nesquena @ gmail or directly on here. I'd be more than happy to manage adding contributors, and/or reviewing PRs so we can get some of this addressed.

FWIW, I still use Padrino on multiple widely used legacy projects, but I haven't created a new Padrino project in years. I still love using it on those older apps. I would love for new people to feel more comfortable trying it out again. I believe it could still be as relevant today for anyone in Ruby who wants a light-weight Sinatra-powered alternative to Rails

**Comment by cblackburn-ajla** [comment]
@nesquena - I am certainly willing to help out as a contributor.  However, this account @cblackburn-ajla is used for a specific government contract.  I'll see what I can do to alleviate this bundler version issue under my personal account: https://github.com/midwire and submit a PR as soon as I can.

**Comment by nesquena** [comment]
That’d be great, thanks! As for anyone else reading this, I am always happy to merge PRs, and look forward to finding some contributors able to help us bring some fresh energy to this project.

**Comment by yb66** [comment]
@nesquena @cblackburn-ajla I've a PR already for it, #2205, it should keep the problem away for a while.

Regards,
iain

**Comment by yb66** [comment]
Yes, it helps if you've actually put in the pull request and link to it properly (0_º)

There's also #2220 to choose from, which completely removes the guard (among other things).

Regards,
iain

**Comment by nesquena** [comment]
Well I know it's been a way too long time coming, and we should have addressed this over a year ago, but I did merge in the changes now, thanks @Esity @yb66 @rogerhu for submitting these fixes. I will also go ahead and release a new major version of Padrino soon so these can be used in new apps.

Going forward, I will try my best to be more responsive to PRs, but I could really help from new (and previous) contributors. Either way, I want to do what I can to make sure Padrino continues to work in projects.

If anyone is interested, I wonder what it would take to get it working with the latest version of Rails and with the latest version of Ruby?
