### ISSUE TITLE
Relax i18n version requirements for padrino-helpers

### ISSUE THREAD

**Issue by sriedel** [padrino/padrino-framework#2207]
#### What is the current behavior?
Currently, padrino-helpers depends on i18n ~>0.6, >= 0.6.7. We're encountering more and more gems that depend on activesupport 5.x, which in turn depends on i18n >= 0.7, < 2, causing a the dependency to not being able to be resolved.

#### What is the expected behavior?
The padrino-helpers gem can be used concurrently with other gems requiring an up-to-date version of activesupport.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
MRI 2.6.1, Padrino 0.14.4, Sinatra 2.0.5, Rack 2.0.6.

**Comment by basex** [comment]
Left a MR for this: https://github.com/padrino/padrino-framework/pull/2216

**Comment by luke-hill** [comment]
This should be closed as completed imo.
