### ISSUE TITLE
Web site down

### ISSUE THREAD

**Issue by Signum** [padrino/padrino-framework#2222]
Not directly connected to the repository. But the web site http://www.padrinorb.com/ is down.

I can't stop wondering if the project is now officially dead.

**Comment by nesquena** [comment]
Hmm thanks for bringing this up, the entire website is open source here: https://github.com/padrino/padrino-web. It's been a while, I forget who manages the dns pointing to the github pages for the site @wikimatze @DAddYE I am happy to take over the domain costs to keep the site running as well if I don't already manage it and just forgot.

**Comment by DAddYE** [comment]
Thank you guys for pointing this out, my bank issued a new card this year which prevented the automatic renewal of the domain. I updated the details and we should be good.

**Comment by nesquena** [comment]
Looks like it’s back up now, thanks Davide :pray:
