### ISSUE TITLE
Support thor v.1.0.1.

### ISSUE THREAD

**Issue by theorician** [padrino/padrino-framework#2230]
In version 0.15.0, released in May 2020, the version of `thor` required (via ~>) is 0.20, which came out in 2018. Latest is 1.0.1 released in 2019.

Please consider upgrading your Gemfile so that padrino users aren't stuck on old version due to your dependencies. It prevents users from upgrading other gems (e.g. Bourbon) to latest because they have thor ~> 1.0.

The changeset from v0.20.3 to v1.0.1: https://github.com/erikhuda/thor/compare/v0.20.3...v1.0.1

**Comment by nesquena** [comment]
Thanks for bringing this up. I agree as well, if anyone reading this can help with a PR and do some testing to make sure that the latest version of Thor works with Padrino, I'd be happy to merge and review. 

We very likely need a broader audit of the locked versions and bring everything into 2020

**Comment by basex** [comment]
This can be closed, the gem was updatedin https://github.com/padrino/padrino-framework/pull/2235

**Comment by theorician** [comment]
I'd prefer to leave it open until a new version of the gem was released which includes your changes. Currently padrino's master branch is broken (due to the PR that made it in before yours, it looks like.)

**Comment by nesquena** [comment]
Master branch has been fixed now. We can keep this open as you said until we release a new major version.

**Comment by theorician** [comment]
@nesquena Great, thanks! Do you have a timeline for a release?

**Comment by theorician** [comment]
@nesquena Ping?

**Comment by nesquena** [comment]
Better late than never? I went ahead and released 0.15.1. Sorry about the super extended delay here. If anyone wants contributor access so they can help in managing future releases, contact me at nesquena AT gmail (dot) com. I am always happy to push out the release if someone else can help with running tests, updating CHANGELOG for next release, etc
