### ISSUE TITLE
v0.15.1 seems to be incompatible with Sinatra v3

### ISSUE THREAD

**Issue by fallwith** [padrino/padrino-framework#2258]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*

The simple bundling of `gem 'padrino'` in a fresh `Gemfile` with no other `gem` entries will fail.
This appears to be because `padrino` depends on `padrino-core`, which in turn depends on `sinatra` `>= 2.0.0`, which is currently being resolved to Sinatra v3.0.0. Padrino appears to not yet be compatible with Sinatra v3, owing to Padrino's attempts to concatenate onto `CALLERS_TO_IGNORE`, which is now frozen.

#### What is the expected behavior?

Padrino can be bundled successfully.

Ideally, the compatibility issue with Sinatra v3 can be worked out without too much trouble. In the meantime, I think updating `padrino-core`'s dependency on Sinatra to specify `>= 2.0.0, < 3.0.0`* would be wise.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby 3.1.2, Padrino "latest" (0.15.1 was fetched), Sinatra specified by `padrino-core` (3.0.0 was fetched), Rack 2.2.4, macOS and Ubuntu 22.

**Comment by nesquena** [comment]
Thanks for reporting. I would +1 this and would be happy to review and merge any attempt to bring Padrino up to support Sinatra 3 either in a backwards compatible way or if not then via a major version bump. 

As is - Padrino is only compatible with Sinatra 1 or 2

**Comment by wakatara** [comment]
Update on this? I've got an app from 4 years ago I built on padrino and the heroku changes mean I *really* need to upgrade the puppy to a more up to date stack (I quite hearted padrino). 

Is the advice for "modernizing" an older app to lock Sinatra to 2.0 and then gem update everything? Such as was quoted above with the "dependency on Sinatra to specify >= 2.0.0, < 3.0.0" would be wise."

**Comment by nesquena** [comment]
Yes I believe right now you'll need to lock Sinatra to < 3 in order for Padrino to continue to function. 

If anyone is able to look into the change set for upgrading to 3.0, I'd be more then happy to review and merge and release a major version for compatibility

**Comment by wakatara** [comment]
It seems like there are a bunch of little things besides just Sinatra, for
example the new adduce record takes a hash (I just figured out) rather than
the dev, test, prod stanzas in the database.rb file for AR and the like.

Will work through the upgrades from 0.14.3 and see if I can bend Sinatra as
well though it does look like thrte would be more than a little bit to
update padrino.

Will update here after I’ve got things up and running on 0.15.x

Daryl.

**Comment by jkowens** [comment]
This has been resolved by #2259. It will just require a new release.
