### ISSUE TITLE
Getting caxlsx to work with padrino as a template engine

### ISSUE THREAD

**Issue by wakatara** [padrino/padrino-framework#2271]
#### Feature

Working on getting caxlsx a excel spreadsheet creation library to work with Padrino

#### What is the current behavior?

For some reason, I cannot get the caxlsx_rails code I have lifted to register the axlsx template with Padrino to render the output.

#### What is the expected behavior?

The xlsx sheet should render and download.

#### Further details

I've written an initializer to attempt to register and load the template engine and handlers (both lifted pretty verbatim from caxlsx_rails) - though combined two files into the file I named template_engine.

``` ruby
module CaxlsxInitializer
    def self.registered(app)
        ActiveSupport.on_load(:action_view) do
            require 'lib/caxlsx_template_handler'
            ActionView::Template.register_template_handler :axlsx, ActionView::Template::Handlers::AxlsxBuilder.new
        end

        ActiveSupport.on_load(:action_controller) do
            require 'lib/caxlsx_template_engine'
        end
    end
end 
```

in `app.rb` I've included the intializer as well: 

```ruby
module AarkResurrection
  class App < Padrino::Application
    register SassInitializer
    use ConnectionPoolManagement
    register Padrino::Mailer
    register Padrino::Helpers
    register WillPaginate::Sinatra
    register CaxlsxInitializer
    ...
```

I've included the `action_pack` gem and bundle installed it as well as `actionview`.

I'm assuming the issue here is that padrino does not use ActionVIew for its template handlers, but lack knowledge of Padrino internals to get padrino to recognize the library as a handler. 

Can someone help? 

Error I'm getting is 

```bash
RuntimeError at /reports/species_data_dump.xlsx
Template engine not found: axlsx
```

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

ruby 3.2.0
Padrino 0.15.2
OSX 13.1

**Comment by jkowens** [comment]
Sinatra uses [Tilt](https://github.com/rtomayko/tilt) to integrate with template engines, so I assume Padrino would do the same. Tilt does not currently support Axlsx as a template engine, but you can create a custom Tilt template like this:

```
require 'tilt/template'
require 'axlsx'

module Tilt
  class AxlsxTemplate < Template
    self.default_mime_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

    def prepare
    end

    def precompiled_preamble(locals)
      "xlsx_package = ::Axlsx::Package.new"
    end

    def precompiled_postamble(locals)
      "xlsx_package.to_stream.string"
    end

    def precompiled_template(locals)
      data.to_str
    end
  end
end
```

I don't know how to register this template handler in Padrino, so hopefully someone can fill in those gaps. I'll follow up if I figure that part out 😅

**Comment by jkowens** [comment]
With the above code loaded, it looks like doing `render :axlsx, 'dir/index'` might just work.

**Comment by jkowens** [comment]
@wakatara were you able to make an progress on this?

**Comment by wakatara** [comment]
@jkowens 

I actually just got round to working with this today, though you're right!! If you register the Tilt template in initializers and then just render the template you don't even need all the fancy actionview and actionpack stuff that the caxlsx plugin has. 

Just tested it on a trivial example of the template for the species report and it opens up in modern GSheets, Numbers (and I'm assuming Excel) fine. 

thanks so much! Omg, this is actually better and easier to get going than the rails thing.  8-/

**Comment by jkowens** [comment]
I've opened a PR with Tilt to see if this AxlsxTemplate can be included in the gem: https://github.com/rtomayko/tilt/pull/392

**Comment by wakatara** [comment]
Cool. And thanks again **so much** for the help with Tilt. I was struggling to get it working the Rails way and was stunned how easy it was once you showed me the modifications to Tilt. 

(it's been really nice using padrino again, I have to say... feels so much easier getting things done... =] )

**Comment by jkowens** [comment]
@wakatara glad I was able to help 😊  I closed the PR to Tilt, but I threw together a `tilt-caxlsx` gem. Hopefully that will make it even easier for someone in the future.

https://github.com/jkowens/tilt-caxlsx

**Comment by wakatara** [comment]
That is absolutely excellent! NIceeeee! Think I'll go back and change my hacky code to use your gem now... 🤩 

Cause quite honestly, I am shocked no on in padrino has not asked for this before. Literally every single app I have ever built has had some management type (hmm... guess I'm one of those now) ask for being able to download something as an excel...
