### ISSUE TITLE
Slow reloading (and reloader branch)

### ISSUE THREAD

**Issue by philly-mac** [padrino/padrino-framework#835]
Hi,

I have noticed something while using Padrino (currently I am using 0.10.5).

First of all, it a bit long to start, and this is not such a problem. I (re)start very seldom.  But the problem comes when I change a helper file or controller file. In this case I am waiting between 30 seconds  to 2 minutes sometimes for the app to reload. 

What makes this even stranger, is that when I do not change a file that is directly tied to the framework, such as the models, or the views (mine are datamapper and haml respectively), then I am only waiting for maybe 5 seconds for the reload to happen. 

As you can imagine, 30 seconds here, and 1 minute there, soon adds up and I think I have easily spent a couple of hours in a few weeks just waiting for padrino to reload. 

Is there anything that I could check that could be causing it to take so long to do the reloads? I have checked the logs, and even started padrino with strace, but I wasn't able to see what was causing the slowness.

**Comment by lesniakania** [comment]
I have the same issue using the latest (even master) version. The boot process is soooo long (over 3 minutes) - first, all the model describes (btw can I turn it off?), then loading controllers and other files taking ages.
It's impossible to do TDD - I can't wait over 3 minutes to run a test...
Was this reloader branch merged to the master? I can't test it now, cause it's too old - I have newer active support dependencies etc.
