### ISSUE TITLE
Couch potato orm component

### ISSUE THREAD

**Issue by froderik** [padrino/padrino-framework#849]
I tried out the couchrest thingie first but didn't like it as much as [couch potato](https://github.com/langalex/couch_potato) so I made the switch easily. And then I have tried to integrate the thing as a component also. The main stuff is there but I have some problem with the admin generators. If someone familiar with that code could have a look at my attempt I am sure it is only a matter of minutes before the couch potato support is there. [My fork](https://github.com/froderik/padrino-framework) only contains these changes.

More specifically I am getting bad code in controllers/session.rb - the model_name is empty so a couple of methods are missing recievers.

**Comment by ujifgc** [comment]
Closing in favor of #1494
