### ISSUE TITLE
Don't know how to build task 'ar:auto:upgrade'

### ISSUE THREAD

**Issue by joslinm** [padrino/padrino-framework#942]
In the documentation, it seems to indicate that I can use the `padrino rake ar:auto:upgrade`, but it's not working. 

mark@mark-laptop:~/dev/projects/bitfountain/yipp$ padrino rake ar:auto:upgrade
=> Executing Rake ar:auto:upgrade ...
rake aborted!
Don't know how to build task 'ar:auto:upgrade'

(See full trace by running task with --trace)

**Comment by pfhawkins** [comment]
I hope I'm not a bother, but I found that same inaccurate information in the docs two years later. So while this issue has been closed, the fix (updating the docs) does not seem to have been applied.

**Comment by robermorales** [comment]
[](http://padrinorb.com/guides/features/rake-tasks/#activerecord-tasks)
